// 社交服务接口测试（不开浏览器）：拍卖（上架 / 幂等 / 购买 / 邮件交割 / 到期退回 / 下架）、邮件（领取幂等 / 好友寄信 / 删除）、
// 签到（跨天 / 连续 / 断签）、排行榜、公告校验与广播、管理员（权限 / 发放 / 群发 / 邀请码 / 日志 / 强制下架）
// 用法：node test/svc_api.mjs（用联机组的真实服务端 + 临时数据库，见 test/svc_host.mjs）
import { startHost } from './svc_host.mjs';
const H = await startHost({ admins: ['gm'] });
let pass = 0, fail = 0;
const ok = (c, msg, extra) => { if (c) { pass++; console.log('  ✓', msg); } else { fail++; console.log('  ✗', msg, extra !== undefined ? JSON.stringify(extra) : ''); } };
const step = s => console.log('·', s);
const A = (m, p, b) => H.api('alice', m, p, b), B = (m, p, b) => H.api('bob', m, p, b), G = (m, p, b) => H.api('gm', m, p, b);
const HOUR = 3600000;
const msgs = async who => { await new Promise(r => setTimeout(r, 250)); return H.msgs(who); };
const sword = { id: 11, key: 'katana_10_2', kind: 'equip', slot: 'weapon', name: '寒光太刀', rar: 2, lvl: 10, grade: 3, enh: 5, st: { atk: 300 }, cls: 'sword', wtype: 'katana', dur: 30, durMax: 30, price: 5000 };
const pots = { id: 12, key: 'hpM', kind: 'use', name: '普通HP药剂', rar: 0, n: 20, price: 60 };
try {
  step('拍卖：上架');
  let r = await A('POST', '/api/auction/list', { item: sword, price: 10000, hours: 24, rid: 'a1', char: '爱丽丝' });
  ok(r.status === 200 && r.id && r.fee === 50, '上架成功，保管费 = 10000×0.5%×1 = 50', r);
  const aid = r.id;
  r = await A('POST', '/api/auction/list', { item: sword, price: 10000, hours: 24, rid: 'a1', char: '爱丽丝' });
  ok(r.again && r.id === aid, '同一个 rid 重复上架：返回同一条挂单（幂等）', r);
  r = await A('POST', '/api/auction/list', { item: { ...pots, kind: 'quest' }, price: 10, hours: 24, rid: 'a-q' });
  ok(r.status === 400, '任务道具不能上架', r);
  r = await A('POST', '/api/auction/list', { item: { ...sword, bind: 'account' }, price: 10, hours: 24, rid: 'a-b' });
  ok(r.status === 400, '账号绑定不能上架', r);
  r = await A('POST', '/api/auction/list', { item: pots, price: 10, hours: 7, rid: 'a-h' });
  ok(r.status === 400, '时长只能 12 / 24 / 48', r);
  r = await A('POST', '/api/auction/list', { item: pots, price: 2000, hours: 12, rid: 'a2', char: '爱丽丝' });
  ok(r.status === 200 && r.fee === 10, '药剂 ×20 上架 12 小时，保管费最低 10', r);
  const potId = r.id;

  step('拍卖：搜索 / 筛选 / 排序');
  r = await B('GET', '/api/auction/search');
  ok(r.total === 2 && r.list.length === 2, '搜索全部：2 件', r.total);
  ok(r.list[0].unit <= r.list[1].unit, '默认按单价从低到高', r.list.map(x => x.unit));
  r = await B('GET', '/api/auction/search?cat=weapon');
  ok(r.total === 1 && r.list[0].name === '寒光太刀', '按类别（武器）', r.total);
  r = await B('GET', '/api/auction/search?q=' + encodeURIComponent('HP'));
  ok(r.total === 1 && r.list[0].key === 'hpM', '按名称关键字', r.total);
  r = await B('GET', '/api/auction/search?cls=gun');
  ok(r.total === 1 && r.list[0].key === 'hpM', '职业筛选：神枪手看不到鬼剑士武器，看得到药剂', r.list.map(x => x.key));
  r = await B('GET', '/api/auction/search?rar=2&lvmin=5&lvmax=15');
  ok(r.total === 1 && r.list[0].rar === 2, '按品级 + 等级区间', r.total);
  r = await B('GET', '/api/auction/search?sort=price_desc');
  ok(r.list[0].price === 10000, '按总价从高到低', r.list.map(x => x.price));

  step('拍卖：购买 → 双方邮件到账');
  r = await A('POST', '/api/auction/buy', { id: aid, rid: 'self' });
  ok(r.status === 400, '不能买自己的东西', r);
  r = await B('POST', '/api/auction/buy', { id: aid, rid: 'b1', price: 9999 });
  ok(r.status === 409, '价格对不上时拒绝（防止买到改价后的东西）', r);
  r = await B('POST', '/api/auction/buy', { id: aid, rid: 'b1', price: 10000, char: '鲍勃' });
  ok(r.status === 200 && r.price === 10000, '一口价购买成功', r);
  r = await B('POST', '/api/auction/buy', { id: aid, rid: 'b1' });
  ok(r.status === 200 && r.again, '同一个 rid 重复购买：返回成功（幂等，不重复扣）', r);
  r = await A('POST', '/api/auction/buy', { id: aid, rid: 'x' });
  ok(r.status === 409 || r.status === 400, '已售出的不能再买', r);
  const bm = await B('GET', '/api/mail');
  const buyMail = bm.list.find(m => m.kind === 'auction' && m.title.includes('购买成功'));
  ok(buyMail && buyMail.items.length === 1 && buyMail.items[0].item.key === 'katana_10_2' && buyMail.items[0].item.enh === 5 && buyMail.expires === null, '买家收到物品邮件（原物，+5，永久保存）', buyMail);
  const am = await A('GET', '/api/mail');
  const sellMail = am.list.find(m => m.kind === 'auction' && m.title.includes('出售成功'));
  ok(sellMail && sellMail.gold === 9500, '卖家收到 9500 G（扣 5% 手续费）', sellMail && sellMail.gold);
  const bMsgs = await msgs('bob');
  ok(bMsgs.some(m => m.t === 'mail:new' && m.unread >= 1), '买家收到 WS 新邮件推送 mail:new', bMsgs);

  step('邮件：领取（幂等）/ 删除');
  r = await B('DELETE', `/api/mail/${buyMail.id}`);
  ok(r.status === 400, '有附件没领取时不能删除', r);
  r = await B('POST', '/api/mail/claim', { id: buyMail.id, rid: 'c1' });
  ok(r.status === 200 && r.items[0].item.key === 'katana_10_2', '领取附件：返回物品', r);
  r = await B('POST', '/api/mail/claim', { id: buyMail.id, rid: 'c1' });
  ok(r.status === 200 && r.again && r.items.length === 1, '同一个 rid 重复领取：返回同样的附件（断网重试）', r);
  r = await B('POST', '/api/mail/claim', { id: buyMail.id, rid: 'c2' });
  ok(r.status === 409, '换一个 rid 再领：拒绝（不会领两次）', r);
  r = await B('GET', '/api/mail/unread');
  ok(r.pending === 0, '未领取数归零', r);
  r = await B('DELETE', `/api/mail/${buyMail.id}`);
  ok(r.status === 200, '领取后可以删除', r);

  step('邮件：好友寄信');
  r = await A('POST', '/api/mail/send', { to: 'bob', title: '送你药', body: '加油', gold: 500, items: [{ item: pots }], rid: 's1' });
  ok(r.status === 200 && r.id, '给好友寄信（金币 + 物品）', r);
  r = await A('POST', '/api/mail/send', { to: 'bob', title: '送你药', gold: 500, items: [{ item: pots }], rid: 's1' });
  ok(r.again, '同一个 rid 只寄一次', r);
  r = await A('POST', '/api/mail/send', { to: 'gm', title: 'hi', rid: 's2' });
  ok(r.status === 403, '不是好友不能寄', r);
  r = await A('POST', '/api/mail/send', { to: 'bob', title: 'hi', cera: 10, rid: 's3' });
  ok(r.status === 400, '点券不能在玩家之间邮寄', r);
  r = await B('GET', '/api/mail');
  const fm = r.list.find(m => m.kind === 'friend');
  ok(fm && fm.from === 'alice' && fm.gold === 500 && fm.items[0].item.n === 20 && fm.expires - fm.created === 30 * 24 * HOUR, '好友邮件：来自 alice，500 G + 药剂 ×20，30 天过期', fm);

  step('拍卖：下架 / 到期退回');
  r = await A('POST', '/api/auction/list', { item: { ...sword, id: 99, enh: 0 }, price: 3000, hours: 48, rid: 'a3' });
  const cid = r.id;
  ok(r.fee === 30, '48 小时保管费 = 3000×0.5%×2 = 30', r);
  r = await B('POST', '/api/auction/cancel', { id: cid });
  ok(r.status === 404, '不能下架别人的东西', r);
  r = await A('POST', '/api/auction/cancel', { id: cid });
  ok(r.status === 200, '下架成功', r);
  r = await A('GET', '/api/mail');
  ok(r.list.some(m => m.title.startsWith('取消上架') && m.items.length === 1), '下架的物品通过邮件退回', r.list.map(m => m.title));
  r = await G('POST', '/api/gm/test/time', { add: 13 * HOUR });
  ok(r.expired === 1, '时间前进 13 小时：12 小时的药剂挂单到期', r);
  r = await A('GET', '/api/mail');
  const back = r.list.find(m => m.title.startsWith('到期退回'));
  ok(back && back.items[0].item.key === 'hpM' && back.items[0].item.n === 20 && back.expires === null, '到期的物品邮件退回卖家（永久保存）', back);
  r = await A('GET', '/api/auction/mine');
  ok(r.on.length === 0 && r.history.some(a => a.id === potId && a.status === 'expired') && r.history.some(a => a.id === aid && a.status === 'sold'), '我的拍卖：历史里有已售 / 到期', r.history.map(a => [a.id, a.status]));
  r = await B('GET', '/api/auction/price?key=katana_10_2');
  ok(r.sold === 1 && r.avg === 10000, '成交价参考：近 7 天 1 笔，均价 10000', r);
  for (let i = 0; i < 10; i++) await A('POST', '/api/auction/list', { item: { ...pots, n: 1 }, price: 100, hours: 24, rid: 'm' + i });
  r = await A('POST', '/api/auction/list', { item: { ...pots, n: 1 }, price: 100, hours: 24, rid: 'm10' });
  ok(r.status === 400 && /10/.test(r.error), '同时最多上架 10 件', r);

  step('签到');
  r = await A('GET', '/api/signin');
  ok(!r.signed && r.count === 0 && r.rewards.length === 31 && r.daysInMonth >= 28, '还没签到，奖励表 31 天', { signed: r.signed, count: r.count });
  const monthStart = r.today.endsWith('-01');
  r = await A('POST', '/api/signin');
  ok(r.status === 200 && r.count === 1 && r.streak === 1 && r.mailId, '签到成功：第 1 天，连续 1 天，奖励邮件', r);
  const sm = (await A('GET', '/api/mail')).list.find(m => m.id === r.mailId);
  ok(sm && sm.gold === 3000 && sm.from === '每日签到', '签到奖励邮件：3000 G', sm);
  r = await A('POST', '/api/signin');
  ok(r.status === 409, '同一天不能签两次', r);
  await G('POST', '/api/gm/test/time', { add: 24 * HOUR });
  r = await A('POST', '/api/signin');
  ok(r.status === 200 && r.streak === 2, '第二天签到：连续 2 天', r);
  await G('POST', '/api/gm/test/time', { add: 24 * HOUR });
  r = await A('POST', '/api/signin');
  ok(r.status === 200 && r.streak === 3 && r.bonus && r.bonus.cera === 30, '连续 3 天：额外点券 30', r);
  await G('POST', '/api/gm/test/time', { add: 48 * HOUR });
  r = await A('POST', '/api/signin');
  ok(r.status === 200 && r.streak === 1, '断签一天后：连续天数从 1 重新算', r);
  ok(monthStart || r.count >= 1, '本月签到次数按月累计', r.count);

  step('排行榜');
  await A('POST', '/api/rank/report', { cid: '100', char: '爱丽丝', cls: 'sword', job: 'blade', lvl: 20, exp: 500, score: 4000, epics: 3, chars: ['100', '101'] });
  await A('POST', '/api/rank/report', { cid: '101', char: '爱丽丝小号', cls: 'mage', lvl: 5, exp: 10, score: 300, epics: 0 });
  await B('POST', '/api/rank/report', { cid: '200', char: '鲍勃', cls: 'gun', lvl: 20, exp: 900, score: 5000, epics: 1 });
  await G('POST', '/api/rank/report', { cid: '300', char: '管理员', cls: 'mage', lvl: 30, exp: 0, score: 9000, epics: 0 });
  r = await A('GET', '/api/rank?board=lvl');
  ok(r.list.map(e => e.char).join() === '管理员,鲍勃,爱丽丝,爱丽丝小号', '等级榜：同等级比经验', r.list.map(e => e.char));
  ok(r.me.length === 2 && r.me[0].rank === 3, '我的名次：两个角色都列出来', r.me);
  r = await A('GET', '/api/rank?board=lvl&scope=friends');
  ok(r.list.map(e => e.char).join() === '鲍勃,爱丽丝,爱丽丝小号', '好友榜：只有自己和好友', r.list.map(e => e.char));
  r = await A('GET', '/api/rank?board=score');
  ok(r.list[0].char === '管理员' && r.list[1].char === '鲍勃', '装备评分榜', r.list.map(e => e.score));
  r = await A('GET', '/api/rank?board=epic');
  ok(r.list.length === 2 && r.list[0].char === '爱丽丝', '史诗收集榜（0 件的不上榜）', r.list.map(e => [e.char, e.epics]));
  await A('POST', '/api/rank/clear', { cid: '100', dungeon: 'lorien', diff: 0, time: 60000 });
  r = await A('POST', '/api/rank/clear', { cid: '100', dungeon: 'lorien', diff: 0, time: 70000 });
  ok(!r.record && r.best === 60000, '更慢的通关不覆盖最快记录', r);
  r = await B('POST', '/api/rank/clear', { cid: '200', dungeon: 'lorien', diff: 0, time: 45000 });
  ok(r.record, '鲍勃刷新记录', r);
  r = await A('GET', '/api/rank?board=clear&dungeon=lorien&diff=0');
  ok(r.list.map(e => [e.char, e.time]).join() === '鲍勃,45000,爱丽丝,60000', '通关时间榜：用时短的在前', r.list.map(e => [e.char, e.time]));
  await A('POST', '/api/rank/duel', { cid: '100', win: true }); await A('POST', '/api/rank/duel', { cid: '100', win: true });
  await B('POST', '/api/rank/duel', { cid: '200', win: false }); await B('POST', '/api/rank/duel', { cid: '200', win: true });
  r = await A('GET', '/api/rank?board=duel');
  ok(r.list[0].char === '爱丽丝' && r.list[0].win === 2 && r.list[1].win === 1 && r.list[1].lose === 1, '决斗胜场榜', r.list.map(e => [e.char, e.win, e.lose]));
  await A('POST', '/api/rank/report', { cid: '100', char: '爱丽丝', cls: 'sword', job: 'blade', lvl: 21, exp: 0, score: 4100, epics: 3, chars: ['100'] });
  r = await A('GET', '/api/rank?board=lvl');
  ok(!r.list.some(e => e.char === '爱丽丝小号'), '删掉的角色自动下榜', r.list.map(e => e.char));

  step('全服公告');
  H.msgs('alice'); H.msgs('bob');
  r = await A('POST', '/api/notice', { kind: 'enhance', char: '爱丽丝', item: { key: 'katana_10_2', name: '寒光太刀', rar: 2, enh: 12 }, lvl: 12 });
  ok(r.status === 200 && r.notice.text === '勇士「爱丽丝」将 [寒光太刀] 强化到了 +12！', '强化 +12 公告文案', r.notice && r.notice.text);
  const bn = (await msgs('bob')).filter(m => m.t === 'notice:show');
  ok(bn.length === 1 && bn[0].item.rar === 2, '广播给其他在线玩家（带品级，客户端上色）', bn);
  r = await A('POST', '/api/notice', { kind: 'enhance', item: { name: 'x' }, lvl: 9 });
  ok(r.status === 400, '+9 不发公告', r);
  r = await A('POST', '/api/notice', { kind: 'custom', text: '我是管理员' });
  ok(r.status === 400, '玩家不能发 custom（只有管理员后台能发）', r);
  r = await A('POST', '/api/notice', { kind: 'epic', char: '爱丽丝', item: { name: '[假]<b>名</b>', rar: 5 }, place: '天空之城' });
  ok(r.status === 200 && !r.notice.text.includes('[假]') && r.notice.text.includes('<b>'), '名字里的方括号被去掉（HTML 由客户端转义显示）', r.notice && r.notice.text);
  for (const k of ['skyset', 'box', 'multi', 'job', 'awaken', 'firstClear', 'amplify']) {
    r = await A('POST', '/api/notice', { kind: k, char: '爱丽丝', item: { name: '天空套', rar: 4 }, name: '天空套', box: '魔盒', job: '剑魂', place: '城主宫殿', lvl: 10 });
    ok(r.status === 200, `公告 ${k}：${r.notice && r.notice.text}`, r);
  }
  r = await A('GET', '/api/notice/recent');
  ok(r.list.length >= 7 && r.list[0].char, '最近公告列表', r.list.length);

  step('管理员');
  r = await A('POST', '/api/gm/mail', { to: ['bob'], title: 'x' });
  ok(r.status === 403, '普通玩家调不了管理员接口', r);
  r = await G('POST', '/api/gm/mail', { to: ['bob', 'alice'], title: '补偿', body: '维护补偿', gold: 10000, cera: 500, items: [{ key: 'fatigue', n: 2 }, { key: 'katana_10_2', n: 1, opt: { enh: 7, grade: 4 } }] });
  ok(r.status === 200 && r.n === 2, '给两个玩家发放金币 / 点券 / 物品', r);
  r = await B('GET', '/api/mail');
  const gmm = r.list.find(m => m.kind === 'gm');
  ok(gmm && gmm.gold === 10000 && gmm.cera === 500 && gmm.items[1].opt.enh === 7 && gmm.from === '管理员', '玩家收到管理员邮件（装备带强化等级）', gmm);
  r = await G('POST', '/api/gm/mail', { to: '*', title: '全服福利', cera: 100 });
  ok(r.n === 3, '群发给全体玩家', r);
  r = await G('POST', '/api/gm/mail', { to: ['nobody'], title: 'x' });
  ok(r.status === 404, '收件人不存在时报错', r);
  r = await G('POST', '/api/gm/invite', { n: 2, note: '给朋友' });
  ok(r.codes.length === 2, '生成 2 个邀请码', r);
  r = await G('GET', '/api/gm/invites');
  ok(r.list.length === 2, '邀请码列表', r.list.length);
  r = await G('GET', '/api/gm/online');
  ok(r.list.length === 3 && r.list.some(o => o.name === 'bob'), '在线玩家列表', r.list.length);
  H.msgs('bob');
  r = await G('POST', '/api/gm/notice', { text: '今晚 8 点维护' });
  ok(r.status === 200 && (await msgs('bob')).some(m => m.t === 'notice:show' && m.kind === 'custom' && m.text === '今晚 8 点维护'), '管理员全服公告', r);
  r = await G('GET', '/api/gm/logs?type=auction');
  ok(r.list.some(x => x.type === 'auction.buy') && r.list.some(x => x.type === 'auction.expire') && r.list.every(x => x.type.startsWith('auction')), '拍卖日志（上架 / 成交 / 到期 / 下架）', [...new Set(r.list.map(x => x.type))]);
  r = await G('GET', '/api/gm/logs?type=mail');
  ok(r.list.some(x => x.type === 'mail.claim') && r.list.some(x => x.type === 'mail.send'), '邮件日志（寄信 / 领取）', [...new Set(r.list.map(x => x.type))]);
  await A('POST', '/api/auction/list', { item: { ...pots, n: 3 }, price: 300, hours: 48, rid: 'g1' });
  r = await G('GET', '/api/gm/auction?status=on');
  ok(r.list.length === 1 && r.list[0].seller === 'alice', '管理员查看在售挂单（前面 24 小时的已经到期）', r.list.length);
  r = await G('POST', '/api/gm/auction/cancel', { id: r.list[0].id });
  ok(r.ok, '强制下架', r);
  r = await A('GET', '/api/mail');
  ok(r.list.some(m => m.title.startsWith('管理员下架')), '强制下架的物品邮件退回卖家', r.list.map(m => m.title).slice(0, 3));

  step('邮件过期：好友邮件没领的附件退回寄件人');
  await G('POST', '/api/gm/test/time', { add: 31 * 24 * HOUR });
  H.tick();
  r = await B('GET', '/api/mail');
  ok(!r.list.some(m => m.kind === 'friend'), '30 天后好友邮件过期', r.list.map(m => m.title));
  r = await A('GET', '/api/mail');
  const ret = r.list.find(m => m.title.startsWith('退回：'));
  ok(ret && ret.gold === 500 && ret.items[0].item.key === 'hpM', '附件退回给寄件人', ret);
  ok(r.list.some(m => m.kind === 'auction'), '拍卖行邮件不过期', r.list.map(m => m.kind));
} catch (e) { fail++; console.log('  ✗ 异常', e.stack); }
await H.close();
console.log(`\n${pass} 项通过，${fail} 项失败`);
process.exit(fail ? 1 : 0);
