// 公会 / 成就点排行 接口测试（不开浏览器，真实服务端 + 临时数据库）：创建（幂等 / 重名 / 徽章校验）、申请 / 审批、邀请 / 接受、职位 / 转让 / 踢人 / 离开 / 解散、
// 公告 / 留言、公会频道（WS）、贡献（每日上限、签到加贡献、升级与技能解锁）、公会商店（等级 / 周限购 / 幂等 / 贡献不足）、名牌标签、公会排行、成就点排行
import { startHost } from './svc_host.mjs';
const H = await startHost({ admins: ['gm'], users: ['alice', 'bob', 'carol', 'dave', 'gm'], friends: [] });
let pass = 0, fail = 0;
const ok = (c, msg, extra) => { if (c) { pass++; console.log('  ✓', msg); } else { fail++; console.log('  ✗', msg, extra !== undefined ? JSON.stringify(extra) : ''); } };
const step = s => console.log('·', s);
const msgs = async who => { await new Promise(r => setTimeout(r, 250)); return H.msgs(who); };
const A = (m, p, b) => H.api('alice', m, p, b), B = (m, p, b) => H.api('bob', m, p, b), C = (m, p, b) => H.api('carol', m, p, b), D = (m, p, b) => H.api('dave', m, p, b), G = (m, p, b) => H.api('gm', m, p, b);
const badge = { s: 2, c: 3, g: '龙' };
try {
  step('创建');
  let r = await A('POST', '/api/guild/create', { name: '破晓', badge: { s: 1, c: 1, g: 'ab' }, rid: 'c0' });
  ok(r.status === 400, '徽章文字只能 1 个字', r);
  r = await A('POST', '/api/guild/create', { name: '破', badge, rid: 'c0' });
  ok(r.status === 400, '公会名至少 2 个字', r);
  r = await A('POST', '/api/guild/create', { name: '破晓之光', badge, rid: 'c1', char: '爱丽丝' });
  ok(r.status === 200 && r.id, '创建成功', r);
  const gid = r.id;
  r = await A('POST', '/api/guild/create', { name: '破晓之光', badge, rid: 'c1' });
  ok(r.again && r.id === gid, '同一个 rid 重复创建：返回同一个公会（金币不会扣两次）', r);
  r = await B('POST', '/api/guild/create', { name: '破晓之光', badge, rid: 'b1' });
  ok(r.status === 409, '重名不能创建', r);
  r = await A('POST', '/api/guild/create', { name: '别的公会', badge, rid: 'c2' });
  ok(r.status === 400, '已经在公会里不能再创建', r);
  r = await A('GET', '/api/guild');
  ok(r.guild && r.guild.name === '破晓之光' && r.me.role === 'leader' && r.members.length === 1 && r.guild.maxMembers === 10 && r.perks.length === 9, '我的公会：会长，1/10 人，9 个公会技能', { g: r.guild, me: r.me });
  ok(r.posts.some(p => p.sys && p.text.includes('创建了公会')), '公会动态：创建', r.posts.map(p => p.text));

  step('申请 / 审批');
  r = await B('GET', '/api/guild/list');
  ok(r.list.length === 1 && r.list[0].leader === 'alice' && r.list[0].members === 1, '公会列表', r.list);
  r = await B('POST', '/api/guild/apply', { id: gid, msg: '带我一个' });
  ok(r.status === 200 && !r.joined, 'bob 申请加入（需要审批）', r);
  const au = (await msgs('alice')).filter(m => m.t === 'guild:update');
  ok(au.some(m => m.why === 'apply'), '会长收到申请通知（WS guild:update）', au);
  r = await A('GET', '/api/guild');
  ok(r.reqs.length === 1 && r.reqs[0].name === 'bob' && r.reqs[0].msg === '带我一个', '会长看到申请', r.reqs);
  r = await B('POST', '/api/guild/post', { text: 'hi' });
  ok(r.status === 400, '还没加入不能留言', r);
  r = await A('POST', '/api/guild/approve', { user: 'bob', ok: true });
  ok(r.status === 200, '批准', r);
  r = await B('GET', '/api/guild');
  ok(r.guild && r.me.role === 'member', 'bob 成为成员', r.me);
  const tagsMsg = (await msgs('carol')).filter(m => m.t === 'guild:tags');
  ok(tagsMsg.length >= 1, '所有在线玩家收到名牌标签刷新通知', tagsMsg.length);
  r = await C('GET', '/api/guild/tags');
  ok(r.map[H.users.find(u => u.name === 'alice').id] === '破晓之光' && r.map[H.users.find(u => u.name === 'bob').id] === '破晓之光', '名牌标签：alice、bob → 破晓之光', r.map);

  step('邀请 / 接受 / 拒绝');
  r = await B('POST', '/api/guild/invite', { user: 'carol' });
  ok(r.status === 403, '普通成员不能邀请', r);
  r = await A('POST', '/api/guild/invite', { user: 'carol' });
  ok(r.status === 200 && r.online, '会长邀请 carol', r);
  const ci = (await msgs('carol')).find(m => m.t === 'guild:invite');
  ok(ci && ci.guild === '破晓之光' && ci.from === 'alice', 'carol 收到邀请推送', ci);
  r = await C('GET', '/api/guild');
  ok(!r.guild && r.invites.length === 1 && r.invites[0].by === 'alice', 'carol 的邀请列表', r.invites);
  r = await C('POST', '/api/guild/accept', { id: gid });
  ok(r.status === 200, 'carol 接受邀请', r);
  await A('POST', '/api/guild/invite', { user: 'dave' });
  r = await D('POST', '/api/guild/decline', { id: gid });
  r = await D('GET', '/api/guild');
  ok(!r.guild && r.invites.length === 0, 'dave 拒绝邀请', r.invites);

  step('职位 / 转让 / 踢人');
  r = await B('POST', '/api/guild/role', { user: 'carol', role: 'vice' });
  ok(r.status === 403, '只有会长能任命', r);
  r = await A('POST', '/api/guild/role', { user: 'carol', role: 'vice' });
  ok(r.status === 200, '任命 carol 为副会长', r);
  r = await C('POST', '/api/guild/kick', { user: 'alice' });
  ok(r.status === 403, '副会长不能踢会长', r);
  r = await C('POST', '/api/guild/notice', { text: '今晚 8 点一起打深渊' });
  ok(r.status === 200, '副会长修改公告', r);
  r = await B('GET', '/api/guild');
  ok(r.guild.notice === '今晚 8 点一起打深渊', '成员看到新公告', r.guild.notice);
  r = await B('POST', '/api/guild/post', { text: '收到！', char: '鲍勃' });
  ok(r.status === 200, '成员留言', r);
  r = await C('DELETE', `/api/guild/post/${r.id}`);
  ok(r.status === 200, '副会长可以删留言', r);
  r = await A('POST', '/api/guild/transfer', { user: 'carol' });
  ok(r.status === 200, '会长转让给 carol', r);
  r = await A('GET', '/api/guild');
  ok(r.me.role === 'vice' && r.guild.leader === 'carol', '转让后：alice 副会长，carol 会长', { me: r.me.role, leader: r.guild.leader });
  r = await C('POST', '/api/guild/leave');
  ok(r.status === 400, '会长（还有别人时）不能直接离开', r);
  r = await C('POST', '/api/guild/transfer', { user: 'alice' });
  r = await A('POST', '/api/guild/kick', { user: 'bob' });
  ok(r.status === 200, '会长请离 bob', r);
  ok((await msgs('bob')).some(m => m.t === 'guild:update' && m.why === 'kicked'), 'bob 收到被请离通知');
  r = await B('GET', '/api/guild');
  ok(!r.guild, 'bob 不在公会里了', r.guild);

  step('公会频道');
  await new Promise(r => setTimeout(r, 200)); H.msgs('alice'); H.msgs('carol'); H.msgs('bob');
  H.say('carol', { t: 'guild:say', text: '大家好' });
  const ga = (await msgs('alice')).filter(m => m.t === 'chat' && m.ch === 'guild');
  const gb = (await msgs('bob')).filter(m => m.t === 'chat' && m.ch === 'guild');
  ok(ga.length === 1 && ga[0].text === '大家好' && ga[0].from.name === 'carol', '公会频道：成员收到', ga);
  ok(gb.length === 0, '非成员收不到', gb);

  step('贡献与等级');
  r = await A('POST', '/api/guild/contrib', { kind: 'clear' });
  ok(r.gain === 10 && r.contrib === 10, '通关 +10 贡献', r);
  for (let i = 0; i < 25; i++) r = await A('POST', '/api/guild/contrib', { kind: 'clear' });
  ok(r.gain === 0 && r.contrib === 200, '每天通关贡献上限 20 次（200）', r);
  for (let i = 0; i < 6; i++) r = await A('POST', '/api/guild/contrib', { kind: 'abyss' });
  ok(r.contrib === 400, '深渊 +40，每天 5 次', r);
  r = await A('POST', '/api/signin');
  ok(r.guild === 30, '签到同时给公会 +30', r.guild);
  const g1 = (await A('GET', '/api/guild')).guild;
  ok(g1.exp === 430 && g1.lvl === 1, '公会经验累计 430（Lv.1）', g1);
  H.ctx.db.run('UPDATE guild SET exp = 990 WHERE id = ?', gid);
  H.msgs('alice');
  r = await C('POST', '/api/guild/contrib', { kind: 'clear' });
  ok(r.lvl === 2, '经验到 1000：公会升到 Lv.2', r);
  const up = (await msgs('alice'));
  ok(up.some(m => m.t === 'chat' && m.ch === 'guild' && /Lv\.2/.test(m.text) && /公会之力/.test(m.text)), '公会频道公告升级和解锁的技能', up.map(m => m.text).filter(Boolean));
  ok(up.some(m => m.t === 'notice:show' && /破晓之光/.test(m.text)), '全服公告公会升级', up.filter(m => m.t === 'notice:show'));

  step('公会商店');
  r = await A('POST', '/api/guild/shop/buy', { id: 'box', rid: 's1' });
  ok(r.status === 403, 'Lv.4 的商品：公会等级不够', r);
  r = await A('POST', '/api/guild/shop/buy', { id: 'fatigue', rid: 's2' });
  ok(r.status === 200 && r.items[0].key === 'fatigue' && r.contrib === 370, '兑换抗疲劳秘药：430 - 60 = 370', r);
  r = await A('POST', '/api/guild/shop/buy', { id: 'fatigue', rid: 's2' });
  ok(r.again && r.items[0].key === 'fatigue', '同一个 rid：返回同样的物品，不重复扣', r);
  ok((await A('GET', '/api/guild')).me.contrib === 370, '贡献只扣了一次');
  for (let i = 0; i < 6; i++) r = await A('POST', '/api/guild/shop/buy', { id: 'fatigue', rid: 'f' + i });
  r = await A('POST', '/api/guild/shop/buy', { id: 'fatigue', rid: 'f9' });
  ok(r.status === 400 && /本周/.test(r.error), '每周限购 7 次', r);
  r = await C('POST', '/api/guild/shop/buy', { id: 'guard', rid: 'g1' });
  ok(r.status === 400 && /贡献不足/.test(r.error), '贡献不足', r);
  const shop = (await A('GET', '/api/guild')).shop;
  ok(shop.find(s => s.id === 'fatigue').bought === 7, '商店显示本周已兑换次数', shop.find(s => s.id === 'fatigue'));

  step('公会排行 / 离开 / 解散');
  await D('POST', '/api/guild/create', { name: '夜行者', badge: { s: 0, c: 0, g: '★' }, rid: 'd1' });
  r = await B('GET', '/api/guild/rank');
  ok(r.list.length === 2 && r.list[0].name === '破晓之光' && r.list[0].rank === 1, '公会排行：等级高的在前', r.list.map(g => [g.name, g.lvl]));
  r = await C('POST', '/api/guild/leave');
  ok(r.status === 200, 'carol 离开', r);
  r = await A('POST', '/api/guild/disband', { name: '错名' });
  ok(r.status === 400, '解散要输入公会名确认', r);
  r = await A('POST', '/api/guild/disband', { name: '破晓之光' });
  ok(r.status === 200, '解散', r);
  r = await A('GET', '/api/guild');
  ok(!r.guild, '解散后没有公会了', r.guild);
  r = await B('GET', '/api/guild/tags');
  ok(Object.values(r.map).join() === '夜行者', '名牌标签只剩夜行者', r.map);
  r = await D('POST', '/api/guild/leave');
  ok(r.status === 200 && r.disbanded, '只剩会长一个人时离开 = 解散', r);

  step('成就点排行');
  await A('POST', '/api/rank/report', { cid: '1', char: '爱丽丝', cls: 'sword', lvl: 20, ach: 350 });
  await B('POST', '/api/rank/report', { cid: '2', char: '鲍勃', cls: 'gun', lvl: 25, ach: 500 });
  r = await A('GET', '/api/rank?board=ach');
  ok(r.list.map(e => [e.char, e.ach]).join() === '鲍勃,500,爱丽丝,350', '成就点榜', r.list.map(e => [e.char, e.ach]));

  step('日志');
  r = await G('GET', '/api/gm/logs?type=guild');
  ok(r.list.some(x => x.type === 'guild.create') && r.list.some(x => x.type === 'guild.shop') && r.list.some(x => x.type === 'guild.disband'), '管理员日志：创建 / 兑换 / 解散', [...new Set(r.list.map(x => x.type))]);
} catch (e) { fail++; console.log('  ✗ 异常', e.stack); }
await H.close();
console.log(`\n${pass} 项通过，${fail} 项失败`);
process.exit(fail ? 1 : 0);
