/* =====================================================================
   区域：万年雪山 · 斯顿雪域（官方 60 版本 Lv36~56；满级 60 后放在 Lv36~42，接在暗精灵地区中段之后）
   官方依据（国服 60 版本）：每三十年冰龙斯卡萨苏醒一次，饥寒交迫的班图族翻越斯特鲁山脉入侵贝尔玛尔公国的防线；冒险家前往班图族的村庄斯顿雪域交涉。
   班图族分沃克族（狼）、库尼克族（兔）、图卢斯族（野牛）；副族长奥尔卡、族长布万加（四剑圣之一，用钝器）、图卢斯族的巴尔雷娜（善于做盔甲，查理是她失散的哥哥）。
   地下城与领主都是官方的：冰心少年（查理，被冰龙变成冰霜巨人的少年，玩具士兵）、利库天井（寒冰巨人利库）、山脊（野兽师鲁乌格与冰齿沙凡特）、
   白色废墟（塞斯奇，带着一群雪魈的巨猿）、布万加的修炼场（隐藏）、冰雪宫殿（冰雪女王洛丝，雷剑克鲁斯把她当成恋人守护她）、斯卡萨之巢（冰龙斯卡萨）。
   任务名多数取自官方主线（班图族的侵略 / 班图族的副族长 / 真正的战士 / 我的孩子 / 永恒的悲惨命运……）。
   本作原创：招式与机制组合、深渊专属「冰龙斯卡萨的遗骸」、查理的石晶项链做成史诗（官方是任务道具的碎片）。
   复用：寒冰巨人利库 = 暗精灵地区的巨人换色；泡沫 / 寒冰蜘蛛 = 毒蜘蛛换色；冰精灵 = 鬼魂换色；石巨人 / 斯卡萨幼龙 = 天空之城的石巨人 / 飞龙换色；
   野蛮牛族 / 图卢斯族 = 格兰之森的牛头人换色；冰霜 / 青哥布林 = 哥布林换色。
   入口：赫顿玛尔 · 后街（x 1960 往上，Lv.36）
   ===================================================================== */
// 斯卡萨（S1 样板）的两个机制：蓄力龙息（stagger）、起飞（form）——阶段进场放一次，之后按冷却再放
const SKASA_CHARGE = { use: 'stagger', windup: 3.2, need: 0.035, onBreak: 'groggy', say: '绝对零度龙息蓄力中——打断它！', col: '#9ad8ff',
  skill: { use: 'cone', ang: 120, len: 520, windup: 0.4, dur: 1.2, tick: 0.2, dmg: 0.6, status: 'freeze', sdur: 1.2, col: '#9ad8ff', say: '绝对零度龙息！' } };
const SKASA_FLY = { use: 'form', name: '升空', fly: 190, dur: 12, invulT: 1.5, say: '斯卡萨飞上了天空——躲开冰雨！', col: '#e8f4ff',
  skills: [{ use: 'rain', kind: 'hex', n: 7, r: 50, interval: 0.3, windup: 1.2, dmg: 1.0, col: '#bfe6ff', cd: [3.2, 4.2], say: '冰雨' }],
  land: { use: 'aoe', shape: 'circle', at: 'self', r: 170, windup: 0.9, dmg: 1.3, down: true, col: '#bfe6ff', say: '斯卡萨落地了！' } };
// R2 块（docs/BOSS_PLAN.md §2 万年雪山）：要被阶段进场 + 按冷却重放的机制写成常量；洛丝的壁钟是区域钩子，在 snow_bosses.js
// 查理：保护心脏（玩具士兵摸到心脏 → 查理回血）；心脏的冰晶护盾（打碎 → 破招）
const SN_CHARLIE_HEART = { use: 'protect', kind: 'charlieHeart', name: '查理的心脏', lives: 4, at: 0.14, threat: ['toySoldier', 'toyMass', 'toyHard'], spawn: { kind: 'toyMass', n: 2, every: 9, first: 3 },
  onTouch: 'heal', heal: 0.04, onLose: 'heal', col: '#8ad8ff', say: '玩具士兵朝查理的心脏走去了——别让它们碰到！' };
const SN_CHARLIE_SHIELD = { use: 'shield', hits: 12, dur: 14, punish: 'heal', onBreak: 'groggy', col: '#bfe6ff', say: '冰晶之心——打碎它！' };
// 塞斯奇：捶胸咆哮（离远一点）
const SN_SESKI_POUND = { use: 'safezone', mode: 'far', r: 240, windup: 3.0, frac: 0.35, col: '#e8f4ff', say: '捶地——离塞斯奇远一点！' };
// 布万加：班图四勇士车轮战（官方 HK63：马拉加 冰块 / 莱里特拉里 旋风 / 美杜莎莎 石化 / 霍克伊 召鸟），打完族长才亲自上；战吼（贴近他）
const SN_BWANGA_TRIAL = { use: 'gauntlet', boss: 'watch', gap: 1.5, col: '#ffd070', say: '布万加：“先打赢我的四个勇士！”', done: '布万加：“好！轮到我了！”',
  waves: [
    { kind: 'bantuMalaga', name: '勇士马拉加', hp: 1, say: '勇士马拉加——被冰块封住之前打碎它！' },
    { kind: 'bantuLerit', name: '勇士莱里特拉里', hp: 1, say: '勇士莱里特拉里——旋风会把你吸过去，往外跑！' },
    { kind: 'bantuMedusa', name: '勇士美杜莎莎', hp: 1, say: '勇士美杜莎莎——她凝视的时候背对她！' },
    { kind: 'bantuHokey', name: '勇士霍克伊', hp: 1, say: '勇士霍克伊——先打掉他的猎鹰！' }] };
const SN_BWANGA_ROAR = { use: 'safezone', mode: 'near', r: 120, windup: 3.2, frac: 0.35, col: '#ffd070', say: '战吼——贴近布万加！' };
// 洛丝走下王座（最后一个阶段）：钩子解开 rooted，只放这个形态自带的招式
const SN_ROSE_RISE = { use: 'form', name: '走下王座', scale: 1.08, dur: 0, invulT: 1.5, col: '#d8f0ff', say: '洛丝离开了王座——梦境化成了现实！',
  skills: [{ use: 'blink', to: 'away', dist: 240, cd: [6, 8], w: 1 },
    { use: 'aoe', shape: 'circle', at: 'target', r: 72, n: 4, scatter: 160, windup: 1.1, dmg: 1.1, status: 'freeze', sdur: 1.2, col: '#bfe6ff', cd: [5, 7], w: 1.5 },
    { use: 'cone', ang: 80, len: 380, windup: 1.0, dur: 1.0, tick: 0.25, dmg: 0.35, status: 'freeze', sdur: 0.8, col: '#bfe6ff', cd: [7, 9], w: 1.3, say: '冰雪吐息——绕到侧面！' },
    { use: 'shot', mode: 'homing', n: 4, spread: 70, speed: 260, turn: 2.2, dmg: 0.85, status: 'slow', col: '#bfe6ff', cd: [4, 5.5], w: 1.4 }] };
defineRegion({
  id: 'snow', name: '万年雪山 · 斯顿雪域', lvl: 36, lvlMax: 42, power: 1.25, bossPower: 1, atkPower: 1.08,
  entry: { scene: 'hm_backstreet', side: 'up', x: 1960, to: 'storm_pass', minLv: 36, label: '斯顿雪域' },

  themes: {
    snTown: { grade: { tint: 'rgba(120,150,200,0.08)', fog: 'rgba(230,240,255,0.10)' }, ambient: 'motes', rgb: '240,248,255', floorW: 1700,
      pal: { sky: ['#6a7a9a', '#a8b8d0', '#e0e8f4'], haze: '#e8f0ff', floor: ['#c8d0dc', '#d8e0ea', '#b8c0cc'] },
      bg: ['Storm Pass, the snowy mountain village of the Bantu tribes: sturdy log houses and hide tents, tall carved totem poles of a wolf, a rabbit and a bison, smoking chimneys, snowy pine trees, the towering white peaks of the Stru mountains behind, gentle snowfall.',
        'a packed snow village path with wooden boardwalk planks and footprints',
        'a low wooden fence capped with snow, stacked firewood and small carved totem posts'] },
    snCave: { grade: { tint: 'rgba(60,110,180,0.12)', fog: 'rgba(170,220,255,0.10)' }, ambient: 'motes', rgb: '190,230,255', floorW: 1600,
      pal: { sky: ['#0e2238', '#1e3e60', '#3a6a90'], haze: '#9ad8ff', floor: ['#3a5068', '#46607a', '#2e4256'] },
      bg: ["The Frozen Heart cave: a lonely icy cavern where a frozen boy's toys lie scattered, giant blue ice crystals, a toy castle and wooden toy soldiers half encased in ice, soft blue light from above.",
        'smooth blue ice floor with frost patterns and a few scattered wooden toy blocks',
        'ice crystals, a broken wooden rocking horse and small frozen toy drums'] },
    snRidge: { grade: { tint: 'rgba(90,110,150,0.10)', fog: 'rgba(220,230,255,0.12)' }, ambient: 'motes', rgb: '235,242,255', floorW: 1700,
      pal: { sky: ['#4a5a78', '#8a9ab8', '#c8d4e6'], haze: '#dfe8ff', floor: ['#b8c2d0', '#c8d2de', '#a8b2c0'] },
      bg: ['The Ridge of the Eternal Snow Mountain: a windswept mountain ridge with deep snow, jagged icy cliffs, Bantu war banners with wolf and bison emblems on wooden poles, a frozen waterfall and distant snowy peaks under a grey-blue sky.',
        'deep packed snow with dark rocks poking through and wind-blown drifts',
        'snow-covered boulders, broken wooden spears and a low wooden barricade'] },
    snRuins: { edgeHoles: true, grade: { tint: 'rgba(110,120,150,0.10)', fog: 'rgba(240,244,255,0.14)' }, ambient: 'motes', rgb: '245,248,255', floorW: 1600,
      pal: { sky: ['#5a6070', '#9aa0b0', '#d8dce6'], haze: '#f0f4ff', floor: ['#b0b6c0', '#c0c6d0', '#a0a6b0'] },
      bg: ['The White Ruins: ancient stone ruins of an old mountain tribe buried in snow and ice, broken pillars and a collapsed temple, huge hanging icicles, big straw nests of snow apes, pale white fog.',
        'snowy cracked stone tiles with patches of blue ice',
        'broken snowy pillar stumps and frozen straw nests'] },
    snPalace: { grade: { tint: 'rgba(90,140,210,0.10)', fog: 'rgba(200,230,255,0.12)' }, ambient: 'motes', rgb: '210,236,255', floorW: 1800,
      pal: { sky: ['#1a3050', '#3a6a9a', '#9ad0f0'], haze: '#c8ecff', floor: ['#8ab0d0', '#9ac0e0', '#7aa0c0'] },
      bg: ['The Ice Palace of the Snow Queen Rose: a grand dreamlike palace carved from glittering ice and packed snow, tall crystal spires, ice chandeliers, frozen fountains, pale blue silk banners, a cold magical glow.',
        'a polished pale blue ice floor with snowflake mosaics',
        'carved ice balustrades, frozen rose bushes and small ice sculptures'] },
    // 布万加的修炼场（领主房单独的背景，bossTheme；美术队列出图前用程序兜底画面）
    snDojoBoss: { grade: { tint: 'rgba(140,100,60,0.08)', fog: 'rgba(255,230,190,0.10)' }, ambient: 'motes', rgb: '255,236,210', floorW: 1700,
      pal: { sky: ['#5a4a48', '#9a8a80', '#d8ccc0'], haze: '#ffe0b0', wall: ['#5a4030', '#3a2a20'], floor: ['#b8aaa0', '#c8bab0', '#a89a90'], line: 'rgba(120,80,40,.4)' },
      bg: ["Bwanga's training ground of the Bantu tribes on a snowy mountain plateau: a big circular arena fenced with thick log palisades, huge carved bear skull totems and crossed spiked clubs, drying animal hides, braziers with warm fire, Bantu war banners, snowy peaks behind under a pale sky.",
        'a trampled snowy dirt arena floor with footprints, scattered straw and a painted tribal circle',
        'a low log fence with bear skulls, weapon racks holding clubs and axes, and snow drifts'] },
    snNest: { edgeHoles: true, grade: { tint: 'rgba(50,90,160,0.14)', fog: 'rgba(190,220,255,0.14)' }, ambient: 'wisps', rgb: '190,225,255', floorW: 1800,
      pal: { sky: ['#0a1628', '#1a3458', '#4a7aa8'], haze: '#a8d8ff' },
      bg: ["Skasa's Nest, the lair of the ice dragon at the summit of the eternal snow mountain: a vast frozen crater of blue-white glacier ice, giant dragon claw marks on the walls, frozen bones of great beasts, a howling blizzard, huge ice eggs.",
        'rough blue-white glacier ice floor with deep claw scratches and drifting snow',
        'jagged glacier ice shards, frozen beast bones and cracked ice eggs'] },
    snLikBoss: { edgeHoles: true, grade: { tint: 'rgba(60,110,180,0.12)', fog: 'rgba(200,230,255,0.12)' }, ambient: 'motes', rgb: '215,238,255', floorW: 1700, pal: { sky: ['#0e2034', '#23486e', '#6a9ac4'], haze: '#b8e2ff', floor: ['#5a7894', '#6a88a4', '#4a6884'] }, bg: ["The floor of a huge frozen cavern at the bottom of Lik's Well, a colossal shaft deep inside the eternal snow mountain: towering walls of layered blue glacier ice and dark slate rock, shafts of pale daylight falling from openings far above, giant pale-blue ice crystal columns, the huge Bantu ice wall braced by wooden scaffolding with ladders and hanging ropes, thick frozen iron chains hanging from above, gently falling snow.", 'thick cracked blue-grey ice over dark slate rock with frost patterns, scattered ice chunks and a few broken wooden planks', 'jagged pale-blue ice crystal clusters, broken wooden scaffolding planks, coiled frozen rope and dark rocks'] },
  },

  monsters: {
    // 冰心少年：查理的玩具士兵
    toySoldier: { name: '普通型玩具士兵', tier: 'normal', arch: 'aggressive', size: [12, 11, 84], art: 'snToy',
      skills: [{ use: 'swipe', n: 2, dmg: 1.0, cd: [1.5, 2.5], w: 2 }, { use: 'dash', len: 260, speed: 600, windup: 0.8, dmg: 1.0, cd: [5, 7] }] },
    toyFine: { name: '精巧型玩具士兵', tier: 'caster', arch: 'kiter', size: [12, 11, 84], art: ['snToy', { hue: -140, sat: 1.0 }],
      skills: [{ use: 'swipe', dmg: 0.8, reach: 60, cd: [2, 3] }, { use: 'shot', mode: 'straight', speed: 360, dmg: 0.85, cd: [2.8, 4], w: 2 }, { use: 'shot', mode: 'spread', n: 3, spread: 45, speed: 320, dmg: 0.7, cd: [5, 7] }] },
    toyMass: { name: '量产型玩具士兵', tier: 'swarm', arch: 'swarm', size: [11, 10, 70], scale: 0.82, art: ['snToy', { sat: 0.4, bright: 0.95 }],
      traits: { onDeath: 'explode', explode: { r: 70, windup: 0.8, dmg: 0.9 } }, skills: [{ use: 'swipe', dmg: 0.7, reach: 50, cd: [1.6, 2.6] }] },
    toyBerserk: { name: '狂暴型玩具士兵', tier: 'brute', arch: 'aggressive', size: [14, 12, 92], scale: 1.12, weight: 2, art: ['snToy', { hue: -40, sat: 1.4, bright: 0.85 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 76, dmg: 1.0, cd: [1.8, 2.8], w: 2 }, { use: 'buff', kind: 'enrage', target: 'self', dur: 8, cd: [14, 18], say: '狂暴！' }] },
    // 班图族
    bantuWarrior: { name: '班图战士', tier: 'normal', arch: 'aggressive', size: [14, 12, 108], art: 'snBantu',
      skills: [{ use: 'swipe', n: 2, reach: 84, dmg: 1.0, cd: [1.6, 2.6], w: 2 }, { use: 'dash', len: 300, speed: 640, windup: 0.8, dmg: 1.1, cd: [5, 7] }, { use: 'grab', reach: 62, hold: 0.7, throwDmg: 1.3, cd: [8, 10], w: 0.6 }] },
    bantuElite: { name: '班图精锐卫士', tier: 'elite', arch: 'guard', size: [15, 12, 112], scale: 1.08, art: ['snBantu', { hue: -30, sat: 1.2, bright: 0.9 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 88, dmg: 1.0, cd: [1.8, 2.8], w: 2 }, { use: 'guard', dur: 2.2, reduce: 0.85, cd: [8, 11], counter: { use: 'aoe', shape: 'circle', at: 'self', r: 120, windup: 0.45, dmg: 1.2 } }] },
    kuniShaman: { name: '库尼族图腾术士', tier: 'caster', arch: 'kiter', size: [14, 12, 104], elem: 'ice', art: ['snBantu', { hue: 150, sat: 0.9, bright: 1.05 }],
      skills: [{ use: 'swipe', dmg: 0.8, reach: 60, cd: [2, 3] }, { use: 'shot', mode: 'homing', n: 2, spread: 50, speed: 230, dmg: 0.8, status: 'slow', cd: [4, 5.5], w: 1.5 },
        { use: 'buff', kind: 'shield', target: 'allies', amt: 0.15, dur: 8, cd: [16, 22], w: 0.6 }] },
    avalancheRabina: { name: '雪崩拉比纳', tier: 'elite', arch: 'aggressive', size: [15, 12, 112], scale: 1.1, art: ['snBantu', { hue: 60, sat: 0.6, bright: 1.15 }],
      skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.62, dmg: 1.3, down: true, sa: true, cd: [2.4, 3.6], w: 2 }, { use: 'rain', kind: 'hex', n: 4, r: 46, windup: 1.2, dmg: 1.0, col: '#e8f4ff', cd: [8, 11], say: '雪崩！' }] },
    bullBastur: { name: '野蛮牛族勇士巴斯图鲁', tier: 'elite', arch: 'aggressive', size: [18, 14, 120], weight: 3, art: ['tauArmored', { hue: -160, sat: 0.7, bright: 1.05 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'axe', reach: 96, width: 30, windup: 0.6, dmg: 1.3, down: true, cd: [2.2, 3.4], w: 2 }, { use: 'dash', clip: 'charge', len: 380, speed: 680, windup: 0.8, dmg: 1.3, cd: [5, 7] }] },
    bullEmuli: { name: '野蛮牛族勇士艾穆利', tier: 'elite', arch: 'guard', size: [18, 14, 120], weight: 3, art: ['tauArmored', { hue: 30, sat: 0.8 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'axe', reach: 96, width: 30, windup: 0.6, dmg: 1.3, down: true, cd: [2.2, 3.4], w: 2 }, { use: 'aoe', shape: 'circle', at: 'self', r: 140, windup: 1.1, dmg: 1.2, jump: true, cd: [8, 10], say: '践踏！' }] },
    tulusWarrior: { name: '图卢斯族战士', tier: 'brute', arch: 'aggressive', size: [16, 13, 112], weight: 2.5, art: ['tau', { hue: -150, sat: 0.6, bright: 1.1 }],
      skills: [{ use: 'swipe', n: 2, reach: 84, dmg: 1.1, cd: [1.8, 2.8], w: 2 }, { use: 'dash', clip: 'charge', len: 320, speed: 640, windup: 0.8, dmg: 1.2, cd: [5, 7] }] },
    tulusElite: { name: '图卢斯族精英战士', tier: 'elite', arch: 'guard', size: [18, 14, 120], weight: 3, art: ['tauArmored', { hue: -120, sat: 0.9, bright: 1.1 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'axe', reach: 96, width: 30, windup: 0.6, dmg: 1.3, down: true, cd: [2.2, 3.4], w: 2 }, { use: 'guard', dur: 2.2, reduce: 0.85, cd: [8, 11] }, { use: 'aoe', shape: 'cross', at: 'target', hw: 22, windup: 1.2, dmg: 1.2, cd: [8, 11] }] },
    // 野兽与雪山的魔物
    iceTiger: { name: '寒冰虎', tier: 'normal', arch: 'aggressive', size: [18, 13, 72], weight: 1.2, speed: 130, elem: 'ice', art: 'snTiger', noGrab: false,
      skills: [{ use: 'swipe', clip: 'bite', reach: 66, dmg: 1.0, cd: [1.4, 2.4], w: 2 }, { use: 'dash', clip: 'pounce', len: 320, speed: 700, windup: 0.7, dmg: 1.1, status: 'slow', cd: [4, 6] }] },
    snowApe: { name: '雪魈', tier: 'brute', arch: 'aggressive', size: [18, 14, 110], weight: 2.5, art: 'snYeti',
      skills: [{ use: 'swipe', clip: 'slam', reach: 84, width: 28, windup: 0.6, dmg: 1.2, down: true, cd: [2, 3], w: 2 }, { use: 'grab', reach: 66, hold: 0.8, throwDmg: 1.5, cd: [7, 9] }] },
    snowballRului: { name: '雪球噜噜伊', tier: 'caster', arch: 'kiter', size: [14, 12, 76], scale: 0.72, art: ['snYeti', { hue: 30, sat: 0.4, bright: 1.15 }],
      skills: [{ use: 'swipe', dmg: 0.8, reach: 56, cd: [2, 3] }, { use: 'shot', clip: 'throw', mode: 'arc', r: 50, dmg: 0.9, status: 'slow', cd: [3.2, 4.5], w: 2 }, { use: 'shot', clip: 'throw', mode: 'straight', speed: 340, dmg: 0.8, cd: [4, 6] }] },
    iceSprite: { name: '冰精灵史苏克', tier: 'flier', arch: 'flier', size: [14, 12, 80], elem: 'ice', art: ['deGhost', { hue: -40, sat: 1.3, bright: 1.2 }], traits: { immune: ['freeze'] },
      skills: [{ use: 'shot', mode: 'spread', n: 3, spread: 50, speed: 260, dmg: 0.75, status: 'slow', cd: [4, 5.5], w: 1.4 }, { use: 'aoe', shape: 'circle', at: 'target', r: 62, windup: 1.1, dmg: 0.95, status: 'freeze', sdur: 1.2, cd: [7, 9] }] },
    iceLurker: { name: '寒冰潜伏者', tier: 'flier', arch: 'flier', size: [14, 12, 84], elem: 'ice', art: ['deGhost', { hue: -70, sat: 0.9, bright: 0.7 }],
      skills: [{ use: 'seq', cd: [5, 7], w: 1.5, steps: [{ use: 'blink', to: 'behind', dist: 60 }, { use: 'swipe', n: 2, dmg: 0.9, windup: 0.3 }] }, { use: 'shot', mode: 'homing', speed: 220, dmg: 0.8, cd: [4, 5.5] }] },
    foamSpider: { name: '泡沫蜘蛛', tier: 'normal', arch: 'aggressive', size: [18, 13, 60], art: ['deSpider', { hue: 150, sat: 0.6, bright: 1.2 }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 62, dmg: 0.95, cd: [1.4, 2.4], w: 2 }, { use: 'shot', mode: 'spread', n: 3, spread: 50, speed: 250, dmg: 0.6, status: 'slow', cd: [5, 7], col: '#e8f4ff' }] },
    iceSpider: { name: '寒冰蜘蛛', tier: 'normal', arch: 'aggressive', size: [18, 13, 60], elem: 'ice', art: ['deSpider', { hue: -80, sat: 1.1, bright: 1.15, only: [230, 330] }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 62, dmg: 0.95, status: 'slow', cd: [1.4, 2.4], w: 2 }, { use: 'dash', clip: 'pounce', len: 260, speed: 640, windup: 0.7, dmg: 1.0, cd: [5, 7] }] },
    frostGoblin: { name: '冰霜哥布林', tier: 'swarm', arch: 'swarm', size: [11, 10, 72], elem: 'ice', art: ['goblin', { hue: 150, sat: 0.6, bright: 1.15, only: [45, 160] }],
      skills: [{ use: 'swipe', dmg: 0.8, reach: 56, cd: [1.4, 2.4], w: 2 }, { use: 'shot', clip: 'throw', mode: 'arc', r: 44, dmg: 0.7, status: 'slow', cd: [4, 6] }] },
    blueGoblin: { name: '青哥布林', tier: 'swarm', arch: 'swarm', size: [11, 10, 72], art: ['goblin', { hue: 115, only: [45, 160] }],
      skills: [{ use: 'swipe', n: 2, dmg: 0.8, reach: 56, cd: [1.4, 2.4], w: 2 }] },
    catapultCommander: { name: '哥布林投石车指挥官', tier: 'elite', arch: 'kiter', size: [13, 11, 80], scale: 1.15, art: ['goblinCaptain', { hue: 150, sat: 0.7, bright: 1.1 }],
      skills: [{ use: 'rain', kind: 'hex', n: 4, r: 50, windup: 1.2, dmg: 1.0, col: '#c8d0dc', cd: [6, 8], w: 2, say: '投石车，放！' }, { use: 'summon', kind: 'frostGoblin', n: 2, max: 4, cd: [12, 16] }] },
    stormGolem: { name: '暴风石巨人', tier: 'brute', arch: 'guard', size: [20, 15, 120], weight: 4, hardness: 40, art: ['golem', { hue: 120, sat: 0.7, bright: 1.1 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.7, dmg: 1.3, down: true, sa: true, cd: [2.4, 3.6], w: 2 }, { use: 'aoe', shape: 'ring', at: 'self', r: 150, r0: 50, windup: 1.2, dmg: 1.1, knock: 260, cd: [8, 10], say: '暴风！' }] },
    thunderGolem: { name: '闪电石巨人', tier: 'brute', arch: 'guard', size: [20, 15, 120], weight: 4, hardness: 40, elem: 'light', art: ['golem', { hue: -70, sat: 1.25, bright: 1.1 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.7, dmg: 1.3, down: true, sa: true, cd: [2.4, 3.6], w: 2 }, { use: 'rain', kind: 'bolt', n: 3, r: 44, windup: 1.0, dmg: 1.0, col: '#ffe070', cd: [7, 9] }] },
    frostGolem: { name: '冰霜石巨人', tier: 'brute', arch: 'guard', size: [20, 15, 120], weight: 4, hardness: 40, elem: 'ice', art: ['golem', { hue: -160, sat: 0.9, bright: 1.2 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.7, dmg: 1.3, down: true, sa: true, status: 'slow', cd: [2.4, 3.6], w: 2 }, { use: 'aoe', shape: 'cross', at: 'target', hw: 22, windup: 1.2, dmg: 1.1, status: 'freeze', sdur: 1, cd: [8, 10] }] },
    skasaEgg: { name: '冰龙之卵', tier: 'swarm', size: [18, 12, 64], obj: { shape: 'egg', col: '#cfeeff', h: 64 } },   // plant 的物件（程序画，不用出图）
    babySkasa: { name: '斯卡萨幼龙', tier: 'flier', arch: 'flier', size: [16, 13, 80], elem: 'ice', art: ['wyvern', { hue: 40, sat: 0.8, bright: 1.15 }],
      skills: [{ use: 'shot', mode: 'straight', speed: 320, dmg: 0.85, status: 'slow', cd: [3.2, 4.5], w: 2, col: '#bfe6ff' }, { use: 'dash', len: 280, speed: 660, windup: 0.7, dmg: 1.0, cd: [5, 7] }] },
    aquiles: { name: '冰影阿奎利斯', tier: 'elite', arch: 'flier', size: [18, 14, 96], scale: 1.3, elem: 'ice', art: ['wyvern', { hue: 60, sat: 1.0, bright: 0.95 }], traits: { immune: ['freeze'] },
      skills: [{ use: 'laser', windup: 1.1, dur: 1.0, sweep: 60, dmg: 0.45, col: '#bfe6ff', cd: [6, 8], w: 1.4, say: '冰之吐息' }, { use: 'rain', kind: 'hex', n: 4, r: 46, windup: 1.1, dmg: 1.0, col: '#bfe6ff', cd: [8, 11] }] },
    kruse: { name: '雷剑克鲁斯', tier: 'elite', arch: 'aggressive', size: [14, 12, 110], speed: 125, elem: 'light', art: ['snBantu', { hue: 90, sat: 0.4, bright: 1.2 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 90, dmg: 0.95, cd: [1.6, 2.4], w: 2 }, { use: 'dash', len: 400, speed: 760, windup: 0.7, dmg: 1.2, cd: [4, 6] }, { use: 'rain', kind: 'bolt', n: 4, r: 44, windup: 1.0, dmg: 1.0, col: '#ffe070', cd: [8, 10] }] },
    frostGiantLik: { name: '寒冰巨人', tier: 'elite', arch: 'guard', size: [22, 16, 150], scale: 0.9, weight: 5, elem: 'ice', art: ['deGiant', { hue: -170, sat: 0.7, bright: 1.15 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', reach: 110, width: 32, windup: 0.7, dmg: 1.3, down: true, sa: true, cd: [2.4, 3.6], w: 2 }, { use: 'grab', reach: 76, hold: 0.9, throwDmg: 1.5, cd: [8, 10] }] },
    // 领主机制用的物件 / 小怪（程序画或借已有精灵染色，不用出图）
    toyHard: { name: '坚硬的玩具士兵', tier: 'normal', arch: 'aggressive', size: [12, 11, 84], speed: 95, art: ['snToy', { hue: 180, sat: 0.35, bright: 0.75 }], traits: { hitHp: 6 },   // 官方：坚硬玩具只受 1 点伤害（固定 6 下打碎）
      skills: [{ use: 'swipe', n: 2, dmg: 1.0, cd: [1.6, 2.6], w: 2 }] },
    charlieHeart: { name: '查理的心脏', tier: 'swarm', size: [18, 12, 70], obj: { shape: 'heart', col: '#8ad8ff', h: 70, botSkip: true } },
    kuniTotemRed: { name: '库尼红图腾', tier: 'swarm', size: [16, 12, 110], obj: { shape: 'totem', col: '#ff6a5a', h: 110 } },
    kuniTotemBlue: { name: '库尼蓝图腾', tier: 'swarm', size: [16, 12, 110], obj: { shape: 'totem', col: '#6ab0ff', h: 110 } },
    iceBlock: { name: '冰块', tier: 'swarm', size: [20, 12, 70], obj: { shape: 'block', col: '#bfe6ff', h: 70 } },
    // 班图四勇士（布万加的修炼场车轮战）：班图战士的四种染色，各带一个招牌
    bantuMalaga: { name: '勇士马拉加', tier: 'elite', arch: 'aggressive', size: [15, 12, 112], scale: 1.08, elem: 'ice', art: ['snBantu', { hue: -110, sat: 0.7, bright: 1.15 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 2, reach: 90, windup: 0.6, dmg: 1.0, cd: [1.8, 2.8], w: 2 },
        { use: 'plant', kind: 'iceBlock', n: 2, at: 'target', spread: 130, fuse: 5, hits: 4, onFuse: 'explode', r: 90, dmg: 1.1, max: 4, label: '冰块', col: '#bfe6ff', cd: [9, 12], w: 1.4, say: '冰块——在碎裂前打掉它！' },
        { use: 'rain', kind: 'hex', n: 4, r: 48, windup: 1.2, dmg: 1.0, col: '#bfe6ff', cd: [8, 11], say: '冰块砸下来了！' }] },
    bantuLerit: { name: '勇士莱里特拉里', tier: 'elite', arch: 'aggressive', size: [15, 12, 112], scale: 1.08, speed: 130, art: ['snBantu', { hue: 90, sat: 0.6, bright: 1.1 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 88, windup: 0.55, dmg: 0.9, cd: [1.6, 2.6], w: 2 },
        { use: 'pull', mode: 'in', r: 360, force: 250, windup: 1.0, dur: 1.4, dmg: 0.5, col: '#e8f4ff', cd: [10, 13], w: 1.3, say: '旋风——往外跑！' },
        { use: 'dash', spin: true, len: 380, speed: 520, windup: 1.0, dmg: 1.0, col: '#e8f4ff', cd: [7, 9], w: 1.2, say: '旋风斩！' }] },
    bantuMedusa: { name: '勇士美杜莎莎', tier: 'elite', arch: 'kiter', size: [15, 12, 112], scale: 1.05, art: ['snBantu', { hue: 150, sat: 0.4, bright: 0.95 }],
      skills: [{ use: 'swipe', n: 2, reach: 86, windup: 0.6, dmg: 0.95, cd: [1.8, 2.8], w: 2 }, { use: 'shot', mode: 'homing', n: 2, spread: 50, speed: 240, dmg: 0.8, status: 'slow', col: '#9ab0a0', cd: [4, 5.5], w: 1.4 },
        { use: 'mech', mech: { use: 'facing', mode: 'away', windup: 1.6, frac: 0.08, status: 'stun', sdur: 1.6, col: '#9ab0a0', say: '美杜莎莎的石化凝视——背对她！' }, cd: [11, 14], gap: 4, w: 1.2 }] },
    bantuHokey: { name: '勇士霍克伊', tier: 'elite', arch: 'kiter', size: [15, 12, 112], scale: 1.05, art: ['snBantu', { hue: 30, sat: 1.1, bright: 0.85 }],
      skills: [{ use: 'swipe', n: 2, reach: 86, windup: 0.6, dmg: 0.95, cd: [1.8, 2.8], w: 2 }, { use: 'shot', mode: 'straight', speed: 380, dmg: 0.9, cd: [3.5, 5], w: 1.4, say: '飞斧！' },
        { use: 'summon', kind: 'hokeyHawk', n: 2, max: 3, cd: [9, 12], w: 1.2, say: '猎鹰，去！' }] },
    hokeyHawk: { name: '霍克伊的猎鹰', tier: 'swarm', arch: 'flier', size: [14, 11, 70], scale: 0.7, speed: 150, art: ['wyvern', { hue: -70, sat: 0.5, bright: 0.85 }],
      skills: [{ use: 'dash', clip: 'pounce', len: 300, speed: 700, windup: 0.7, dmg: 0.8, cd: [3.5, 5], w: 2 }, { use: 'swipe', clip: 'bite', reach: 56, dmg: 0.7, cd: [1.6, 2.4] }] },
    // 冰雪宫殿的五宫女（官方 HK61：混乱 / 召唤 / 回复加速 / 踢 / 击飞）：洛丝的小号染色；回复宫女会给女王回血，要先打
    maidHeal: { name: '回复宫女', tier: 'caster', arch: 'kiter', size: [12, 11, 100], scale: 0.8, elem: 'ice', art: ['snRose', { hue: 100, sat: 0.6, bright: 1.1 }],
      skills: [{ use: 'buff', kind: 'heal', target: 'allies', r: 900, amt: 0.03, cd: [6, 8], w: 2, say: '女王陛下，请保重！' }, { use: 'buff', kind: 'haste', target: 'allies', r: 600, dur: 6, amt: 0.3, cd: [12, 15], w: 1 },
        { use: 'shot', mode: 'straight', speed: 300, dmg: 0.7, col: '#9affc0', cd: [4, 6] }] },
    maidKick: { name: '踢腿宫女', tier: 'normal', arch: 'aggressive', size: [12, 11, 100], scale: 0.8, speed: 130, elem: 'ice', art: ['snRose', { hue: -60, sat: 0.8, bright: 1.05 }],
      skills: [{ use: 'swipe', n: 2, reach: 70, windup: 0.5, dmg: 0.9, knock: 320, cd: [1.8, 2.8], w: 2, say: '' }] },
    maidLaunch: { name: '击飞宫女', tier: 'normal', arch: 'aggressive', size: [12, 11, 100], scale: 0.8, speed: 120, elem: 'ice', art: ['snRose', { hue: 40, sat: 0.9, bright: 1.0 }],
      skills: [{ use: 'swipe', reach: 72, windup: 0.6, dmg: 1.0, launch: 380, cd: [2.4, 3.4], w: 2 }] },
    maidConfuse: { name: '混乱宫女', tier: 'caster', arch: 'kiter', size: [12, 11, 100], scale: 0.8, elem: 'ice', art: ['snRose', { hue: 160, sat: 0.9, bright: 0.95 }],
      skills: [{ use: 'shot', mode: 'homing', speed: 220, dmg: 0.6, status: 'confuse', sdur: 2, col: '#ff8ae0', cd: [5, 7], w: 2, say: '混乱吧……' }] },
    maidCaller: { name: '召唤宫女', tier: 'caster', arch: 'kiter', size: [12, 11, 100], scale: 0.8, elem: 'ice', art: ['snRose', { hue: -120, sat: 0.7, bright: 1.0 }],
      skills: [{ use: 'summon', kind: 'iceSprite', n: 2, max: 3, cd: [10, 13], w: 2, say: '冰精灵们，来吧！' }, { use: 'shot', mode: 'straight', speed: 300, dmg: 0.7, col: '#bfe6ff', cd: [4, 6] }] },
  },

  bosses: {
    // 查理（官方 HK57）：火箭拳、霸体冲撞、空中降冰块、坚硬玩具（固定 6 下打碎）；房间：保护查理的心脏（玩具摸到 → 查理回血）；心脏的冰晶护盾
    charlie: { name: '查理', lvl: 37, power: 1.55, size: [20, 15, 140], weight: 5, speed: 75, elem: 'ice', art: 'snCharlie', scale: 1.15, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 90, dur: 6 }],
      phases: [
        { at: 1, skills: [
          { use: 'swipe', clip: 'slam', reach: 116, width: 32, windup: 0.95, dmg: 1.3, down: true, sa: true, cd: [2.2, 3.2], w: 2 },
          { use: 'aoe', id: 'rocket', clip: 'sigA', shape: 'line', at: 'front', len: 620, hw: 30, windup: 1.0, dmg: 1.4, knock: 280, col: '#bfe6ff', cd: [7, 9], w: 1.4, say: '火箭拳——往上下躲开这一条！' },
          { use: 'dash', clip: 'charge', len: 420, speed: 700, windup: 1.0, dmg: 1.3, col: '#bfe6ff', cd: [8, 10], say: '霸体冲撞！' },
          { use: 'rain', kind: 'hex', n: 5, r: 50, windup: 1.2, dmg: 1.0, col: '#bfe6ff', cd: [9, 12], say: '冰块从天而降！' },
          { use: 'summon', id: 'hardToys', clip: 'sigB', kind: 'toyHard', n: 2, max: 3, cd: [14, 18], w: 0.9, say: '坚硬的玩具——只能一下一下地敲碎！' }] },
        { at: 0.7, enter: { col: '#8ad8ff', mechs: [SN_CHARLIE_HEART] } },
        { at: 0.35, enter: { say: '查理的心脏在发光——打碎守护它的冰晶！', col: '#bfe6ff', mechs: [SN_CHARLIE_SHIELD] }, skills: [{ use: 'mech', mech: SN_CHARLIE_SHIELD, cd: [26, 32], w: 0.7 }] },
      ] },
    lik: { name: '寒冰巨人利库', lvl: 38, size: [22, 16, 150], weight: 6, speed: 70, elem: 'ice', art: 'snLik', scale: 1.3, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 110, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', clip: 'slam', reach: 124, width: 34, windup: 0.7, dmg: 1.4, down: true, sa: true, cd: [2, 3], w: 2 }, { use: 'grab', reach: 84, hold: 0.9, throwDmg: 1.6, cd: [8, 10] },
          { use: 'aoe', shape: 'cross', at: 'target', hw: 26, windup: 1.2, dmg: 1.3, status: 'freeze', sdur: 1, cd: [7, 9], say: '冰裂！' }] },
        { at: 0.5, enter: { say: '利库召来了暴风雪！', col: '#e8f4ff', mechs: [{ use: 'hazard', kind: 'debris', every: 4, n: 3, col: '#bfe6ff' }] },
          skills: [{ use: 'summon', kind: 'frostGolem', n: 1, max: 2, cd: [18, 24] }, { use: 'rain', kind: 'hex', n: 5, r: 48, windup: 1.2, dmg: 1.1, col: '#bfe6ff', cd: [8, 10] }] },
      ] },
    // 野兽师鲁乌格 + 冰齿沙凡特（官方 HK58，双领主）：上勾拳、召寒冰虎、加攻速；沙凡特出血飞跃、爪击突进；两个被远程打到都会霸体（逼近战）
    ruug: { name: '野兽师鲁乌格', lvl: 39, power: 1.3, variantOf: 'avalancheRabina', size: [15, 12, 116], speed: 110, art: ['snBantu', { hue: -60, sat: 1.1, bright: 0.85 }], scale: 1.3, pref: 140, traits: { saVsRanged: 1.2 },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }, { use: 'duo', with: ['sabertooth'], hp: 0.55, onPartnerDown: 'enrage', atk: 1.3, speed: 1.2, col: '#bfe6ff', say: '野兽师鲁乌格和冰齿沙凡特一起上了——被远程打到它们会霸体，贴上去打！' }],
      phases: [
        { at: 1, skills: [
          { use: 'swipe', id: 'uppercut', clip: 'sigA', reach: 92, windup: 0.95, dmg: 1.2, launch: 340, cd: [4, 6], w: 1.4, say: '上勾拳！' },
          { use: 'swipe', n: 2, reach: 90, windup: 0.95, dmg: 1.0, cd: [1.8, 2.8], w: 2 },
          { use: 'shot', clip: 'sigB', mode: 'spread', n: 3, spread: 50, speed: 300, dmg: 0.85, cd: [5, 7], say: '飞斧！' },
          { use: 'summon', kind: 'iceTiger', n: 2, max: 3, cd: [14, 18], w: 0.8, say: '去吧，孩子们！' },
          { use: 'buff', kind: 'haste', target: 'allies', dur: 8, cd: [15, 19], w: 0.6, say: '狂野的号令——加速！' }] },
        { at: 0.5, enter: { col: '#bfe6ff', mechs: [{ use: 'enrage', t: 1, atk: 1.25, speed: 1.2, say: '吹响了兽笛——野兽们狂暴了！' }] } },
      ] },
    sabertooth: { name: '冰齿沙凡特', lvl: 39, power: 1.2, size: [22, 15, 90], scale: 1.45, weight: 3, speed: 140, elem: 'ice', art: ['snTiger', { hue: 20, sat: 0.8, bright: 0.9 }], pref: 80, noGrab: true, traits: { saVsRanged: 1.2 },
      mechs: [{ use: 'groggy', max: 70, dur: 5 }],
      phases: [{ at: 1, skills: [
        { use: 'swipe', clip: 'bite', reach: 94, width: 28, windup: 0.95, dmg: 1.2, cd: [1.8, 2.6], w: 2 },
        { use: 'leap', id: 'bleedLeap', crouch: 0.25, up: 0.3, track: 0.55, fall: 0.5, r: 100, hover: 360, dmg: 1.3, status: 'bleed', sdur: 3, col: '#e04a4a', cd: [9, 12], w: 1.3, say: '出血飞跃——锁定后跑出圈！' },
        { use: 'dash', clip: 'pounce', len: 420, speed: 760, windup: 1.0, dmg: 1.2, col: '#bfe6ff', cd: [6, 8], say: '爪击突进！' }] }] },
    // 塞斯奇（官方 HK60）：近身抓到头顶狂扁、双掌震地的雪波（沿纵深推进，留一排）、召小雪魈、血量很多；房间：库尼图腾（红 = 狂暴 / 蓝 = 回血，打碎就没事）
    seski: { name: '塞斯奇', lvl: 40, power: 1.7, variantOf: 'frostApe', size: [22, 16, 140], weight: 6, speed: 60, art: ['snYeti', { hue: -20, sat: 0.8, bright: 0.85 }], scale: 1.55, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 120, dur: 6 }],
      phases: [
        { at: 1, skills: [
          { use: 'grab', id: 'pummel', clip: 'sigA', reach: 96, windup: 0.95, hold: 1.4, dmg: 0.8, throwDmg: 1.7, cd: [6, 8], w: 1.6, say: '抓住了——举过头顶狂扁！' },
          { use: 'swipe', clip: 'slam', reach: 124, width: 34, windup: 0.95, dmg: 1.3, down: true, cd: [2.2, 3.2], w: 2 },
          { use: 'lanes', id: 'snowwave', clip: 'sigB', kind: 'wave', lanes: 5, hit: 4, from: 'boss', windup: 1.1, speed: 900, dmg: 1.3, col: '#e8f4ff', cd: [9, 12], w: 1.4, say: '双掌震地——雪波！站进没亮的那一排！', then: { use: 'hold', dur: 2.0, clip: 'roar', col: '#e8f4ff' } },
          { use: 'plant', id: 'totemRed', kind: 'kuniTotemRed', n: 1, at: 'spots', fuse: 10, hits: 5, onFuse: 'buff', max: 1, label: '红图腾', col: '#ff6a5a', cd: [18, 22], w: 0.8, say: '库尼红图腾——不打碎它，塞斯奇会狂暴！' },
          { use: 'summon', kind: 'snowApe', n: 2, max: 3, cd: [15, 19], w: 0.7, say: '小雪魈们，上！' }] },
        { at: 0.5, enter: { say: '塞斯奇捶胸咆哮！', col: '#e8f4ff', mechs: [SN_SESKI_POUND] },
          skills: [{ use: 'mech', mech: SN_SESKI_POUND, cd: [24, 30], w: 0.7 },
            { use: 'plant', id: 'totemBlue', kind: 'kuniTotemBlue', n: 2, at: 'spots', fuse: 9, hits: 5, onFuse: 'heal', heal: 0.05, max: 2, label: '蓝图腾', col: '#6ab0ff', cd: [20, 24], w: 0.8, say: '库尼蓝图腾——不打碎它，塞斯奇会回血！' }] },
      ] },
    // 班图族长 布万加（官方 HK63 · 四剑圣之一）：先让四勇士车轮战；本人挥图腾眩晕击退、起跳砸地（落地时跳起来躲）、消失后从背后击飞、长霸体；战吼（贴近他）
    bwanga: { name: '布万加', lvl: 41, power: 1.6, size: [18, 14, 132], weight: 5, speed: 100, art: 'snBwanga', scale: 1.15, pref: 100, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 120, dur: 6 }, SN_BWANGA_TRIAL],
      phases: [
        { at: 1, skills: [
          { use: 'swipe', clip: 'club', n: 2, reach: 108, width: 30, windup: 0.95, dmg: 1.2, status: 'stun', sdur: 0.7, knock: 260, cd: [2, 3], w: 2 },
          { use: 'leap', id: 'slam', clip: 'sigA', crouch: 0.2, up: 0.3, track: 0.6, fall: 0.5, r: 170, hover: 600, jump: true, dmg: 1.8, col: '#ffd070', cd: [11, 14], w: 1.4, say: '起跳砸地——落地的瞬间跳起来！' },
          { use: 'seq', id: 'backstab', clip: 'sigB', cd: [9, 12], w: 1.3, say: '布万加消失了——小心背后！', steps: [{ use: 'blink', to: 'behind', dist: 70, col: '#ffd070' }, { use: 'swipe', clip: 'slam', reach: 100, windup: 0.6, dmg: 1.3, launch: 380 }] },
          { use: 'dash', clip: 'charge', len: 420, speed: 740, windup: 1.0, dmg: 1.3, col: '#ffd070', cd: [6, 8] },
          { use: 'guard', dur: 2.4, reduce: 0.85, cd: [11, 14], counter: { use: 'aoe', shape: 'circle', at: 'self', r: 150, windup: 0.9, dmg: 1.4, col: '#ffd070' } }] },
        { at: 0.5, enter: { say: '布万加：“拿出你的勇气，证明你是真正的勇士！”', col: '#ffd070', mechs: [SN_BWANGA_ROAR] }, skills: [{ use: 'mech', mech: SN_BWANGA_ROAR, cd: [24, 30], w: 0.7 }] },
      ] },
    // 冰雪女王洛丝（官方 HK61）：和冰晶王座融为一体、不能移动，坐在王座上指挥（rooted）；雷剑克鲁斯把她当成恋人守护她（连线）；
    // 五宫女（回复宫女会给女王回血，先打它）；洛丝的壁钟（钟响时躲到王座后，钩子 roseClock）；最后走下王座（form）
    // 美术：王座上的形态写在 art.chars.snRose.forms.throne（美术队列出图后领主平时用 snRose_throne，走下王座的 form 换回 snRose）
    rose: { name: '冰雪女王洛丝', lvl: 42, power: 1.7, size: [15, 12, 124], speed: 95, elem: 'ice', art: 'snRose', scale: 1.15, pref: 220, hook: 'roseClock', traits: { rooted: true, sa: 'cast' },
      mechs: [{ use: 'groggy', max: 110, dur: 6 }, { use: 'tether', kind: 'kruse', mode: 'guard', mul: 0.35, hp: 0.22, onBreak: 'groggy', say: '雷剑克鲁斯把洛丝当成了恋人——先打倒克鲁斯！', col: '#ffe070' }],
      phases: [
        { at: 1, skills: [
          { use: 'shot', mode: 'homing', n: 3, spread: 60, speed: 250, turn: 2.0, dmg: 0.9, status: 'slow', cd: [4, 5.5], w: 1.6, say: '冰晶', col: '#bfe6ff' },
          { use: 'aoe', shape: 'circle', at: 'target', r: 70, n: 3, scatter: 140, windup: 1.2, dmg: 1.1, status: 'freeze', sdur: 1.2, cd: [7, 9], col: '#bfe6ff' },
          { use: 'laser', windup: 1.2, dur: 1.2, sweep: 70, dmg: 0.5, col: '#bfe6ff', cd: [8, 10] },
          { use: 'aoe', shape: 'circle', at: 'self', r: 150, windup: 1.0, dmg: 1.2, status: 'freeze', sdur: 1, col: '#bfe6ff', cd: [6, 8], say: '别靠近王座！' },
          { use: 'summon', id: 'maidHeal', clip: 'sigA', kind: 'maidHeal', n: 1, max: 1, cd: [16, 20], w: 1.2, say: '回复宫女，照顾好我——先打倒她！' },
          { use: 'summon', kind: 'maidKick', n: 2, max: 2, cd: [14, 18], w: 0.8, say: '宫女们，保护女王！' }] },
        { at: 0.55, enter: { say: '洛丝唤来了更多的宫女！', col: '#d8f0ff' },
          skills: [{ use: 'summon', kind: 'maidLaunch', n: 1, max: 1, cd: [16, 20], w: 0.8 }, { use: 'summon', kind: 'maidConfuse', n: 1, max: 1, cd: [18, 22], w: 0.8 },
            { use: 'summon', kind: 'maidCaller', n: 1, max: 1, cd: [20, 24], w: 0.7 },
            { use: 'cone', id: 'blizzard', clip: 'sigB', ang: 70, len: 360, windup: 1.0, dur: 1.0, tick: 0.25, dmg: 0.35, status: 'freeze', sdur: 0.8, col: '#bfe6ff', cd: [9, 12], w: 1.3, say: '冰雪吐息——绕到侧面！' }] },
        { at: 0.25, enter: { col: '#d8f0ff', mechs: [SN_ROSE_RISE] } },
      ] },
    // S1 机制样板（docs/BOSS_PLAN.md §4.3，docs/BOSS_SPEC.md）：前爪拍地（跳起躲）、极寒龙息（扇形，绕侧面）、吹气（推开 + 眩晕）、龙蛋（孵化前打碎）、
    // 蓄力龙息（打够伤害打断 → 破招，打不断放大范围龙息）、起飞（空中冰雨，落地砸一下）
    skasa: { name: '冰龙斯卡萨', tier: 'raid', lvl: 43, power: 1.35, size: [30, 18, 140], weight: 8, speed: 70, elem: 'ice', art: 'snSkasa', scale: 1.5, pref: 150, traits: { sa: 'cast', immune: ['freeze'] },
      mechs: [{ use: 'groggy', max: 130, dur: 7, mul: 1.6 }, { use: 'enrage', t: 300 }],
      phases: [
        { at: 1, skills: [
          { use: 'aoe', id: 'claw', clip: 'sigA', shape: 'circle', at: 'front', r: 150, windup: 1.0, dmg: 1.4, jump: true, down: true, follow: false, cd: [5, 7], w: 1.6, say: '前爪拍地——跳起来！', col: '#bfe6ff' },
          { use: 'swipe', clip: 'bite', reach: 140, width: 36, dmg: 1.2, down: true, cd: [2.5, 3.5], w: 1.2 },
          { use: 'cone', id: 'breath', clip: 'sigB', ang: 56, len: 380, windup: 1.0, dur: 1.4, tick: 0.2, dmg: 0.32, status: 'freeze', sdur: 0.8, cd: [8, 10], w: 1.4, say: '极寒龙息——绕到侧面！', col: '#bfe6ff' },
          { use: 'pull', id: 'blow', mode: 'out', r: 340, force: 320, windup: 0.9, dur: 1.1, status: 'stun', sdur: 0.9, dmg: 0.4, cd: [13, 16], say: '吹气！', col: '#e8f4ff' },
          { use: 'plant', id: 'eggs', kind: 'skasaEgg', n: 3, at: 'spots', fuse: 12, hp: 0.012, onFuse: 'hatch:babySkasa', max: 3, cd: [22, 26], w: 0.8, label: '孵化', say: '斯卡萨产下了龙蛋——在孵化前打碎！', col: '#bfe6ff' }] },
        { at: 0.7, enter: { col: '#bfe6ff', mechs: [SKASA_CHARGE] },
          skills: [{ use: 'mech', mech: SKASA_CHARGE, cd: [26, 32], gap: 18, w: 0.8 }] },
        { at: 0.45, enter: { col: '#e8f4ff', mechs: [SKASA_FLY] },
          skills: [{ use: 'mech', mech: SKASA_FLY, cd: [42, 50], gap: 30, w: 0.6 }] },
        { at: 0.2, enter: { say: '斯卡萨之巢在崩塌！', mechs: [{ use: 'hazard', kind: 'shrink', minW: 640, speed: 20, col: '#bfe6ff' }] } },
      ] },
  },

  items: {
    epics: [
      { key: 'ep_sn_charlie', slot: 'neck', lvl: 37, name: '查理的石晶项链', fx: { ice: 25, dmgUp: 0.09, hpPct: 0.04 }, desc: '巴尔雷娜小时候送给哥哥查理的项链，碎成了好几块，又被一块一块拼了回来。',
        look: 'a simple leather cord necklace with a pale blue stone crystal pendant that was broken and pieced back together with thin silver wire' },
    ],
    sets: [
      // 深渊专属（万年雪山深渊）：本作原创，辅助装备 + 魔法石两件套
      { id: 'set_skasa', name: '冰龙斯卡萨的遗骸', lvl: 42, abyss: true, desc: '三十年苏醒一次的冰龙，每次沉睡前都会蜕下一片鳞。',
        bonus: { 2: { st: { dmgUp: 0.1, ice: 30, hpPct: 0.06 }, desc: '【冰龙】伤害增加 10%，冰属性强化 +30，HP 上限 +6%；攻击时 6% 几率降下冰龙的冰锥（周围 160% 冰属性伤害，减速 2 秒）',
          proc: { chance: 0.06, cd: 1.5, act: 'strike', mul: 1.6, aoe: 110, elem: 'ice', vis: 'ice', name: '冰龙的冰锥' } } },
        pieces: [
          { key: 'ep_sn_skasa_scale', slot: 'support', name: '冰龙的逆鳞', look: 'a single large pale blue ice dragon scale with a frosty sheen, bound with a leather strap and a small silver clasp' },
          { key: 'ep_sn_skasa_eye', slot: 'stone', name: '冰龙之眼', look: 'a round icy blue magic gem shaped like a slit-pupil dragon eye, set in a frosted silver claw frame' },
        ] },
    ],
    quest: [{ key: 'q_sn_shard', look: 'a few small broken pieces of a pale blue stone crystal pendant on a torn leather cord' }],
  },

  dungeons: {
    frozen_heart: { name: '冰心少年', lvl: [36, 37], theme: 'snCave', layout: 'standard', mobs: [['toySoldier', 3], ['toyFine', 2], ['toyMass', 2], ['toyBerserk', 1]], elite: 'toyBerserk', boss: 'charlie', bgm: 'dungeon2', bossBgm: 'boss',
      gate: { x: 420, col: '170,220,255' }, desc: '被冰龙变成冰霜巨人的少年查理，和他的玩具士兵们。火箭拳是一条直线，往上下躲开；坚硬的玩具只能一下一下地敲碎。之后玩具士兵会走向查理的心脏——别让它们碰到，否则查理会回血；心脏被冰晶护住时，打碎冰晶他就会破招。',
      drops: { boss: [['ep_sn_charlie', 0.03]], mats: [['crystal', 0.1, 8], ['c_white', 0.02, 1], ['m_cloth', 0.03, 2]] } },
    lik_well: { name: '利库天井', lvl: [37, 38], theme: 'snRidge', layout: 'long', mobs: [['bantuWarrior', 3], ['frostGoblin', 2], ['foamSpider', 1.5], ['stormGolem', 0.7], ['thunderGolem', 0.7], ['frostGolem', 0.7]], elite: 'catapultCommander', boss: 'lik', bossTheme: 'snLikBoss', bgm: 'dungeon3', bossBgm: 'boss',
      gate: { x: 900, col: '200,230,255' }, desc: '冰封的天井里，寒冰巨人利库守着班图族的冰壁。他的冰裂会冻住人；血量过半后会召来暴风雪和冰霜石巨人。',
      drops: { boss: [['ep_sn_charlie', 0.012]], mats: [['crystal', 0.1, 8], ['m_iron', 0.03, 2], ['c_blue', 0.02, 1]] } },
    ridge: { name: '山脊', lvl: [38, 39], theme: 'snRidge', layout: 'standard', mobs: [['bantuWarrior', 3], ['frostGoblin', 2], ['iceTiger', 2], ['iceSprite', 1]], elite: 'bullBastur', boss: 'ruug', bgm: 'dungeon', bossBgm: 'boss',
      preBoss: { kind: 'bullEmuli', say: '野蛮牛族勇士艾穆利挡住了去路！' },
      gate: { x: 1380, col: '220,235,255' }, desc: '班图族勇士们的试炼之地。野兽师鲁乌格和冰齿沙凡特一起上（两条血条，全部打倒才算赢）：被远程打到它们会霸体，贴上去打；倒下一个，另一个就会暴怒。沙凡特的出血飞跃在锁定后跑出圈。',
      drops: { boss: [['ep_sn_charlie', 0.008]], mats: [['crystal', 0.11, 9], ['m_leather', 0.03, 2], ['c_red', 0.02, 1]] } },
    white_ruins: { name: '白色废墟', lvl: [39, 40], theme: 'snRuins', layout: 'long', mobs: [['snowApe', 2.5], ['iceTiger', 1.5], ['blueGoblin', 2], ['kuniShaman', 1.5], ['snowballRului', 2]], elite: 'avalancheRabina', boss: 'seski', bgm: 'dungeon2', bossBgm: 'boss',
      gate: { x: 1860, col: '240,245,255' }, desc: '雪魈占据的古代废墟。巨猿塞斯奇一靠近就会把人举过头顶狂揍；双掌震地的雪波一排一排地推过来，站进没亮的那一排；库尼图腾要在亮完之前打碎（红的让它狂暴，蓝的给它回血）；它捶胸咆哮时，离它远一点。',
      drops: { boss: [['ep_sn_charlie', 0.012]], mats: [['crystal', 0.11, 9], ['m_bone', 0.03, 2], ['c_white', 0.03, 1]] } },
    bwanga_dojo: { name: '布万加的修炼场', lvl: [40, 41], theme: 'snRidge', layout: 'raid', hidden: true, unlock: { quest: 'q_sn09' },
      mobs: [['bantuWarrior', 2], ['bantuElite', 1], ['tulusWarrior', 1.5], ['kuniShaman', 1]], elite: 'bantuElite', boss: 'bwanga', bossAdds: 0, bgm: 'dungeon3', bossBgm: 'boss',
      preBoss: { kind: 'tulusElite', say: '图卢斯族的精英战士在等你。' },
      gate: { x: 2340, col: '255,220,140' }, desc: '【隐藏】班图族族长、四剑圣之一的布万加的修炼场。先要打赢他的四个勇士：马拉加的冰块要打碎，莱里特拉里的旋风往外跑，美杜莎莎凝视时背对她，霍克伊的猎鹰先打掉。布万加亲自出手后，起跳砸地时在落地的瞬间跳起来，他消失时小心背后；“战吼”读条时要贴近他才安全。',
      bossTheme: 'snDojoBoss', bossProps: [{ kind: 'pillar', x: 0.12, y: 0.1, h: 180, col: '#8a6a4a' }, { kind: 'pillar', x: 0.88, y: 0.1, h: 180, col: '#8a6a4a' }],
      drops: { boss: [['ep_sn_charlie', 0.02]], mats: [['crystal', 0.12, 10], ['m_soul', 0.003, 1], ['m_obsidian', 0.006, 1]] } },
    ice_palace: { name: '冰雪宫殿', lvl: [41, 42], theme: 'snPalace', layout: 'long', mobs: [['iceSprite', 2], ['kuniShaman', 1.5], ['tulusWarrior', 2], ['iceLurker', 1.5], ['aquiles', 0.5]], elite: 'tulusElite', boss: 'rose', bgm: 'dungeon3', bossBgm: 'boss',
      gate: { x: 2820, col: '190,230,255' }, desc: '冰雪女王洛丝的宫殿。洛丝和冰晶王座融为一体，一步也不动；雷剑克鲁斯把她当成了自己的恋人，拼死守护她——先打倒克鲁斯。宫女里的回复宫女会给女王回血，先打她；壁钟敲响时躲到王座后面。血量很低时洛丝会走下王座。',
      bossProps: [{ kind: 'throne', x: 0.772, y: 0.4, h: 180, col: '#cfeaff' }],
      drops: { boss: [['ep_sn_charlie', 0.012]], mats: [['crystal', 0.12, 10], ['m_elem2', 0.01, 1], ['c_blue', 0.03, 2]] } },
    skasa_nest: { name: '斯卡萨之巢', lvl: [42, 42], bossLvl: 44, theme: 'snNest', layout: 'raid', mobs: [['tulusWarrior', 2], ['iceLurker', 1.5], ['babySkasa', 1.5], ['iceSpider', 1.5], ['tulusElite', 0.5]], elite: 'aquiles', boss: 'skasa', bossAdds: 0,
      bgm: 'abyss', bossBgm: 'boss', preBoss: { kind: 'aquiles', say: '冰影阿奎利斯守在巢穴前……' },
      gate: { x: 3300, col: '170,215,255' }, desc: '【攻坚】万年雪山之巅的冰龙巢穴。前爪拍地时跳起来，极寒龙息绕到侧面躲，吹气会把人吹开；龙蛋要在孵化前打碎；蓄力龙息打够伤害就能打断；它飞上天时躲开冰雨。',
      drops: { boss: [['ep_sn_charlie', 0.04], ['ep_de_cross', 0.01]], mats: [['crystal', 0.14, 12], ['m_soul', 0.004, 1], ['m_diamond', 0.01, 1]] } },
  },

  abyss: {
    abyss_snow: { name: '万年雪山深渊', from: 'ice_palace', theme: 'abyssSnow', tint: 'rgba(70,20,120,0.30)', lvl: [41, 42], lordLvl: 44, cost: 1, pity: 7,
      lords: ['charlie', 'lik', 'seski', 'rose'], gate: { scene: 'snow_field', x: 3560 }, clearExp: 15000,
      waves: [
        { n: 6, mobs: [['toySoldier', 1], ['toyMass', 2]], elites: ['toyBerserk'], say: '玩具士兵的游行！' },
        { n: 5, mobs: [['snowApe', 1], ['snowballRului', 1], ['iceTiger', 1]], elite: 1, say: '雪魈群从雪里钻出来了！' },
        { n: 6, mobs: [['tulusWarrior', 2], ['iceSprite', 1]], elites: ['bullBastur', 'bullEmuli'], say: '野蛮牛族的勇士们冲进了派对！' },
      ],
      lord: { mechs: [{ use: 'enrage', t: 220 }], cycle: [{ every: [20, 26], mech: { use: 'hazard', kind: 'debris', every: 3.5, n: 3, dur: 10, col: '#c890ff' } },
        { every: [28, 34], at: 0.6, mech: { use: 'safezone', windup: 3.2, frac: 0.35, say: '深渊之力——站进光圈！' } }] },
      desc: '【深渊派对】冰雪宫殿深处的深渊裂缝。需要消耗 1 张深渊派对邀请函。深渊领主是万年雪山的四个领主之一（每次随机），降临后会引发落石，血量过半时要站进光圈。「冰龙斯卡萨的遗骸」只在这里出现。',
      quest: { name: '雪山的深渊', lvl: 41, clear: 'ice_palace', pre: ['q_abyss_gf'], gold: 5500, desc: '冰雪宫殿深处裂开了深渊。通关冰雪宫殿，歌兰蒂斯就会告诉你万年雪山深渊的入口。',
        offer: ['万年雪山也……被深渊渗进去了。', '冰龙每次沉睡前都会蜕下一片鳞，据说那片鳞就掉进了深渊里。', '先去通关冰雪宫殿吧。'],
        done: ['万年雪山地图的最右边，深渊之门已经打开。穿暖和点。'] } },
  },

  npcs: {
    orca: { name: '奥尔卡', title: '班图族副族长', h: 124, services: ['quest'],
      greet: ['外来的人……拿出你的勇气，证明你是真正的勇士！'], lines: ['冰龙每三十年醒一次。每一次，班图族都要翻过斯特鲁山脉。', '我的哥哥布万加是族长。他只认拳头。', '班图族不想打仗——我们只是想活下去。'],
      look: 'Orca, the vice-chief of the Bantu tribes: a tall strong man in his thirties with tanned skin, long braided dark hair, a short beard, a thick grey wolf pelt over his shoulders, fur-trimmed leather armor with tribal bead ornaments, a big bone-handled axe on his back' },
    balrena: { name: '巴尔雷娜', title: '图卢斯族 · 修理 / 仓库', h: 114, services: ['repair', 'storage'],
      greet: ['哟，冒险家！盔甲坏了？交给大婶就对了！'], lines: ['我有个哥哥叫查理……小时候走丢在雪山里了。', '图卢斯族的盔甲，冰龙都咬不穿！'],
      look: 'Balrena, a cheerful sturdy middle-aged Tulus tribe woman blacksmith: rosy cheeks, thick brown hair tied up with a cloth, small bison horn ornaments in her hair, a fur-lined leather apron over a warm wool dress, rolled-up sleeves, holding a smithing hammer' },
  },
  scenes: {
    storm_pass: { name: '斯顿雪域', area: '班图族的村庄', kind: 'town', width: 2400, theme: 'snTown', bgm: 'guild', ambient: 'magic', map: [58, 64],
      props: [{ art: 'world/p_crates', x: 420, h: 80, y: 30 }, { art: 'world/p_magiclamp', x: 700, h: 110, y: 20 }, { art: 'world/p_magiclamp', x: 1700, h: 110, y: 20 }, { art: 'world/p_crates', x: 2040, h: 80, y: 40 }],
      npcs: [{ npc: 'orca', x: 980, y: 50 }, { npc: 'balrena', x: 1420, y: 60 }],
      exits: [{ side: 'left', to: 'hm_backstreet' }, { side: 'right', to: 'snow_field' }] },
    snow_field: { name: '万年雪山', area: '斯特鲁山脉', kind: 'field', width: 3800, theme: 'snRidge', bgm: 'field', map: [72, 64],
      exits: [{ side: 'left', to: 'storm_pass' }] },
  },

  story: { chapter: '雪山篇 · 冰龙苏醒', prefix: 'q_sn', pre: 'q_de09', npc: 'orca', scene: 'storm_pass', steps: [
    { t: 'arrive', npc: 'sharan', to: 'orca', name: '班图族的侵略', lvl: 36, scene: 'storm_pass', reward: { exp: 0.05, gold: 1500 },
      desc: '班图族翻过斯特鲁山脉，冲击了贝尔玛尔公国的防线。去班图族的村庄斯顿雪域，找副族长奥尔卡谈谈。',
      talk: { offer: ['北边的班图族越过了斯特鲁山脉，公国的防线快守不住了。', '可是……他们不像是来打仗的，更像是在逃难。去斯顿雪域，找副族长奥尔卡问清楚吧。'], doing: ['斯顿雪域在赫顿玛尔后街的北边，Lv.36 才能过去。'], done: ['外来的人？……拿出你的勇气，证明你是真正的勇士！'] } },
    { t: 'clear', dungeon: 'ridge', lvl: 38, name: '班图族的副族长', reward: { exp: 0.09, gold: 2500 },
      desc: '奥尔卡不信任外来的人。通关万年雪山的「山脊」，证明你的实力。',
      talk: { offer: ['班图族只相信勇士。去山脊——我们的勇士都是在那里被认可的。'], doing: ['寒冰虎扑过来之前会压低身子。'], done: ['……你比我想的强。'] } },
    { t: 'boss', dungeon: 'ridge', lvl: 38, name: '真正的战士', reward: { exp: 0.1, gold: 3000 },
      desc: '山脊深处的野兽师鲁乌格和他的冰齿沙凡特被冰龙的气息迷了心智。打倒鲁乌格。',
      talk: { offer: ['鲁乌格曾经是族里最好的驯兽师。冰龙醒来以后，他和他的野兽都疯了。', '他和冰齿沙凡特会一起上。离远了打，它们会霸体——贴上去。'], doing: ['倒下一个，另一个会暴怒。尽量一起打低。'], done: ['你是真正的战士。好——我告诉你班图族的事。', '冰龙斯卡萨醒了。雪山上的一切都在结冰，我们只能往南逃。'] } },
    { t: 'clear', dungeon: 'frozen_heart', lvl: 36, name: '我的孩子', reward: { exp: 0.09, gold: 2500 },
      desc: '雪山的冰洞里常常传出孩子的声音。通关「冰心少年」。',
      talk: { offer: ['雪山的冰洞里有孩子的声音……可那里不可能有人活着。去看看吧。'], doing: ['玩具士兵会自爆，别贴太近。'], done: ['冰洞最深处……有一个冰做的巨人，抱着一堆玩具。'] } },
    { t: 'boss', dungeon: 'frozen_heart', lvl: 37, name: '永恒的悲惨命运', collect: { key: 'q_sn_shard', item: '查理的石晶项链碎片', icon: 'q_sn_shard', desc: '一块淡蓝色石晶的碎片，穿在断掉的皮绳上。' }, npc: 'orca', to: 'balrena', reward: { exp: 0.1, gold: 3000 },
      desc: '冰霜巨人查理身上有一条碎掉的石晶项链。打倒他，把碎片带给图卢斯族的巴尔雷娜。',
      talk: { offer: ['那个冰巨人叫查理……是巴尔雷娜失散多年的哥哥。冰龙把他变成了那样。', '他的心脏被冰晶护着——打碎冰晶，他才会停下来。', '玩具士兵会往他的心脏那边走。别让它们碰到。'], doing: ['把项链碎片带给巴尔雷娜。'], done: ['这是……我小时候送给哥哥的项链。', '谢谢你让他安息。'] } },
    { t: 'clear', dungeon: 'lik_well', lvl: 37, name: '利库天井', reward: { exp: 0.09, gold: 2500 },
      desc: '班图族的冰壁在利库天井。通关它。',
      talk: { offer: ['我们用冰龙的气息把雪山上的怪物冻成了冰壁。可是冰壁在融化……利库天井最危险。'], doing: ['石巨人会架起架势，看准了再打。'], done: ['冰壁后面醒来的是寒冰巨人利库。'] } },
    { t: 'boss', dungeon: 'lik_well', lvl: 38, name: '寒冰巨人利库', reward: { exp: 0.1, gold: 3000 },
      desc: '打倒利库天井深处的寒冰巨人利库。',
      talk: { offer: ['利库的冰裂会把人冻住。看到地上的十字就走开。'], doing: ['它召来暴风雪的时候，注意头顶。'], done: ['利库倒下了。……白色废墟那边，雪魈们也不安分了。'] } },
    { t: 'clear', dungeon: 'white_ruins', lvl: 39, name: '白色废墟', reward: { exp: 0.09, gold: 2500 },
      desc: '通关被雪魈占据的「白色废墟」。',
      talk: { offer: ['白色废墟是古代部族的遗迹，现在是雪魈的窝。'], doing: ['噜噜伊会在远处扔雪球。'], done: ['雪魈们的头领……是一只巨大的猿。'] } },
    { t: 'boss', dungeon: 'white_ruins', lvl: 40, name: '塞斯奇', reward: { exp: 0.1, gold: 3000 },
      desc: '打倒雪魈的头领塞斯奇。',
      talk: { offer: ['塞斯奇一抓住人就不会松手。别贴着它打。', '它捶胸的时候，离它远一点。'], doing: ['雪波是一条直线，往旁边躲。'], done: ['你真的很强。……族长想见你。他在修炼场等你。'] } },
    { t: 'boss', dungeon: 'bwanga_dojo', lvl: 40, name: '布万加的修炼场', reward: { exp: 0.12, gold: 3500 },
      desc: '班图族族长布万加要亲自试一试你。去「布万加的修炼场」，打倒他。',
      talk: { offer: ['我的哥哥布万加——族长，四剑圣之一。他想亲手试试你的实力。', '修炼场的入口是隐藏的，在万年雪山的中间。', '他会先让四个勇士上场：马拉加、莱里特拉里、美杜莎莎、霍克伊。'], doing: ['美杜莎莎凝视的时候背对她。', '布万加跳起来砸地的时候，落地那一下你也跳。“战吼”的时候贴近他。'], done: ['布万加：“哈哈哈！好！你就是真正的勇士！”', '布万加：“冰龙的手下在冰雪宫殿。去吧，班图族跟你一起。”'] } },
    { t: 'clear', dungeon: 'ice_palace', lvl: 41, name: '冰雪宫殿', reward: { exp: 0.09, gold: 3000 },
      desc: '冰龙的手下——冰雪女王洛丝的宫殿就在坎纳克山的峡谷里。通关「冰雪宫殿」。',
      talk: { offer: ['洛丝本来只是一片积雪……冰龙给了她人的身体，让她替自己抓走班图族的人。'], doing: ['宫殿里的图卢斯族战士都被她控制了。'], done: ['宫殿深处，洛丝身边站着一个拿雷剑的男人。'] } },
    { t: 'boss', dungeon: 'ice_palace', lvl: 42, name: '冰雪女王洛丝', reward: { exp: 0.12, gold: 4000 },
      desc: '打倒冰雪女王洛丝，把被控制的班图族人救回来。',
      talk: { offer: ['那个男人是雷剑克鲁斯。洛丝在梦里骗他，让他以为自己是他的恋人。先打倒克鲁斯——别杀他。', '洛丝坐在王座上不会动。她的宫女里有一个会给她回血——先打那个。'], doing: ['壁钟敲响的时候，躲到王座后面。'], done: ['族人们醒过来了。克鲁斯……也醒了。', '冰龙斯卡萨就在山顶的巢穴里。'] } },
    { t: 'raid', dungeon: 'skasa_nest', lvl: 42, name: '冰龙斯卡萨', reward: { exp: 0.18, gold: 7000, coins: 2 },
      desc: '登上万年雪山之巅，讨伐冰龙斯卡萨。',
      talk: { offer: ['斯卡萨会冰封自己，先击破冰龙之卵。', '“冰封大地”的时候跳起来，“绝对零度”的时候站进光圈。', '去吧，勇士。班图族的命运交给你了。'], doing: ['暴风雪来的时候注意头顶。'], done: ['……冰龙倒下了。雪山的冬天，终于要结束了。'] } },
    { t: 'handin', to: 'orca', lvl: 42, name: '你就是打败斯卡萨的勇士', reward: { exp: 0.08, gold: 4000, items: [{ key: 'ep_sn_charlie', n: 1 }] },
      desc: '回斯顿雪域，把好消息告诉奥尔卡。',
      talk: { offer: ['冰龙斯卡萨倒下了。'], done: ['你就是那位打败斯卡萨的勇士吗？', '巴尔雷娜把查理的项链修好了，她说要交给你——哥哥一定也希望这样。', '——雪山篇 · 完——'] } },
  ] },

  art: {
    chars: {
      snToy: { h: 84, hold: 'holding a wooden toy sword', desc: 'A toy soldier monster brought to life in a frozen cave: a knee-high wooden nutcracker-style toy soldier with a tall red and gold shako hat, a blue painted jacket with gold buttons, white trousers, round painted rosy cheeks, visible wooden joints, holding a wooden toy sword.',
        atk: 'the wooden toy sword', cast: 'raising the toy sword high and marching in place', low: 'lunging forward low with the toy sword' },
      snCharlie: { h: 140, boss: true, hold: 'with huge icy fists', desc: 'Charlie the Frozen-Hearted Boy, a boss of the eternal snow mountain: a big childlike frost giant made of pale blue ice and packed snow, a round boyish face with sad big eyes, a small tuft of icy hair, a tattered knitted scarf and a small wooden toy soldier tucked in his belt, a glowing blue ice crystal heart visible in his chest, huge icy fists.',
        atk: 'his huge icy fist', cast: 'hugging himself as his crystal heart glows', low: 'crouching low and punching the ground',
        sig: ['rocket punch: pulling one icy arm far back, then firing the fist straight forward like a rocket with the arm fully extended, body leaning into it', 'toy command: holding a wooden toy soldier high over his head with both hands, stomping and crying out'] },
      snBantu: { h: 108, hold: 'holding a bone-handled war axe', desc: 'A Bantu tribe warrior of the snowy mountains: a sturdy tanned man with braided dark hair, a grey wolf head pelt worn as a hood, fur-trimmed leather armor with bone and bead ornaments, fur boots, painted tribal marks on the cheeks, holding a bone-handled war axe.',
        atk: 'the war axe', cast: 'raising the war axe overhead with a war cry', low: 'charging forward low with the axe held back',
        // 招牌动作（野兽师鲁乌格用：上勾拳 / 飞斧；班图战士、四勇士共用这张表，它们不放招牌招式）
        sig: ['rising uppercut: crouching low, then springing upward with a huge uppercut of the free fist, feet leaving the ground', 'axe throw: winding the bone-handled war axe far behind the head and hurling it forward in a spinning throw'] },
      snTiger: { h: 72, hold: null, holes: false, outline: '#2a4a7a', cycle: 'trot', desc: 'An ice tiger monster of the snow mountain: a lean four-legged white tiger with pale blue stripes, frosty fur tips, long ice-blue fangs, glowing light blue eyes and small ice shards along its back.',
        atk: 'its icy fangs', cast: 'rearing up and roaring', low: 'crouching low ready to pounce' },
      snYeti: { h: 110, hold: null, holes: false, outline: '#2a4a7a', desc: 'A snow ape (yeti) monster of the white ruins: a big hunched ape with shaggy white fur, a pale blue-grey face with a heavy brow, long powerful arms with huge hands, a few icicles hanging from its fur, big flat feet.',
        atk: 'its huge hands', cast: 'beating its chest with both fists', low: 'knuckle-walking forward low',
        sig: ['overhead pummel: grabbing forward with both huge hands, lifting the catch high above its head and slamming it down again and again', 'double palm quake: rearing up on its legs and slamming both palms flat onto the ground so hard its fur flies up'] },
      snRose: { h: 124, boss: true, holes: false, outline: '#2a4a7a', hold: 'holding a slender ice crystal scepter', desc: 'Rose the Snow Queen, a boss of the Ice Palace: an elegant cold beautiful woman made from snow given a human body, pale blue skin, long flowing white hair with ice crystal ornaments, an ice crown, a long modest high-collared gown of layered pale blue and white frost fabric with long sleeves, holding a slender ice crystal scepter.',
        atk: 'the ice crystal scepter', cast: 'raising the scepter as her gown flutters', low: 'gliding forward low with the scepter pointed',
        sig: ['summon maidens: raising the ice scepter high with one hand and sweeping the other hand out in a regal command', 'blizzard breath: leaning forward and blowing a long freezing breath over the scepter held flat in front of her lips'],
        // 新形态（BOSS_PLAN §3.3 必须出新图）：官方的洛丝和冰晶王座融为一体、不能移动。出图后领主平时用 snRose_throne（不走路：参考图 + act + more），最后走下王座时换回 snRose
        forms: { throne: { h: 170, sheets: ['act', 'more'], desc: 'Rose the Snow Queen seated on (merged with) a tall glittering ice crystal throne: an elegant cold beautiful woman made from snow given a human body, pale blue skin, long flowing white hair with ice crystal ornaments, an ice crown, a long high-collared gown of layered pale blue and white frost fabric whose hem melts into the throne; the throne has tall jagged crystal spires and frozen roses. She never stands up.',
          atk: 'pointing the ice scepter forward from the throne', cast: 'raising the scepter high from the throne as the spires glow', low: 'leaning forward on the throne with the scepter pointed down' } } },
      snBwanga: { h: 132, boss: true, hold: 'holding a huge spiked iron club', desc: 'Bwanga, the chief of the Bantu tribes and one of the four sword saints: a huge muscular cheerful man with tanned skin, wild long dark hair and a thick beard, a big bear pelt cloak with the head as a hood, heavy fur and leather armor with tribal bone ornaments, bracers, holding a huge spiked iron club on his shoulder.',
        atk: 'the huge spiked club', cast: 'raising the club high with a hearty laugh', low: 'charging forward low with the club held back',
        sig: ['leaping slam: crouching deep, leaping high with the spiked club raised over the head with both hands, then crashing down club-first', 'vanishing backstab: turning around mid-step and swinging the club upward from low behind in a launching uppercut swing'] },
      snSkasa: { h: 140, boss: true, cycle: 'trot', desc: 'Skasa the Ice Dragon, the ancient fierce adult dragon of the eternal snow mountain: a huge heavily built four-legged dragon with a long powerful neck, a large angular head with a menacing scowl, long sharp swept-back horns, bared sharp fangs, cold glowing pale blue eyes, thick armored glacier-blue scales, jagged ice-crystal spines running along the back and tail, big tattered frosty wings folded, massive clawed feet. Menacing and powerful, an adult dragon, not a baby, not cute.',
        atk: 'its huge icy jaws biting', cast: 'rearing its head up and spreading its wings', low: 'lowering its head and lunging forward' },
      snLik: { h: 150, boss: true, hold: null, outline: '#2a4a7a', desc: 'Lik the Frost Giant, an ancient boss of the eternal snow mountain: a colossal hulking giant made of dark slate-blue rock armored with thick translucent glacier-blue ice plates, very top-heavy with enormous shoulders and very long massive arms whose fists hang down near the knees, big jagged pale-cyan ice crystal clusters growing out of his shoulders and upper back like frozen mountain peaks, a small craggy head sunk low between the shoulders with a heavy frosty brow, two glowing icy cyan eyes and a short beard of icicles, huge blocky fists encrusted with ice crystals, short thick sturdy legs, a broken iron shackle with three chain links around one wrist. Menacing and powerful, an adult giant boss, not a child, not cute.', atk: 'his huge ice-crystal fist', cast: 'raising both huge fists to the sky and roaring', low: 'charging forward shoulder-first with the head down', sig: ['frost nova: hunching down and hugging both huge fists tight against his chest, then throwing both arms and his chest wide open to the sides in a huge outward burst pose', 'giant grab: lunging far forward and reaching out low with one enormous open hand to seize an enemy, then heaving the clenched fist high overhead'], rage: 'enraged roar: rearing up to full height, head thrown back roaring, both huge fists raised and clenched' },
    },
    gates: {
      frozen_heart: 'an ice cave entrance framed by giant blue ice crystals with a frozen wooden toy soldier on each side, a pale blue portal',
      lik_well: 'a deep icy shaft entrance with a wooden Bantu gate frame, hanging ropes and a huge frozen ice wall behind, a white-blue portal',
      ridge: 'a snowy mountain pass gate made of two tall carved Bantu totem poles with wolf and bison heads and war banners, a pale white portal',
      white_ruins: 'a crumbling ancient stone archway buried in snow with huge icicles and a straw ape nest on top, a white portal',
      bwanga_dojo: 'a sturdy Bantu training ground gate made of big logs with a huge carved bear skull and crossed clubs on top, a warm golden portal',
      ice_palace: 'an elegant gate carved from glittering ice with crystal spires and frozen roses climbing the sides, a pale blue portal',
      skasa_nest: 'a colossal gate made of two huge frozen dragon ribs meeting at the top with a giant ice dragon skull, a deep blue portal',
    },
  },
});
