/* =====================================================================
   区域：时空之门（官方 80 版本 Lv70~77；满级 60 后放在 Lv55~59，希洛克 Lv60 的前一站）
   官方依据：三条龙被释放到阿拉德大陆，冒险家通过时空之门回到过去调查幕后黑手；前置任务在剑圣西岚那里。
     八张地下城：格兰之火（兽王乌塔拉，森林大火、“灭火”机制）、瘟疫之源（骷髅骑士，暗精灵村庄的瘟疫来自异次元裂缝、“治疗瘟疫”机制）、
     卡勒特之初（沙影贝利特，卡勒特成立之时的西部无法地带）、暗黑圣战（尼尔巴斯·格拉西亚，圣职者击退奥兹玛之后、小女孩寻找失踪的哥哥）、
     绝密区域（地狱三头犬，比尔马克帝国试验场最深处）、昔日悲鸣（凯恩，阿甘左的噩梦：当年在悲鸣洞穴和使徒希洛克的对决）、
     凛冬（年轻的斯卡萨，昔日的万年雪山）、谜之觉悟（攻坚，吟游诗人艾丽丝——所有线索指向的暗黑城使者）。
     时空之门深渊：打倒凯恩 / 年轻的斯卡萨 / 艾丽丝各一次后开启（这里写成资格任务的前置）。
   本作原创：入口放在鲁夫特港的灯塔（官方在素喃）、各招式与机制组合（火种 = 无敌阶段的水晶、瘟疫之源 = 连线搭档、沙暴缩圈等）、
     史诗「吟游诗人的竖琴」、深渊专属「时空旅者」。
   入口：鲁夫特悬空海港（x 1900 往上，Lv.55）→ 时空之门（左：过去的回廊 · 前段；右：过去的回廊 · 后段 Lv.57；往上：魔界 Lv.60）
   ===================================================================== */
defineRegion({
  id: 'timegate', name: '时空之门', lvl: 55, lvlMax: 59, power: 1.3, bossPower: 1, atkPower: 1.12,
  entry: { scene: 'luft_port', side: 'up', x: 1900, to: 'time_gate', minLv: 55, label: '时空之门' },

  themes: {
    tgTown: { grade: { tint: 'rgba(70,60,130,0.10)', fog: 'rgba(190,180,255,0.08)' }, ambient: 'motes', rgb: '215,205,255', floorW: 1700,
      pal: { sky: ['#1a1838', '#40407a', '#8a86c0'], haze: '#c8c0ff' },
      bg: ['The Gate of Time and Space: an ancient stone plaza on a floating island at the edge of the sky, a giant ring-shaped portal gate of carved stone and brass clockwork gears with a swirling blue-violet void inside, floating clock faces and hourglasses, stone pillars with runes, a twilight sky with drifting stars.',
        'ancient stone floor tiles engraved with clock dial patterns and runes',
        'broken stone pillars, small brass gears and hourglass statues along a low stone wall'] },
    tgFire: { edgeHoles: true, grade: { tint: 'rgba(150,60,20,0.14)', fog: 'rgba(255,150,80,0.08)' }, ambient: 'wisps', rgb: '255,170,110', floorW: 1700,
      pal: { sky: ['#2a1008', '#6a2a10', '#c06030'], haze: '#ff9a5a' },
      bg: ['The Grand Flores forest of the past on fire: huge ancient trees burning, a red-orange sky with dark smoke clouds, fallen burning logs, a ruined elf shrine of white stone, the whole great forest turning to ash.',
        'scorched forest ground with grey ash, charred roots and fallen dry leaves',
        'burnt tree stumps, charred fallen logs and blackened bushes'] },
    tgPlague: { edgeHoles: true, grade: { tint: 'rgba(90,100,40,0.14)', fog: 'rgba(200,210,120,0.10)' }, ambient: 'wisps', rgb: '210,220,150', floorW: 1700,
      pal: { sky: ['#1a1a20', '#3a3a2a', '#6a6a40'], haze: '#c8d090' },
      bg: ['The dark elf village of the past struck by a plague: dark elf houses carved into a huge violet cavern, a sickly yellow miasma drifting between the houses, abandoned market stalls, cloth masks on the ground, a jagged glowing dimensional rift crack in the cave wall.',
        'cracked cave stone floor with scattered bones, spilled potion bottles and purple fungus',
        'broken crates, plague warning cloth signs and piles of bones along a low cave wall'] },
    tgDesert: { grade: { tint: 'rgba(160,120,60,0.10)', fog: 'rgba(255,220,150,0.10)' }, ambient: 'motes', rgb: '255,225,160', floorW: 1700,
      pal: { sky: ['#6a4a2a', '#c08a50', '#f0d098'], haze: '#ffe0a8' },
      bg: ['The western lawless desert in the days when the Kartel was founded: endless golden sand dunes, a small frontier outpost of wooden shacks and a water tower, a sandstorm on the horizon, a blazing sun, bleached animal skulls, a crude Kartel flag on a pole.',
        'hard packed desert sand with footprints, pebbles and dry grass tufts',
        'wooden fence posts, cactus, bleached cow skulls and sand-covered crates'] },
    tgHoly: { edgeHoles: true, grade: { tint: 'rgba(80,70,120,0.14)', fog: 'rgba(220,210,255,0.08)' }, ambient: 'motes', rgb: '230,220,255', floorW: 1700,
      pal: { sky: ['#14121e', '#34304a', '#8a84a8'], haze: '#d8d0ff' },
      bg: ['The battlefield of the Dark Holy War of the past: a ruined grand cathedral with broken stained glass windows and toppled statues of saints, a dark stormy sky split by a beam of pale light, scattered shields and banners of the holy army, a crater of dark chaos in the distance.',
        'cracked white marble cathedral floor with scattered broken shields and torn banners',
        'toppled saint statues, broken wooden pews and fallen marble pillars'] },
    tgRift: { edgeHoles: true, grade: { tint: 'rgba(90,40,130,0.16)', fog: 'rgba(200,160,255,0.08)' }, ambient: 'motes', rgb: '220,190,255', floorW: 1800,
      pal: { sky: ['#0e0818', '#2a1644', '#6a4a9a'], haze: '#c8a8ff' },
      bg: ['The Mysterious Realization, a dreamlike dimensional rift beyond time: fragments of past places floating in a dark violet void (a piece of burning forest, a desert dune, a snowy peak, a cave mouth), giant broken clock gears and hourglasses, an old moonlit theater stage with heavy curtains, eerie starlight.',
        'a floating stone stage floor engraved with clock patterns and scattered sheet music pages',
        'broken clock gears, cracked hourglasses and old theater footlights along the stage edge'] },
  },

  monsters: {
    // 格兰之火
    fireGoblin: { name: '燃烧的哥布林', tier: 'normal', arch: 'aggressive', size: [13, 11, 84], elem: 'fire', art: ['goblin', { hue: -85, sat: 1.1, bright: 0.8, only: [60, 170] }],
      skills: [{ use: 'swipe', n: 2, reach: 64, dmg: 1.0, cd: [1.4, 2.4], w: 2 }, { use: 'shot', clip: 'throw', mode: 'arc', r: 56, dmg: 0.9, status: 'burn', col: '#ff8a3a', cd: [3.5, 5] }] },
    fireTreant: { name: '燃烧的树精', tier: 'brute', arch: 'guard', size: [20, 14, 124], weight: 4, hardness: 30, elem: 'fire', art: ['treant', { hue: -80, sat: 1.2, bright: 0.7, only: [60, 170] }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.7, dmg: 1.2, down: true, cd: [2.4, 3.4], w: 2 }, { use: 'aoe', shape: 'ring', at: 'self', r: 150, r0: 50, windup: 1.1, dmg: 0.9, status: 'root', sdur: 1.2, col: '#c08a4a', cd: [8, 10], say: '燃烧的树根' }] },
    fireSpirit: { name: '火焰精灵', tier: 'swarm', arch: 'guard', size: [12, 10, 70], speed: 120, elem: 'fire', art: ['ador', { hue: -10, sat: 1.1 }], traits: { onDeath: 'explode', explode: { r: 70, windup: 0.7, dmg: 0.8 } },
      skills: [{ use: 'shot', mode: 'homing', speed: 220, turn: 2.0, dmg: 0.75, status: 'burn', col: '#ffaa4a', cd: [3, 4.5] }] },
    fireSeed: { name: '燃烧的火种', tier: 'swarm', arch: 'guard', size: [14, 12, 80], weight: 99, speed: 1, elem: 'fire', art: ['ador', { hue: 15, sat: 1.3, bright: 1.1 }], traits: { immune: ['stun', 'freeze'] },
      skills: [{ use: 'shot', mode: 'homing', speed: 200, turn: 1.8, dmg: 0.7, status: 'burn', col: '#ffaa4a', cd: [4, 6] }] },
    lavaGolem: { name: '熔岩巨人', tier: 'brute', arch: 'aggressive', size: [20, 15, 128], scale: 1.1, weight: 5, elem: 'fire', art: ['flamehulk', { hue: -10, sat: 1.0, bright: 0.8 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', n: 2, reach: 92, width: 30, dmg: 1.15, cd: [2, 3], w: 2 }, { use: 'rain', kind: 'hex', n: 3, r: 46, windup: 1.2, dmg: 1.0, col: '#ff6a2a', cd: [7, 9], say: '熔岩喷发' }] },
    fireChief: { name: '焚烬的哥布林酋长', tier: 'elite', arch: 'aggressive', size: [16, 13, 110], scale: 1.2, weight: 3, elem: 'fire', art: ['goblinChief', { hue: -85, sat: 1.1, bright: 0.8, only: [60, 170] }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 90, dmg: 1.05, cd: [1.8, 2.6], w: 2 }, { use: 'dash', len: 340, speed: 720, windup: 0.6, dmg: 1.2, cd: [4.5, 6] }, { use: 'buff', kind: 'enrage', target: 'allies', r: 320, dur: 8, cd: [16, 20], say: '吼——！' }] },
    // 瘟疫之源
    plagueGhoul: { name: '染疫的食尸鬼', tier: 'normal', arch: 'aggressive', size: [14, 12, 100], elem: 'dark', art: ['deGhoul', { hue: 55, sat: 1.2, bright: 0.9 }],
      skills: [{ use: 'swipe', clip: 'scratch', n: 2, reach: 66, dmg: 1.0, status: 'poison', cd: [1.4, 2.4], w: 2 }, { use: 'dash', clip: 'pounce', len: 280, speed: 680, windup: 0.6, dmg: 1.05, cd: [4.5, 6] }] },
    plagueSkel: { name: '瘟疫骷髅兵', tier: 'normal', arch: 'aggressive', size: [13, 12, 104], elem: 'dark', art: ['deSkel', { hue: 60, sat: 1.1, bright: 0.85 }],
      skills: [{ use: 'swipe', n: 3, reach: 74, dmg: 0.9, cd: [1.6, 2.6], w: 2 }, { use: 'guard', dur: 1.8, reduce: 0.7, cd: [8, 10] }] },
    plagueGhost: { name: '瘟疫之灵', tier: 'flier', arch: 'flier', size: [14, 12, 80], elem: 'dark', art: ['deGhost', { hue: -150, sat: 1.2, bright: 0.95 }],
      skills: [{ use: 'shot', mode: 'homing', speed: 230, turn: 2.2, dmg: 0.85, status: 'poison', col: '#d8e070', cd: [3, 4.5], w: 2 }, { use: 'blink', to: 'behind', dist: 80, cd: [6, 8], w: 0.6 }] },
    plagueSpider: { name: '变异的洞穴蜘蛛', tier: 'swarm', arch: 'swarm', size: [16, 12, 56], speed: 150, elem: 'dark', art: ['deSpider', { hue: -40, sat: 0.7, bright: 0.85 }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 56, dmg: 0.75, status: 'poison', cd: [1.2, 2.2] }] },
    plagueHeadless: { name: '染疫的无头骑士', tier: 'elite', arch: 'aggressive', size: [16, 13, 116], scale: 1.15, elem: 'dark', art: ['deHeadless', { hue: 140, sat: 1.0, bright: 0.85 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 92, dmg: 1.05, cd: [1.6, 2.4], w: 2 }, { use: 'dash', len: 360, speed: 760, windup: 0.6, dmg: 1.2, cd: [4.5, 6] }, { use: 'aoe', shape: 'circle', at: 'target', r: 80, n: 2, scatter: 120, windup: 1.1, dmg: 0.9, status: 'curse', sdur: 2, col: '#c8d070', cd: [8, 10], say: '瘟疫诅咒' }] },
    plagueHeart: { name: '瘟疫之源', tier: 'flier', arch: 'guard', size: [16, 13, 90], weight: 99, speed: 1, elem: 'dark', art: ['deGhost', { hue: -140, sat: 1.6, bright: 0.7 }], traits: { immune: ['stun', 'freeze'] },
      skills: [{ use: 'aoe', shape: 'circle', at: 'target', r: 70, windup: 1.2, dmg: 0.8, status: 'poison', col: '#d8e070', cd: [4, 6] }] },
    // 卡勒特之初
    desertBandit: { name: '沙漠盗贼', tier: 'normal', arch: 'aggressive', size: [13, 12, 100], art: ['nmBandit', { hue: 30, sat: 1.2, bright: 1.1 }],
      skills: [{ use: 'swipe', n: 2, reach: 70, dmg: 1.0, cd: [1.4, 2.4], w: 2 }, { use: 'dash', len: 300, speed: 700, windup: 0.7, dmg: 1.1, cd: [4.5, 6] }] },
    youngKartel: { name: '卡勒特的创始成员', tier: 'caster', arch: 'kiter', size: [13, 12, 104], art: ['gtSoldier', { hue: 25, sat: 2.3, bright: 1.1 }],
      skills: [{ use: 'shot', mode: 'straight', speed: 480, dmg: 0.85, cd: [1.6, 2.6], w: 2.5, col: '#ffd070' }, { use: 'shot', clip: 'throw', mode: 'arc', r: 56, dmg: 0.9, col: '#ffb050', cd: [4, 6] }] },
    sandSpider: { name: '沙漠毒蛛', tier: 'swarm', arch: 'swarm', size: [16, 12, 56], speed: 155, art: ['deSpider', { hue: 125, sat: 0.7, bright: 1.1 }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 56, dmg: 0.75, status: 'poison', cd: [1.2, 2.2] }, { use: 'dash', clip: 'pounce', len: 220, speed: 620, windup: 0.5, dmg: 0.8, cd: [5, 7] }] },
    desertRider: { name: '沙漠骑手', tier: 'elite', arch: 'aggressive', size: [20, 14, 110], speed: 160, art: ['gtSuleide', { hue: 30, sat: 1.1, bright: 1.1 }], traits: { sa: 'cast' },
      skills: [{ use: 'dash', len: 480, speed: 860, windup: 0.6, dmg: 1.2, cd: [3, 4.5], w: 2, say: '驾！' }, { use: 'aoe', shape: 'circle', at: 'self', r: 120, windup: 0.6, dmg: 1.0, status: 'blind', sdur: 1.5, col: '#e8c890', cd: [6, 8], say: '扬沙！' }] },
    // 暗黑圣战
    ozmaCultist: { name: '奥兹玛的信徒', tier: 'caster', arch: 'kiter', size: [13, 12, 100], elem: 'dark', art: ['gbl', { hue: 160, sat: 1.3, bright: 0.65 }],
      skills: [{ use: 'shot', clip: 'cast', mode: 'homing', speed: 240, turn: 2.2, dmg: 0.85, col: '#b070ff', cd: [3, 4.5], w: 2 }, { use: 'buff', clip: 'cast', kind: 'heal', target: 'allies', r: 280, amt: 0.1, cd: [7, 9], say: '混沌的祝福' }] },
    fallenPaladin: { name: '堕落的圣骑士', tier: 'brute', arch: 'guard', size: [17, 13, 118], scale: 1.1, weight: 3, hardness: 40, elem: 'dark', art: ['gatekeeper', { hue: 200, sat: 0.7, bright: 0.6 }], traits: { sa: 'cast' },
      skills: [{ use: 'guard', dur: 2.4, reduce: 0.85, cd: [6, 8], w: 1.5, counter: { use: 'aoe', shape: 'cross', at: 'self', len: 180, hw: 26, windup: 0.4, dmg: 1.1, col: '#b070ff' } }, { use: 'swipe', clip: 'slam', reach: 90, dmg: 1.15, down: true, cd: [2.4, 3.4], w: 2 }] },
    chaosBeast: { name: '混沌魔兽', tier: 'normal', arch: 'aggressive', size: [16, 12, 90], speed: 135, elem: 'dark', art: ['stalker', { hue: -80, sat: 0.9, bright: 0.85 }],
      skills: [{ use: 'swipe', clip: 'scratch', n: 2, reach: 66, dmg: 1.0, cd: [1.4, 2.2], w: 2 }, { use: 'dash', clip: 'pounce', len: 320, speed: 740, windup: 0.6, dmg: 1.1, cd: [4, 6] }] },
    chaosEye: { name: '混沌之眼', tier: 'flier', arch: 'flier', size: [14, 12, 70], elem: 'dark', art: ['gazer', { hue: 90, sat: 1.0, bright: 0.8 }],
      skills: [{ use: 'laser', windup: 1.2, dur: 0.9, sweep: 40, dmg: 0.45, col: '#c890ff', cd: [6, 8], w: 1.4 }, { use: 'shot', mode: 'spread', n: 3, spread: 40, speed: 300, dmg: 0.7, col: '#b070ff', cd: [3.5, 5] }] },
    chaosPriest: { name: '混沌祭司', tier: 'elite', arch: 'kiter', size: [15, 12, 116], scale: 1.1, elem: 'dark', art: ['archbishop', { hue: 170, sat: 1.3, bright: 0.55 }],
      skills: [{ use: 'rain', kind: 'hex', n: 4, r: 48, windup: 1.2, dmg: 1.0, col: '#b070ff', cd: [7, 9], w: 1.5, say: '混沌降临' }, { use: 'summon', kind: 'chaosBeast', n: 2, max: 3, cd: [14, 18] }, { use: 'shot', mode: 'homing', n: 2, spread: 40, speed: 240, dmg: 0.8, col: '#b070ff', cd: [3.5, 5] }] },
    // 绝密区域
    labRobot: { name: '试验型战斗机器人', tier: 'normal', arch: 'aggressive', size: [14, 12, 92], art: ['bmRobot', { hue: -40, sat: 1.2, bright: 0.9 }],
      skills: [{ use: 'swipe', n: 2, reach: 64, dmg: 1.0, cd: [1.4, 2.4], w: 2 }, { use: 'laser', windup: 1.0, dur: 0.5, hw: 12, dmg: 0.9, col: '#ff6a6a', cd: [5, 7] }] },
    labIvan: { name: '失控的伊凡', tier: 'swarm', arch: 'swarm', size: [12, 10, 80], speed: 145, art: ['bmIvan', { hue: 180, sat: 0.8 }], traits: { onDeath: 'explode', explode: { r: 80, windup: 0.8, dmg: 1.0 } },
      skills: [{ use: 'swipe', reach: 54, dmg: 0.75, cd: [1.2, 2.2] }] },
    labMechTau: { name: '机械牛头试验体', tier: 'brute', arch: 'aggressive', size: [18, 14, 120], scale: 1.05, weight: 4, art: ['bmMechTau', { hue: 180, sat: 0.9, bright: 0.85 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'axe', reach: 92, width: 30, dmg: 1.15, down: true, cd: [2, 3], w: 2 }, { use: 'dash', clip: 'charge', len: 360, speed: 760, windup: 0.7, dmg: 1.2, cd: [4.5, 6] }] },
    labHound: { name: '试验体猎犬', tier: 'normal', arch: 'aggressive', size: [16, 12, 72], speed: 140, elem: 'fire', art: ['hound', { hue: -150, sat: 1.3, bright: 0.75 }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 62, dmg: 0.95, cd: [1.4, 2.4], w: 2 }, { use: 'dash', clip: 'chargeW', len: 340, speed: 720, windup: 0.7, dmg: 1.1, cd: [4, 6] }] },
    labWalker: { name: '试验型战斗兵器', tier: 'elite', arch: 'guard', size: [22, 16, 120], scale: 0.95, weight: 6, speed: 70, hardness: 50, art: ['gtMech', { hue: 120, sat: 0.7, bright: 0.85 }], traits: { sa: 'always', immune: ['stun', 'freeze'] },
      skills: [{ use: 'swipe', clip: 'slam', reach: 110, width: 34, windup: 0.7, dmg: 1.2, down: true, cd: [2.4, 3.4], w: 2 }, { use: 'rain', kind: 'hex', n: 4, r: 50, windup: 1.2, dmg: 1.0, col: '#ffb050', cd: [7, 9], say: '导弹发射' },
        { use: 'laser', windup: 1.2, dur: 1.0, sweep: 40, dmg: 0.5, col: '#ff6a6a', cd: [8, 10] }] },
    // 昔日悲鸣
    pastLarva: { name: '悲鸣洞穴的幼虫', tier: 'swarm', arch: 'swarm', size: [18, 12, 50], speed: 120, elem: 'dark', art: ['wcLarva', { hue: 40, sat: 1.0, bright: 0.85 }],
      skills: [{ use: 'swipe', clip: 'bite', reach: 56, dmg: 0.75, status: 'poison', cd: [1.2, 2.2] }, { use: 'shot', mode: 'arc', r: 48, dmg: 0.7, status: 'poison', col: '#c0d070', cd: [4, 6] }] },
    caveSpider: { name: '悲鸣洞穴的蜘蛛', tier: 'normal', arch: 'aggressive', size: [16, 12, 60], speed: 140, elem: 'dark', art: ['deSpider', { hue: -40, sat: 1.1, bright: 0.8 }],
      skills: [{ use: 'swipe', clip: 'bite', n: 2, reach: 62, dmg: 0.95, cd: [1.4, 2.4], w: 2 }, { use: 'shot', mode: 'straight', speed: 380, dmg: 0.75, status: 'slow', col: '#e0e0e8', cd: [4, 6], say: '' }] },
    siroShade: { name: '希洛克的残影', tier: 'flier', arch: 'flier', size: [14, 12, 100], elem: 'dark', art: ['siPhantom', { hue: -30, sat: 0.9, bright: 0.85 }],
      skills: [{ use: 'seq', cd: [5, 7], w: 1.5, steps: [{ use: 'blink', to: 'behind', dist: 70 }, { use: 'swipe', n: 2, reach: 70, dmg: 0.9 }] }, { use: 'shot', mode: 'homing', speed: 240, turn: 2.2, dmg: 0.8, col: '#b890ff', cd: [3.5, 5] }] },
    nightmareBlade: { name: '噩梦中的剑士', tier: 'elite', arch: 'aggressive', size: [15, 12, 116], scale: 1.1, elem: 'dark', art: ['sandor', { hue: -30, sat: 1.2, bright: 0.8 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 92, dmg: 1.05, cd: [1.6, 2.4], w: 2 }, { use: 'aoe', shape: 'line', at: 'front', len: 300, hw: 30, windup: 0.8, dmg: 1.15, col: '#c890ff', cd: [5, 7], say: '剑气！' }, { use: 'blink', to: 'behind', dist: 80, cd: [7, 9], w: 0.6 }] },
    // 凛冬
    pastYeti: { name: '昔日的雪人', tier: 'brute', arch: 'aggressive', size: [18, 14, 110], weight: 3, elem: 'ice', art: ['snYeti', { hue: 20, sat: 0.9, bright: 0.95 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', n: 2, reach: 86, dmg: 1.1, cd: [2, 3], w: 2 }, { use: 'shot', clip: 'throw', mode: 'arc', r: 60, dmg: 1.0, status: 'freeze', sdur: 1.2, col: '#bfe6ff', cd: [5, 7], say: '雪球！' }] },
    pastTiger: { name: '昔日的冰虎', tier: 'normal', arch: 'aggressive', size: [18, 12, 72], speed: 145, elem: 'ice', art: ['snTiger', { hue: 15, sat: 1.0, bright: 0.95 }],
      skills: [{ use: 'swipe', clip: 'scratch', n: 2, reach: 64, dmg: 1.0, cd: [1.4, 2.2], w: 2 }, { use: 'dash', clip: 'pounce', len: 320, speed: 740, windup: 0.6, dmg: 1.1, cd: [4, 6] }] },
    pastBantu: { name: '昔日的班图战士', tier: 'caster', arch: 'kiter', size: [13, 12, 104], elem: 'ice', art: ['snBantu', { hue: 25, sat: 1.1 }],
      skills: [{ use: 'shot', clip: 'throw', mode: 'straight', speed: 500, dmg: 0.85, col: '#e0f0ff', cd: [2, 3], w: 2 }, { use: 'aoe', shape: 'circle', at: 'target', r: 70, n: 2, scatter: 110, windup: 1.1, dmg: 0.9, status: 'slow', col: '#9ad8ff', cd: [6, 8] }] },
    iceWyvern: { name: '冰霜飞龙', tier: 'flier', arch: 'flier', size: [16, 12, 90], elem: 'ice', art: ['wyvern', { hue: 60, sat: 0.8, bright: 1.15 }],
      skills: [{ use: 'aoe', shape: 'line', at: 'front', len: 240, hw: 28, windup: 0.9, dmg: 0.95, status: 'freeze', sdur: 1, col: '#9ad8ff', cd: [5, 7], w: 1.5, say: '冰之吐息' }, { use: 'swipe', clip: 'bite', reach: 64, dmg: 0.9, cd: [2, 3] }] },
    frostApe: { name: '冰原巨猿', tier: 'elite', arch: 'aggressive', size: [20, 15, 124], scale: 1.25, weight: 5, elem: 'ice', art: ['snYeti', { hue: -20, sat: 0.8, bright: 0.8 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', clip: 'slam', n: 3, reach: 96, dmg: 1.1, cd: [1.8, 2.6], w: 2 }, { use: 'grab', reach: 66, hold: 0.8, throwDmg: 1.4, cd: [7, 9] }, { use: 'aoe', shape: 'ring', at: 'self', r: 170, r0: 50, windup: 1.1, dmg: 1.0, jump: true, col: '#9ad8ff', cd: [8, 10], say: '震地——跳起来！' }] },
    // 谜之觉悟
    riftGazer: { name: '时空的凝视者', tier: 'flier', arch: 'flier', size: [14, 12, 70], elem: 'dark', art: ['gazer', { hue: -60, sat: 1.1, bright: 0.95 }],
      skills: [{ use: 'laser', windup: 1.2, dur: 0.9, sweep: 40, dmg: 0.45, col: '#c890ff', cd: [6, 8], w: 1.4 }, { use: 'shot', mode: 'homing', speed: 230, turn: 2.2, dmg: 0.8, col: '#c890ff', cd: [3.5, 5] }] },
    riftStalker: { name: '时空潜行者', tier: 'normal', arch: 'aggressive', size: [16, 12, 90], speed: 140, elem: 'dark', art: ['stalker', { hue: -50, sat: 1.0, bright: 0.85 }],
      skills: [{ use: 'seq', cd: [5, 7], w: 1.5, steps: [{ use: 'blink', to: 'behind', dist: 70 }, { use: 'swipe', clip: 'scratch', n: 2, reach: 66, dmg: 0.9 }] }, { use: 'swipe', clip: 'bite', reach: 62, dmg: 0.95, cd: [1.6, 2.6], w: 2 }] },
    riftCaster: { name: '时空咏唱者', tier: 'caster', arch: 'kiter', size: [13, 12, 100], elem: 'dark', art: ['voidcaster', { hue: -40, sat: 1.1 }],
      skills: [{ use: 'rain', kind: 'bolt', n: 3, r: 44, windup: 1.1, dmg: 0.95, col: '#c8a0ff', cd: [6, 8], w: 1.5 }, { use: 'shot', mode: 'spread', n: 3, spread: 40, speed: 300, dmg: 0.75, col: '#c8a0ff', cd: [3, 4.5], w: 2 }] },
    riftEcho: { name: '过去的回响', tier: 'elite', arch: 'aggressive', size: [15, 12, 116], scale: 1.15, elem: 'dark', art: ['merkle', { hue: -50, sat: 1.0, bright: 0.85 }], traits: { sa: 'cast' },
      skills: [{ use: 'swipe', n: 3, reach: 90, dmg: 1.05, cd: [1.6, 2.4], w: 2 }, { use: 'mech', mech: { use: 'shield', hp: 0.12, dur: 8, punish: 'heal', col: '#c8a0ff' }, cd: [16, 20], say: '时间停滞' }, { use: 'blink', to: 'behind', dist: 80, cd: [7, 9], w: 0.6 }] },
    riftKeeper: { name: '时空守门人', tier: 'elite', arch: 'guard', size: [17, 13, 120], scale: 1.15, weight: 4, hardness: 40, art: ['gatekeeper', { hue: 170, sat: 0.9, bright: 0.8 }], traits: { sa: 'cast' },
      skills: [{ use: 'guard', dur: 2.4, reduce: 0.85, cd: [6, 8], w: 1.5, counter: { use: 'aoe', shape: 'ring', at: 'self', r: 150, r0: 40, windup: 0.4, dmg: 1.1, col: '#c8a0ff' } }, { use: 'swipe', clip: 'slam', reach: 96, dmg: 1.15, down: true, cd: [2.2, 3.2], w: 2 }] },
  },

  bosses: {
    utara: { name: '兽王乌塔拉', lvl: 56, size: [22, 16, 136], weight: 6, speed: 110, elem: 'fire', art: 'tgUtara', scale: 1.25, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', clip: 'slam', n: 2, reach: 112, width: 34, dmg: 1.15, down: true, cd: [1.8, 2.6], w: 2 },
          { use: 'dash', clip: 'pounce', len: 380, speed: 780, windup: 0.6, dmg: 1.25, cd: [4.5, 6], say: '' },
          { use: 'aoe', clip: 'roar', shape: 'ring', at: 'self', r: 200, r0: 60, windup: 1.2, dmg: 1.1, jump: true, col: '#ff8a3a', cd: [8, 10], say: '兽王的咆哮——跳起来！' },
          { use: 'summon', kind: 'fireGoblin', n: 3, max: 4, cd: [14, 18], w: 0.8, say: '森林的子民，烧起来吧！' }] },
        { at: 0.6, enter: { say: '大火烧到了兽王身上——扑灭火种！火种不灭，它不会受伤！', col: '#ff8a3a', mechs: [{ use: 'invuln', until: 'crystals', kind: 'fireSeed', name: '燃烧的火种', n: 4, hpFrac: 0.02, col: '#ff8a3a' }, { use: 'hazard', kind: 'fire', every: 3.5, n: 2, col: '#ff6a2a' }] },
          skills: [{ use: 'rain', kind: 'hex', n: 5, r: 50, windup: 1.2, dmg: 1.1, col: '#ff6a2a', cd: [8, 10], say: '燃烧的落木' }] },
        { at: 0.25, enter: { say: '格兰之森……是我的！', mechs: [{ use: 'enrage', t: 60, atk: 1.4, speed: 1.2 }] } },
      ] },
    skelKnight: { name: '骷髅骑士', lvl: 56, size: [18, 14, 134], weight: 5, speed: 95, elem: 'dark', art: 'tgSkelKnight', scale: 1.2, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', clip: 'axe', n: 2, reach: 116, width: 34, dmg: 1.15, cd: [1.8, 2.6], w: 2 },
          { use: 'dash', len: 380, speed: 760, windup: 0.7, dmg: 1.25, cd: [5, 7], say: '' },
          { use: 'aoe', shape: 'line', at: 'front', len: 320, hw: 34, windup: 0.9, dmg: 1.15, status: 'poison', col: '#d8e070', cd: [6, 8], say: '腐朽之刃' },
          { use: 'rain', kind: 'hex', n: 4, r: 48, windup: 1.2, dmg: 1.0, status: 'curse', sdur: 2, col: '#c8d070', cd: [9, 12] }] },
        { at: 0.6, enter: { say: '骷髅骑士躲进了瘟疫里——净化三个瘟疫之源，把它逼出来！', col: '#d8e070', mechs: [{ use: 'invuln', until: 'crystals', kind: 'plagueHeart', name: '瘟疫之源', n: 3, hpFrac: 0.025, col: '#d8e070' }] },
          skills: [{ use: 'summon', kind: 'plagueSkel', n: 2, max: 3, cd: [14, 18], say: '起来吧，染疫的士兵们！' }, { use: 'aoe', shape: 'cross', at: 'self', len: 260, hw: 30, windup: 1.0, dmg: 1.1, status: 'poison', col: '#d8e070', cd: [8, 10] }] },
        { at: 0.3, enter: { say: '瘟疫爆发！靠近骷髅骑士，躲进他的死角！', col: '#d8e070', mechs: [{ use: 'safezone', mode: 'near', r: 150, windup: 3.4, frac: 0.4, say: '瘟疫爆发——贴近骷髅骑士！' }] },
          skills: [{ use: 'mech', mech: { use: 'safezone', mode: 'near', r: 150, windup: 3.4, frac: 0.4, say: '瘟疫爆发——贴近骷髅骑士！' }, cd: [22, 28] }] },
      ] },
    belit: { name: '沙影贝利特', lvl: 57, size: [15, 12, 122], speed: 140, art: 'tgBelit', scale: 1.2, pref: 120, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'seq', cd: [5, 7], w: 2, say: '', steps: [{ use: 'blink', to: 'behind', dist: 70 }, { use: 'swipe', n: 3, reach: 80, gap: 0.22, dmg: 0.85 }] },
          { use: 'dash', len: 420, speed: 900, windup: 0.5, dmg: 1.15, cd: [4, 6], w: 1.5 },
          { use: 'shot', clip: 'throw', mode: 'spread', n: 5, spread: 50, speed: 520, dmg: 0.75, cd: [5, 7], say: '飞刀！' },
          { use: 'aoe', shape: 'circle', at: 'target', r: 100, windup: 1.2, dmg: 0.9, status: 'blind', sdur: 2, col: '#e8c890', cd: [8, 10], say: '沙影' }] },
        { at: 0.6, enter: { say: '沙子里全是我的影子——你找得到我吗？', col: '#e8c890', mechs: [{ use: 'clones', n: 3, dur: 12, punish: 'nova' }] },
          skills: [{ use: 'mech', mech: { use: 'clones', n: 3, dur: 12, punish: 'nova' }, cd: [24, 30], say: '沙影分身' }] },
        { at: 0.35, enter: { say: '沙暴来了！场地在缩小！', col: '#e8c890', mechs: [{ use: 'hazard', kind: 'shrink', minW: 700, speed: 22, dur: 0 }] },
          skills: [{ use: 'rain', kind: 'hex', n: 5, r: 48, windup: 1.1, dmg: 1.0, col: '#e8c890', cd: [8, 10], say: '流沙' }] },
      ] },
    nilbas: { name: '尼尔巴斯·格拉西亚', lvl: 57, size: [16, 13, 130], speed: 110, elem: 'dark', art: 'tgNilbas', scale: 1.2, pref: 120, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', n: 3, reach: 112, width: 34, dmg: 1.1, cd: [1.8, 2.6], w: 2 },
          { use: 'dash', len: 400, speed: 820, windup: 0.6, dmg: 1.25, cd: [4.5, 6] },
          { use: 'aoe', shape: 'cross', at: 'target', len: 220, hw: 28, windup: 1.1, dmg: 1.15, col: '#b070ff', cd: [7, 9], say: '混沌十字' },
          { use: 'aoe', shape: 'line', at: 'front', len: 340, hw: 32, windup: 0.8, dmg: 1.1, col: '#b070ff', cd: [6, 8], say: '暗之剑气' }] },
        { at: 0.6, enter: { say: '信徒们在为尼尔巴斯祈祷——先打倒奥兹玛的信徒！', col: '#b070ff', mechs: [{ use: 'invuln', until: 'adds', kind: 'ozmaCultist', n: 4 }] },
          skills: [{ use: 'rain', kind: 'hex', n: 5, r: 50, windup: 1.2, dmg: 1.1, col: '#b070ff', cd: [8, 10] }] },
        { at: 0.3, enter: { say: '……妹妹？不，我已经……回不去了！', col: '#fff0c0', mechs: [{ use: 'safezone', mode: 'zone', n: 2, r: 70, windup: 3.4, frac: 0.4, say: '混沌爆发——站进圣光的光圈！', col: '#fff0c0' }] },
          skills: [{ use: 'mech', mech: { use: 'safezone', mode: 'zone', n: 2, r: 70, windup: 3.4, frac: 0.4, say: '混沌爆发——站进圣光的光圈！', col: '#fff0c0' }, cd: [22, 28] }] },
      ] },
    cerberus: { name: '地狱三头犬', lvl: 58, size: [28, 17, 120], weight: 7, speed: 130, elem: 'fire', art: 'tgCerberus', scale: 1.35, pref: 120, traits: { sa: 'cast', immune: ['stun'] },
      mechs: [{ use: 'groggy', max: 110, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', clip: 'bite', n: 3, reach: 104, width: 36, gap: 0.24, dmg: 0.95, cd: [1.8, 2.6], w: 2, say: '' },
          { use: 'dash', clip: 'pounce', len: 420, speed: 820, windup: 0.6, dmg: 1.25, cd: [4, 6], w: 1.5 },
          { use: 'aoe', shape: 'line', at: 'front', len: 300, hw: 40, windup: 0.9, dmg: 1.15, status: 'burn', col: '#ff6a2a', cd: [6, 8], say: '地狱火吐息' },
          { use: 'summon', kind: 'labHound', n: 2, max: 3, cd: [15, 19], w: 0.8, say: '嗷呜——！' }] },
        { at: 0.6, enter: { say: '三个头一起喷出了地狱火！', col: '#ff6a2a', mechs: [{ use: 'hazard', kind: 'fire', every: 3, n: 3, col: '#ff6a2a' }] },
          skills: [{ use: 'seq', cd: [9, 12], say: '三头连扑！', steps: [{ use: 'dash', clip: 'pounce', len: 360, speed: 820, windup: 0.5, dmg: 1.1 }, { use: 'dash', clip: 'pounce', len: 360, speed: 820, windup: 0.35, dmg: 1.1 }, { use: 'dash', clip: 'pounce', len: 360, speed: 820, windup: 0.35, dmg: 1.1 }] }] },
        { at: 0.3, enter: { say: '试验场的警报响了——防护罩启动！打破它！', col: '#8ad8ff', mechs: [{ use: 'shield', hp: 0.05, dur: 14, punish: 'nova', onBreak: 'groggy', col: '#8ad8ff' }] },
          skills: [{ use: 'mech', mech: { use: 'shield', hp: 0.04, dur: 12, punish: 'nova', onBreak: 'groggy', col: '#8ad8ff' }, cd: [24, 30] }] },
      ] },
    kainPast: { name: '凯恩', lvl: 58, size: [18, 14, 130], weight: 5, speed: 115, elem: 'dark', art: ['wcKain', { hue: -15, sat: 1.25, bright: 0.85 }], scale: 1.55, pref: 110, traits: { sa: 'cast' },
      mechs: [{ use: 'groggy', max: 100, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'swipe', clip: 'axe', n: 2, reach: 124, width: 36, dmg: 1.2, down: true, cd: [2, 2.8], w: 2 },
          { use: 'dash', len: 420, speed: 820, windup: 0.6, dmg: 1.25, cd: [4.5, 6] },
          { use: 'aoe', shape: 'line', at: 'front', len: 360, hw: 34, windup: 0.9, dmg: 1.2, col: '#c05aff', cd: [6, 8], say: '悲鸣之剑' },
          { use: 'seq', cd: [9, 12], steps: [{ use: 'blink', to: 'behind', dist: 80 }, { use: 'aoe', shape: 'circle', at: 'self', r: 140, windup: 0.5, dmg: 1.2 }] }] },
        { at: 0.6, enter: { say: '洞穴在崩塌……这是阿甘左的噩梦！撑住！', col: '#c05aff', mechs: [{ use: 'invuln', until: 'survive', survive: 12 }, { use: 'hazard', kind: 'debris', every: 3, n: 4, col: '#c05aff', dur: 12 }] },
          skills: [{ use: 'summon', kind: 'siroShade', n: 2, max: 3, cd: [14, 18], say: '希洛克的残影……' }] },
        { at: 0.3, enter: { say: '凯恩举起了诅咒之剑！', col: '#c05aff', mechs: [{ use: 'safezone', mode: 'far', r: 240, windup: 3.2, frac: 0.4, say: '诅咒之剑——离凯恩远一点！' }] },
          skills: [{ use: 'mech', mech: { use: 'safezone', mode: 'far', r: 240, windup: 3.2, frac: 0.4, say: '诅咒之剑——离凯恩远一点！' }, cd: [22, 28] }] },
      ] },
    youngSkasa: { name: '年轻的斯卡萨', lvl: 59, size: [26, 16, 120], weight: 7, speed: 90, elem: 'ice', art: ['snSkasa', { hue: 12, sat: 0.85, bright: 1.12 }], scale: 1.1, pref: 140, traits: { sa: 'cast', immune: ['freeze'] },
      mechs: [{ use: 'groggy', max: 110, dur: 6 }],
      phases: [
        { at: 1, skills: [{ use: 'aoe', shape: 'line', at: 'front', len: 320, hw: 42, windup: 0.9, dmg: 1.15, status: 'freeze', sdur: 1, col: '#9ad8ff', cd: [5, 7], w: 1.5, say: '冰之吐息' },
          { use: 'swipe', clip: 'bite', n: 2, reach: 110, width: 36, dmg: 1.15, cd: [2, 2.8], w: 2 },
          { use: 'dash', clip: 'charge', len: 380, speed: 760, windup: 0.7, dmg: 1.25, cd: [5, 7] },
          { use: 'rain', kind: 'hex', n: 5, r: 50, windup: 1.2, dmg: 1.05, status: 'slow', col: '#bfe6ff', cd: [8, 10], say: '冰锥' }] },
        { at: 0.6, enter: { say: '年轻的冰龙张开了冰晶护壁——打破它！', col: '#9ad8ff', mechs: [{ use: 'shield', hp: 0.05, dur: 14, punish: 'heal', onBreak: 'groggy', col: '#9ad8ff' }, { use: 'hazard', kind: 'debris', every: 4, n: 3, col: '#bfe6ff' }] },
          skills: [{ use: 'mech', mech: { use: 'shield', hp: 0.04, dur: 12, punish: 'heal', onBreak: 'groggy', col: '#9ad8ff' }, cd: [24, 30], say: '冰晶护壁' }] },
        { at: 0.3, enter: { say: '暴风雪！离冰龙远一点！', col: '#bfe6ff', mechs: [{ use: 'safezone', mode: 'far', r: 240, windup: 3.2, frac: 0.4, say: '暴风雪——离斯卡萨远一点！' }] },
          skills: [{ use: 'mech', mech: { use: 'safezone', mode: 'far', r: 240, windup: 3.2, frac: 0.4, say: '暴风雪——离斯卡萨远一点！' }, cd: [22, 28] }] },
      ] },
    irisBard: { name: '吟游诗人艾丽丝', tier: 'raid', lvl: 59, power: 0.75, size: [15, 12, 128], weight: 5, speed: 105, elem: 'dark', art: 'tgIris', scale: 1.3, pref: 200, traits: { sa: 'cast', immune: ['stun', 'freeze'] },
      mechs: [{ use: 'groggy', max: 130, dur: 6, mul: 1.6 }, { use: 'enrage', t: 300 }],
      phases: [
        { at: 1, skills: [{ use: 'shot', clip: 'cast', mode: 'homing', n: 3, spread: 60, speed: 240, turn: 2.0, dmg: 0.9, status: 'confuse', sdur: 1.5, cd: [4.5, 6], w: 1.6, say: '迷乱的旋律', col: '#e0a0ff' },
          { use: 'aoe', clip: 'cast', shape: 'ring', at: 'self', r: 180, r0: 60, windup: 1.1, dmg: 1.0, status: 'sleep', sdur: 1.2, cd: [8, 11], say: '安眠曲' },
          { use: 'rain', kind: 'bolt', n: 5, r: 46, windup: 1.1, dmg: 1.05, col: '#c8a0ff', cd: [8, 10], say: '时空的音符' },
          { use: 'blink', to: 'away', dist: 260, cd: [6, 9], w: 0.8 },
          { use: 'summon', kind: 'riftGazer', n: 2, max: 3, cd: [15, 19], w: 0.7 }] },
        { at: 0.65, enter: { say: '哪一个才是真正的我？……', col: '#e0a0ff', mechs: [{ use: 'clones', n: 3, dur: 12, punish: 'heal' }] },
          skills: [{ use: 'mech', mech: { use: 'clones', n: 3, dur: 12, punish: 'heal' }, cd: [24, 30], say: '回响' },
            { use: 'laser', windup: 1.2, dur: 1.2, sweep: 50, dmg: 0.55, col: '#e0a0ff', cd: [8, 10], say: '琴弦' }] },
        { at: 0.35, enter: { say: '艾丽丝躲进了时空的缝隙——击碎时空碎片！', col: '#c8a0ff', mechs: [{ use: 'invuln', until: 'crystals', name: '时空碎片', n: 4, hpFrac: 0.02, col: '#c8a0ff' }] },
          skills: [{ use: 'mech', mech: { use: 'safezone', mode: 'zone', n: 2, r: 70, windup: 3.4, frac: 0.4, say: '终曲——站进光圈！', col: '#e0a0ff' }, cd: [22, 28] }] },
      ] },
  },

  items: {
    epics: [
      { key: 'ep_tg_harp', slot: 'support', lvl: 59, name: '吟游诗人的竖琴', fx: { dmgUp: 0.1, dark: 18, cdr: 0.04 }, desc: '暗黑城的使者艾丽丝弹过的竖琴。弹响它的时候，好像能听见过去的声音。',
        look: 'an ornate small golden lyre harp with dark violet strings, a crescent moon and clock gear motif on the frame, a tiny violet ribbon' },
    ],
    sets: [
      // 深渊专属（时空之门深渊）：本作原创，手镯 + 魔法石两件套
      { id: 'set_timeslip', name: '时空旅者', lvl: 58, abyss: true, desc: '穿过时空之门的旅人留下的东西。它们记得每一个过去。',
        bonus: { 2: { st: { dmgUp: 0.12, cspd: 0.06, aspd: 0.06 }, desc: '【时空】伤害增加 12%，攻击 / 施放速度 +6%；攻击时 6% 几率撕开一道时空裂隙（周围 170% 暗属性伤害）',
          proc: { chance: 0.06, cd: 1.5, act: 'strike', mul: 1.7, aoe: 120, elem: 'dark', vis: 'nova', name: '时空裂隙' } } },
        pieces: [
          { key: 'ep_tg_hourglass', slot: 'bracelet', name: '逆流的沙漏手镯', look: 'a bronze bangle with a tiny hourglass charm whose violet sand flows upward, engraved clock numerals' },
          { key: 'ep_tg_shard', slot: 'stone', name: '过去的碎片', look: 'a jagged violet crystal shard reflecting a tiny burning forest and a snowy peak inside, set in a bronze gear frame' },
        ] },
    ],
  },

  dungeons: {
    grand_fire: { name: '格兰之火', lvl: [55, 56], theme: 'tgFire', layout: 'standard', mobs: [['fireGoblin', 3], ['fireTreant', 1.5], ['fireSpirit', 1.5], ['lavaGolem', 1]], elite: 'fireChief', boss: 'utara', bgm: 'dungeon2', bossBgm: 'boss',
      gate: { scene: 'tg_past_a', x: 520, col: '255,150,90' }, desc: '过去的格兰之森燃起了大火。兽王乌塔拉血量过半后会被大火包住——先扑灭四个燃烧的火种，它才会受伤。“咆哮”读条时跳起来。',
      drops: { boss: [['ep_tg_harp', 0.006]], mats: [['crystal', 0.12, 10], ['c_red', 0.03, 2], ['m_leather', 0.03, 2]] } },
    plague_source: { name: '瘟疫之源', lvl: [55, 56], theme: 'tgPlague', layout: 'standard', mobs: [['plagueGhoul', 3], ['plagueSkel', 2], ['plagueGhost', 1.5], ['plagueSpider', 1.5]], elite: 'plagueHeadless', boss: 'skelKnight', bgm: 'dungeon3', bossBgm: 'boss',
      gate: { scene: 'tg_past_a', x: 1160, col: '220,220,140' }, desc: '暗精灵村庄的瘟疫，是从异次元裂缝里来的。骷髅骑士血量过半后会躲进瘟疫里——净化三个“瘟疫之源”把它逼出来；瘟疫爆发时贴近骷髅骑士。',
      drops: { boss: [['ep_tg_harp', 0.006]], mats: [['crystal', 0.12, 10], ['m_bone', 0.03, 2], ['c_black', 0.02, 1]] } },
    kartel_origin: { name: '卡勒特之初', lvl: [56, 57], theme: 'tgDesert', layout: 'standard', mobs: [['desertBandit', 3], ['youngKartel', 2.5], ['sandSpider', 1.5]], elite: 'desertRider', boss: 'belit', bgm: 'dungeon', bossBgm: 'boss',
      gate: { scene: 'tg_past_a', x: 1800, col: '255,220,150' }, desc: '卡勒特刚成立的时候，西部的无法地带。年轻的沙影贝利特会在沙子里分出影子；沙暴来时场地会缩小，别站在边上。',
      drops: { boss: [['ep_tg_harp', 0.008]], mats: [['crystal', 0.12, 10], ['m_iron', 0.03, 2], ['c_white', 0.02, 1]] } },
    holy_war: { name: '暗黑圣战', lvl: [56, 57], theme: 'tgHoly', layout: 'standard', mobs: [['ozmaCultist', 2.5], ['fallenPaladin', 1.5], ['chaosBeast', 2.5], ['chaosEye', 1.2]], elite: 'chaosPriest', boss: 'nilbas', bgm: 'dungeon2', bossBgm: 'boss',
      gate: { scene: 'tg_past_a', x: 2440, col: '220,200,255' }, desc: '圣职者击退混沌之神奥兹玛之后的战场。格拉西亚家族的小女孩在找她失踪的哥哥——尼尔巴斯。信徒为他祈祷时他会退到后面——先打倒信徒；混沌爆发时站进圣光的光圈。',
      drops: { boss: [['ep_tg_harp', 0.008]], mats: [['crystal', 0.12, 10], ['c_black', 0.03, 2], ['m_elem2', 0.01, 1]] } },
    secret_zone: { name: '绝密区域', lvl: [57, 58], theme: 'bmLab', layout: 'standard', mobs: [['labRobot', 3], ['labIvan', 2], ['labMechTau', 1.2], ['labHound', 2]], elite: 'labWalker', boss: 'cerberus', bgm: 'dungeon', bossBgm: 'boss',
      gate: { scene: 'tg_past_b', x: 520, col: '255,120,110' }, desc: '比尔马克帝国试验场最深处的秘密。地狱三头犬会喷地狱火、连扑三次；警报响起后的防护罩要尽快打破。',
      drops: { boss: [['ep_tg_harp', 0.01]], mats: [['crystal', 0.12, 10], ['m_iron', 0.03, 2], ['m_elem2', 0.01, 1]] } },
    old_wail: { name: '昔日悲鸣', lvl: [57, 58], theme: 'wcCave', layout: 'long', mobs: [['pastLarva', 2.5], ['caveSpider', 2], ['siroShade', 1.5]], elite: 'nightmareBlade', boss: 'kainPast', bgm: 'dungeon3', bossBgm: 'boss',
      gate: { scene: 'tg_past_b', x: 1160, col: '200,120,255' }, desc: '阿甘左的噩梦：当年在悲鸣洞穴和使徒希洛克的对决。凯恩血量过半后洞穴会崩塌——撑过 12 秒；他举起诅咒之剑时离他远一点。',
      drops: { boss: [['ep_tg_harp', 0.01]], mats: [['crystal', 0.12, 10], ['m_bone', 0.03, 2], ['m_soul', 0.003, 1]] } },
    old_winter: { name: '凛冬', lvl: [58, 59], theme: 'snRidge', layout: 'long', mobs: [['pastYeti', 1.5], ['pastTiger', 2.5], ['pastBantu', 2], ['iceWyvern', 1.2]], elite: 'frostApe', boss: 'youngSkasa', bgm: 'dungeon2', bossBgm: 'boss',
      gate: { scene: 'tg_past_b', x: 1800, col: '170,220,255' }, desc: '昔日的万年雪山，冰龙斯卡萨还年轻的时候。冰晶护壁要尽快打破（超时它会回血）；暴风雪时离它远一点。',
      drops: { boss: [['ep_tg_harp', 0.012]], mats: [['crystal', 0.12, 10], ['c_blue', 0.03, 2], ['m_diamond', 0.006, 1]] } },
    iris_raid: { name: '谜之觉悟', lvl: [58, 59], bossLvl: 60, theme: 'tgRift', layout: 'raid', mobs: [['riftGazer', 2], ['riftStalker', 2.5], ['riftCaster', 2], ['riftEcho', 0.4], ['riftKeeper', 0]], elite: 'riftEcho', boss: 'irisBard', bossAdds: 0,
      bgm: 'abyss', bossBgm: 'boss', preBoss: { kind: 'riftKeeper', say: '时空守门人：再往前，就是“她”的舞台了。' },
      gate: { scene: 'tg_past_b', x: 2440, col: '210,160,255' }, desc: '【攻坚】所有线索都指向了暗黑城的使者——吟游诗人艾丽丝。她的歌声会让你迷乱、睡着；她躲进时空缝隙时，击碎四块时空碎片。',
      drops: { boss: [['ep_tg_harp', 0.04]], mats: [['crystal', 0.14, 12], ['m_soul', 0.005, 1], ['m_diamond', 0.012, 1]] } },
  },

  abyss: {
    abyss_timegate: { name: '时空之门深渊', from: 'old_wail', themeFrom: 'tgRift', theme: 'abyssTimegate', tint: 'rgba(60,10,120,0.34)', lvl: [58, 59], lordLvl: 60, cost: 1, pity: 7,
      lords: ['kainPast', 'youngSkasa', 'nilbas'], gate: { scene: 'tg_past_b', x: 2950 }, clearExp: 24000,
      waves: [{ n: 7, mobs: [['riftStalker', 2], ['siroShade', 1], ['pastTiger', 1], ['riftCaster', 1]], elite: 1, say: '过去的影子从裂缝里涌出来了！' }, { elites: ['nightmareBlade', 'frostApe'], say: '噩梦中的剑士和冰原巨猿！' }],
      lord: { mechs: [{ use: 'enrage', t: 220 }], cycle: [{ every: [22, 28], at: 0.8, say: '深渊护盾！', mech: { use: 'shield', hp: 0.05, dur: 12, punish: 'heal', onBreak: 'groggy', col: '#c890ff' } },
        { every: [28, 34], at: 0.5, mech: { use: 'safezone', windup: 3.2, frac: 0.35, say: '深渊之力——站进光圈！' } }] },
      desc: '【深渊派对】时空之门的缝隙里裂开了深渊。需要消耗 1 张深渊派对邀请函。深渊领主是凯恩 / 年轻的斯卡萨 / 尼尔巴斯之一（每次随机）。「时空旅者」只在这里出现。',
      quest: { name: '时空之门的深渊', lvl: 59, clear: 'iris_raid', pre: ['q_abyss_gf', 'q_tg11', 'q_tg12'], gold: 10000, desc: '打倒过凯恩和年轻的斯卡萨之后，再通关一次「谜之觉悟」，歌兰蒂斯就会告诉你时空之门深渊的入口。',
        offer: ['时空之门……连深渊都能连到过去。', '先在过去打倒凯恩、年轻的斯卡萨，再去见一见那个吟游诗人。'],
        done: ['过去的回廊 · 后段的最右边，深渊之门已经打开。'] } },
  },

  npcs: {
    silan: { name: '西岚', title: '剑圣 · 修理 / 仓库', h: 120, services: ['quest', 'repair', 'storage'],
      greet: ['时空之门已经打开了。年轻人，你准备好去看一看过去了吗？'], lines: ['三条龙被放到了阿拉德大陆……背后一定有人。', '答案藏在过去。格兰之森、暗精灵的村子、西部的沙漠……', '阿甘左的噩梦，也在门的另一边。'],
      look: 'Silan, the legendary Sword Saint: a dignified elderly swordmaster with long white hair tied in a topknot and a long white beard, calm sharp eyes, a dark blue and white martial arts robe with a black sash, a long sheathed katana at the waist, hands clasped behind his back' },
  },
  scenes: {
    time_gate: { name: '时空之门', area: '时空之门', kind: 'town', width: 2400, theme: 'tgTown', bgm: 'guild', ambient: 'magic', map: [46, -3],
      props: [{ art: 'world/p_magiclamp', x: 520, h: 110, y: 20 }, { art: 'world/p_magiclamp', x: 1700, h: 110, y: 20 }],
      npcs: [{ npc: 'silan', x: 1150, y: 50 }],
      exits: [{ side: 'down', x: 300, to: 'luft_port' }, { side: 'left', to: 'tg_past_a' }, { side: 'right', to: 'tg_past_b', minLv: 57, label: '过去的回廊 · 后段' }] },
    tg_past_a: { name: '时空之门', area: '过去的回廊 · 前段', kind: 'field', width: 3200, theme: 'tgTown', bgm: 'field', map: [38, -6],
      exits: [{ side: 'right', to: 'time_gate' }] },
    tg_past_b: { name: '时空之门', area: '过去的回廊 · 后段', kind: 'field', width: 3200, theme: 'tgRift', bgm: 'field', map: [54, -6],
      exits: [{ side: 'left', to: 'time_gate' }] },
  },

  story: { chapter: '时空之门篇 · 谜之觉悟', prefix: 'q_tg', pre: 'q_tr09', npc: 'silan', scene: 'time_gate', steps: [
    { t: 'arrive', npc: 'harland', to: 'silan', name: '时空之门', lvl: 55, scene: 'time_gate', reward: { exp: 0.05, gold: 5000 },
      desc: '鲁夫特港的灯塔旁出现了一扇奇怪的门。从海港往上走，穿过时空之门，去找等在那里的剑圣西岚。',
      talk: { offer: ['灯塔那边的光……果然是一扇门。', '有个拿刀的老先生一直站在门口，说在等一个“打倒过卡勒特总指挥的人”。去看看吧。'], doing: ['门在海港往上走，Lv.55 才能过去。'], done: ['你来了。我是西岚。', '三条龙被放到了阿拉德大陆——斯卡萨、希尔德……背后一定有人在推动。答案，藏在过去。'] } },
    { t: 'clear', dungeon: 'grand_fire', name: '格兰之火', lvl: 55, reward: { exp: 0.08, gold: 5000 },
      desc: '穿过时空之门，回到格兰之森燃起大火的那一天。通关「格兰之火」。',
      talk: { offer: ['格兰之森那场大火，精灵们全都消失了。', '回到那一天，看看是谁放的火。'], doing: ['火焰精灵死的时候会爆炸，别贴着打。'], done: ['森林深处，有一头发狂的兽王。'] } },
    { t: 'boss', dungeon: 'grand_fire', name: '兽王乌塔拉', lvl: 56, reward: { exp: 0.09, gold: 6000 },
      desc: '打倒被大火逼疯的兽王乌塔拉。',
      talk: { offer: ['乌塔拉血量过半后，大火会护住它——先扑灭四个燃烧的火种。'], doing: ['“咆哮”读条的时候跳起来。'], done: ['大火里……有人留下了一片紫色的羽毛。', '这羽毛，我在暗精灵的村子里也见过。'] } },
    { t: 'clear', dungeon: 'plague_source', name: '瘟疫之源', lvl: 55, reward: { exp: 0.08, gold: 5000 },
      desc: '暗精灵村庄的瘟疫是从哪里来的？回到过去，通关「瘟疫之源」。',
      talk: { offer: ['暗精灵村庄的瘟疫……据说来自一道异次元裂缝。', '去过去的村子看看。'], doing: ['食尸鬼和蜘蛛都带毒，别被围住。'], done: ['裂缝旁边，站着一个骷髅骑士。'] } },
    { t: 'boss', dungeon: 'plague_source', name: '骷髅骑士', lvl: 56, reward: { exp: 0.09, gold: 6000 },
      desc: '打倒守着瘟疫之源的骷髅骑士。',
      talk: { offer: ['骷髅骑士血量过半后会躲进瘟疫里——净化三个瘟疫之源，把它逼出来。', '瘟疫爆发的时候，贴近它，躲进它的死角。'], doing: [], done: ['瘟疫停下了。裂缝边上……又是那种紫色的羽毛。'] } },
    { t: 'clear', dungeon: 'kartel_origin', name: '卡勒特之初', lvl: 56, reward: { exp: 0.08, gold: 5000 },
      desc: '卡勒特是怎么成立的？回到西部的无法地带，通关「卡勒特之初」。',
      talk: { offer: ['你在天界打过的卡勒特……它刚成立的时候，只是一群沙漠里的亡命之徒。'], doing: ['沙漠骑手扬沙的时候会看不清，别慌。'], done: ['那群人的头领……是一个年轻的刺客。'] } },
    { t: 'boss', dungeon: 'kartel_origin', name: '沙影贝利特', lvl: 57, reward: { exp: 0.1, gold: 6000 },
      desc: '打倒年轻时的沙影贝利特。',
      talk: { offer: ['贝利特会在沙子里分出影子，打中真身影子就散了。', '沙暴来的时候场地会缩小。'], doing: [], done: ['贝利特说，卡勒特成立的那天，有个唱歌的女人来过。'] } },
    { t: 'clear', dungeon: 'holy_war', name: '暗黑圣战', lvl: 56, reward: { exp: 0.08, gold: 5000 },
      desc: '圣职者击退混沌之神奥兹玛之后的战场。通关「暗黑圣战」。',
      talk: { offer: ['暗黑圣战结束以后，有个小女孩一直在找她失踪的哥哥。', '她姓格拉西亚——和诺伊佩拉的格拉西亚家族是同一家。'], doing: ['信徒会给同伴回血，先打他们。'], done: ['战场尽头……那个人，就是她的哥哥。'] } },
    { t: 'boss', dungeon: 'holy_war', name: '尼尔巴斯·格拉西亚', lvl: 57, reward: { exp: 0.1, gold: 6000 },
      desc: '打倒被混沌侵蚀的尼尔巴斯·格拉西亚。',
      talk: { offer: ['尼尔巴斯已经被混沌侵蚀了。', '信徒为他祈祷的时候，先打倒信徒。混沌爆发时站进圣光的光圈。'], doing: [], done: ['他最后说了一个名字……“艾丽丝”。'] } },
    { t: 'boss', dungeon: 'secret_zone', name: '地狱三头犬', lvl: 57, reward: { exp: 0.1, gold: 6000 },
      desc: '比尔马克帝国试验场的最深处，藏着一个秘密。打倒「绝密区域」的地狱三头犬。',
      talk: { offer: ['比尔马克帝国的试验场，你去过吧？最深处还有一扇门。', '里面关着一头三个头的狗。'], doing: ['警报响了以后，它的防护罩要尽快打破。'], done: ['试验记录上写着：“资助人：艾丽丝”。'] } },
    { t: 'boss', dungeon: 'old_wail', name: '凯恩', lvl: 58, reward: { exp: 0.11, gold: 7000 },
      desc: '阿甘左的噩梦：当年在悲鸣洞穴和使徒希洛克的对决。打倒「昔日悲鸣」的凯恩。',
      talk: { offer: ['阿甘左……到现在还会梦见悲鸣洞穴。', '那天，他和使徒希洛克交过手。凯恩是守在洞口的骷髅剑士。'], doing: ['洞穴崩塌的时候撑住 12 秒。'], done: ['噩梦散了。……希洛克的影子里，也有那个唱歌的女人。'] } },
    { t: 'boss', dungeon: 'old_winter', name: '年轻的斯卡萨', lvl: 58, reward: { exp: 0.11, gold: 7000 },
      desc: '冰龙斯卡萨还年轻的时候，昔日的万年雪山。打倒「凛冬」的年轻的斯卡萨。',
      talk: { offer: ['三条龙里的斯卡萨，你在万年雪山打倒过。', '去看看它年轻的时候——是谁把它从沉睡里叫醒的。'], doing: ['冰晶护壁超时它会回血。'], done: ['冰龙的记忆里……有一首歌。唱歌的人，是暗黑城的使者。'] } },
    { t: 'raid', dungeon: 'iris_raid', name: '吟游诗人艾丽丝', lvl: 59, reward: { exp: 0.16, gold: 10000, coins: 2 },
      desc: '所有的线索都指向同一个人——暗黑城的使者，吟游诗人艾丽丝。打倒她。',
      talk: { offer: ['羽毛、瘟疫、卡勒特、三条龙……全都是她。', '艾丽丝的歌声会让你迷乱、睡着。她躲进时空缝隙时，击碎四块时空碎片。'], doing: ['时空守门人在她的舞台前面。'], done: ['艾丽丝消失前笑着说：“魔界的第五使徒，正在等你哦。”'] } },
    { t: 'handin', to: 'silan', name: '谜之觉悟', lvl: 59, reward: { exp: 0.08, gold: 8000, items: [{ key: 'ep_tg_harp', n: 1 }] },
      desc: '回时空之门，把艾丽丝留下的话告诉西岚。',
      talk: { offer: ['艾丽丝……消失了。'], done: ['这把竖琴留在了她的舞台上——拿去吧。', '魔界的第五使徒……潜行者希洛克。阿甘左的妻子卢克西，就是被她带走的。', '等你到了 Lv.60，从时空之门往上走，穿过次元裂缝，去魔界找阿甘左。', '——时空之门篇 · 完——'] } },
  ] },

  art: {
    chars: {
      tgUtara: { h: 136, boss: true, hold: 'holding a giant bone and stone war club', desc: 'Utara the Beast King, lord of the Grand Flores forest and a menacing boss: a huge hulking beast-man with the head of a snarling lion-boar with big curved tusks, a thick dark brown mane, a muscular body covered in dark fur with red tribal war paint, a necklace of big fangs and bones, rough leather and wooden plate armor, a torn loincloth, clawed feet, holding a giant bone and stone war club. Savage, roaring and fierce.',
        atk: 'the giant war club smashed down', cast: 'beating its chest and roaring', low: 'charging forward low on all fours' },
      tgSkelKnight: { h: 134, boss: true, hold: 'holding a large rusted halberd and a round shield', desc: 'The Skeleton Knight guarding the source of the plague, a menacing boss: a tall undead skeleton knight in corroded dull bronze plate armor tinged with olive rot, a tattered moss-brown cape, a cracked skull with glowing pale yellow eye lights inside a pointed open helm with a broken plume, holding a large rusted halberd and a round shield with a rotten skull emblem. Dreadful and fierce.',
        atk: 'the halberd swung in a wide arc', cast: 'raising the halberd as the eye lights flare', low: 'lunging forward low with the halberd' },
      tgBelit: { h: 122, boss: true, hold: 'holding two curved daggers', desc: 'Belit the Sand Shadow in his youth, a founding member of the Kartel and a menacing boss: a lean agile desert assassin in his early twenties with a menacing glare, narrowed sharp amber eyes, furrowed brows and a cruel sneer showing his teeth, a scar on the cheek, dark tan skin, a sand-colored hooded scarf wrapped over the lower face, layered desert cloth armor with leather straps and a red sash, bandaged forearms, holding two curved daggers in reverse grip. Deadly, hostile and fierce, clearly a villain.',
        atk: 'both curved daggers slashing', cast: 'crossing the daggers in front of the face', low: 'dashing forward low with both daggers' },
      tgNilbas: { h: 130, boss: true, holes: false, outline: '#2a1a3a', hold: 'holding a huge black greatsword', desc: 'Nilbas Gracia, the lost elder brother of the Gracia family corrupted during the Dark Holy War, a menacing boss: a tall young dark elf knight with dark grey skin, long white hair and long pointed ears, glowing red eyes and a furious anguished expression, black and violet plate armor engraved with a tusked boar crest, a torn dark cape, holding a huge black greatsword with violet rune engravings. Tragic, corrupted and fierce.',
        atk: 'the black greatsword swung down', cast: 'raising the greatsword overhead with a furious shout', low: 'charging forward low with the greatsword' },
      tgCerberus: { h: 120, boss: true, hold: null, cycle: 'trot', desc: 'Cerberus, the hellhound locked in the deepest secret area of the Bilmark Empire test site, a menacing boss: a huge four-legged dog monster with three snarling heads side by side, sharp fangs and glowing red eyes, dark charcoal fur with steel armor plates bolted onto the back and legs, heavy iron collars with broken chains and experiment number tags, big claws and a spiked tail. Ferocious.',
        atk: 'all three heads biting forward', cast: 'rearing up with all three heads howling', low: 'crouching low ready to pounce' },
      tgIris: { h: 128, boss: true, hold: 'holding an ornate golden lyre harp', desc: 'Iris the Bard, the mysterious envoy of the Dark City behind every clue and a menacing raid boss: a slender elegant woman with long wavy lavender hair, pale skin, wide-open piercing violet eyes with a cold menacing stare and a sinister crooked smirk, dark plum lipstick, a long modest dark violet and black gothic dress with a high collar and gold trims, a wide feathered bard hat, holding an ornate golden lyre harp with dark strings. Beautiful but clearly a sinister, threatening villain, not cute.',
        atk: 'the lyre swung like a blade', cast: 'playing the lyre with eyes closed', low: 'gliding forward low with the lyre held out' },
    },
    gates: {
      grand_fire: 'a charred wooden forest archway with burnt leaves and a white stone elf shrine, an orange-red portal',
      plague_source: 'a dark elf cave entrance with plague warning cloth banners and bones, a pale olive-yellow portal',
      kartel_origin: 'a desert frontier outpost gate of wooden logs with a crude Kartel flag and a cow skull, a sandy gold portal',
      holy_war: 'a ruined cathedral doorway with broken stained glass and a toppled saint statue, a pale white-violet portal',
      secret_zone: 'a heavy steel blast door of the Bilmark test site with hazard stripes and a TOP SECRET plate, a red portal',
      old_wail: 'a dark wailing cave mouth with stalactites and scattered bones, a deep violet portal',
      old_winter: 'an icy mountain pass gate of snow-covered stone with icicles and an old tribal banner, an icy blue portal',
      iris_raid: 'an ornate old theater stage gate with heavy violet curtains, broken clock gears and a golden lyre emblem, a dark violet portal',
    },
  },
});
