/* =====================================================================
   希洛克攻坚战 · RA4 节点地下城
   每个节点使用独立主题、专属小怪和专属领主；规则核心仍在 raid_core.js。
   ===================================================================== */
const SIROCO_RAID_SPEC = { id: 'sirocoRaid', lvl: 63, power: 1.12, bossPower: 1.2, atkPower: 1.08 };
regionTheme('siroRaidMirror', { grade: { tint: 'rgba(40,170,200,0.13)', fog: 'rgba(90,220,255,0.1)' }, ambient: 'motes', rgb: '110,220,255', pal: { sky: ['#061d2b', '#0b4a5c', '#16849a'], far: '#03121b', haze: '#58ddf0', floor: ['#092d3b', '#0d5361', '#061d2b'], line: 'rgba(120,240,255,.5)' } });
regionTheme('siroRaidCoffin', { grade: { tint: 'rgba(170,50,190,0.16)', fog: 'rgba(230,120,255,0.1)' }, ambient: 'wisps', rgb: '220,120,255', pal: { sky: ['#16051f', '#42135c', '#812b95'], far: '#0b0312', haze: '#e078ff', floor: ['#25102f', '#4b1d58', '#1b0925'], line: 'rgba(236,130,255,.48)' } });
regionTheme('siroRaidGate', { grade: { tint: 'rgba(220,155,40,0.13)', fog: 'rgba(255,210,90,0.08)' }, ambient: 'motes', rgb: '255,205,110', pal: { sky: ['#211306', '#5c3410', '#a56a1b'], far: '#120a03', haze: '#ffd36a', floor: ['#38220c', '#674116', '#241407'], line: 'rgba(255,220,130,.48)' } });
// 官方小怪：被侵蚀的格里姆希克教徒系（一般教徒 / 战士 / 上级教徒，잠식된 그림시커 일반신도·전사·상급신도 [NAMU-DG][NAMU-LAW]）+ 希洛克的碎片（P2 第 1 界 [SR-P2]【存疑】）。
// 公开资料只写了“血量低、基本无威胁”[YW-忆][91-破]，没有技能表：招式是按定位补的占位（docs/RAID_SIROCO.md §小怪）。
const SIROCO_RAID_MOB_DEFS = {
  siRaidMob_grimFollower: { name: '被侵蚀的格里姆希克一般教徒', tier: 'swarm', arch: 'swarm', size: [13, 11, 92], elem: 'dark', art: ['voidcaster', { hue: -60, sat: 0.9, bright: 0.72 }], skills: [{ use: 'swipe', n: 2, reach: 70, dmg: 0.8, cd: [1.6, 2.4] }, { use: 'shot', mode: 'spread', n: 2, spread: 30, speed: 260, dmg: 0.7, cd: [3.5, 5] }] },
  siRaidMob_grimWarrior: { name: '被侵蚀的格里姆希克战士', arch: 'aggressive', size: [17, 14, 108], weight: 2, elem: 'dark', art: ['jailer', { hue: -80, sat: 0.85, bright: 0.74 }], skills: [{ use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.6, dmg: 1.15, cd: [2.2, 3.2] }, { use: 'dash', len: 280, speed: 640, windup: 0.65, dmg: 1, cd: [4, 6] }] },
  siRaidMob_grimElder: { name: '被侵蚀的格里姆希克上级教徒', tier: 'caster', arch: 'kiter', elem: 'dark', art: ['archbishop', { hue: -50, sat: 0.9, bright: 0.75 }], skills: [{ use: 'mark', delay: 0.9, r: 60, dmg: 1, cd: [5, 7] }, { use: 'buff', kind: 'shield', target: 'allies', r: 240, amt: 0.1, dur: 6, cd: [11, 15] }, { use: 'shot', mode: 'homing', n: 2, speed: 230, turn: 2.2, dmg: 0.8, cd: [3.5, 5] }] },
  siRaidMob_sirocoShard: { name: '希洛克的碎片', tier: 'swarm', arch: 'swarm', size: [11, 10, 60], scale: 0.8, elem: 'dark', art: ['siPhantom', { hue: 140, sat: 0.8, bright: 0.8 }], skills: [{ use: 'seq', cd: [5, 7], steps: [{ use: 'blink', to: 'behind', dist: 54 }, { use: 'swipe', n: 2, reach: 56, dmg: 0.72 }] }, { use: 'explode', r: 74, windup: 0.8, dmg: 1.1, cd: [6, 8] }] },
  // 破坏之门 ③ 号房的精英「门」[91-破][NAMU-LAW]：不断召唤教徒（P3 接炮台充能 / 召唤时无敌）
  siRaidMob_gate: { name: '门', tier: 'elite', arch: 'guard', size: [26, 18, 150], weight: 9, speed: 0, noGrab: true, elem: 'dark', art: ['gatekeeper', { hue: -100, sat: 0.6, bright: 0.6 }], skills: [{ use: 'summon', kind: 'siRaidMob_grimFollower', n: 2, max: 6, lvlOff: -1, cd: [7, 9] }, { use: 'laser', windup: 1, dur: 0.9, sweep: 0, dmg: 0.5, cd: [6, 8] }, { use: 'mark', delay: 1, r: 70, dmg: 1.1, cd: [7, 9] }] },
};
for (const [id, M] of Object.entries(SIROCO_RAID_MOB_DEFS)) regionMonster(SIROCO_RAID_SPEC, id, M, false);
// 领主模板：两阶段（100% / 50%），没有通用破招槽 / 狂暴（官方的虚弱只来自各自的机制，P3 由 raid_mech 脚本接管）
const raidBoss = (id, name, art, elem, first, second, extra = {}) => regionMonster(SIROCO_RAID_SPEC, id, { name, lvl: extra.lvl || 64, size: extra.size || [18, 15, 126], speed: extra.speed || 100, scale: extra.scale ?? 0.92, elem, art, hook: extra.hook, mechs: extra.mechs || [], phases: [{ at: 1, skills: first }, { at: 0.5, enter: extra.enter || { say: `${name}进入第二阶段！` }, skills: second }] }, true);
raidBoss('siRaidBoss_gatekeeper', '遗忘姓名的守门人', 'gatekeeper', 'light', [{ use: 'pull', clip: 'sigA', mode: 'in', r: 320, force: 300, dur: 1, windup: 0.8, dmg: 0.4, cd: [8, 11] }, { use: 'swipe', clip: 'sigB', n: 3, reach: 120, width: 34, windup: 0.6, dmg: 1.15, cd: [3, 4.5] }, { use: 'aoe', clip: 'charge', shape: 'ring', at: 'self', r: 230, r0: 90, windup: 1, dmg: 1.2, down: true, cd: [8, 10] }], [{ use: 'dash', clip: 'sigA', len: 360, speed: 690, windup: 0.8, dmg: 1.25, cd: [7, 9] }, { use: 'aoe', clip: 'sigB', shape: 'circle', at: 'self', r: 200, windup: 1.2, dmg: 1.3, cd: [9, 11] }], { scale: 0.84 });
raidBoss('siRaidBoss_haniel', '魅惑之哈妮尔', 'sirocoRaidMimic', 'dark', [{ use: 'shot', clip: 'sigA', mode: 'straight', n: 1, speed: 520, dmg: 1.05, cd: [4, 6] }, { use: 'aoe', clip: 'sigB', shape: 'circle', at: 'self', r: 150, windup: 0.9, dmg: 1.2, cd: [7, 9] }, { use: 'dash', clip: 'sigA', len: 300, speed: 700, windup: 0.6, dmg: 1.1, cd: [6, 8] }], [{ use: 'aoe', clip: 'rage', shape: 'ring', at: 'self', r: 300, r0: 120, windup: 1, dmg: 1.15, cd: [8, 10] }, { use: 'swipe', clip: 'sigB', n: 4, reach: 96, dmg: 1.05, cd: [4, 6] }], { scale: 0.78 });
raidBoss('siRaidBoss_lena', '魔弹持有者蕾娜', 'sirocoRaidFrost', 'dark', [{ use: 'rain', clip: 'sigA', kind: 'bolt', n: 5, r: 50, spread: 190, windup: 1, dmg: 1.05, cd: [7, 9] }, { use: 'shot', clip: 'sigB', mode: 'spread', n: 6, spread: 60, speed: 340, dmg: 0.8, cd: [4, 6] }, { use: 'mark', clip: 'atk1', delay: 1.1, r: 70, dmg: 1.2, cd: [8, 10] }], [{ use: 'shot', clip: 'sigA', mode: 'straight', n: 3, speed: 620, dmg: 1.1, cd: [6, 8] }, { use: 'rain', clip: 'sigB', kind: 'bolt', n: 7, r: 46, spread: 220, windup: 1.1, dmg: 1.1, cd: [8, 10] }], { scale: 0.78 });
raidBoss('siRaidBoss_gusty', '灭食之古斯迪', 'sirocoRaidGorge', 'dark', [{ use: 'pull', clip: 'sigA', mode: 'out', r: 240, force: 300, dur: 0.8, windup: 0.6, dmg: 0.6, cd: [8, 11] }, { use: 'leap', clip: 'sigB', r: 110, dmg: 1.25, cd: [6, 8] }, { use: 'rain', clip: 'atk1', kind: 'hex', n: 5, r: 52, spread: 180, windup: 1, dmg: 1.05, cd: [7, 9] }], [{ use: 'pull', clip: 'rage', mode: 'in', r: 320, force: 300, dur: 1.2, windup: 0.9, dmg: 0.5, cd: [10, 13] }, { use: 'mark', clip: 'sigA', delay: 1, r: 64, dmg: 0.9, status: 'slow', cd: [8, 10] }], { scale: 0.86 });
raidBoss('siRaidBoss_grumi', '飘荡的咕噜米', 'sirocoRaidCinder', 'light', [{ use: 'shot', clip: 'sigA', mode: 'spread', n: 5, spread: 48, speed: 300, dmg: 0.72, cd: [4, 6] }, { use: 'rain', clip: 'sigB', kind: 'bolt', n: 5, r: 54, spread: 180, windup: 1.1, dmg: 1.1, cd: [7, 9] }], [{ use: 'shot', clip: 'sigA', mode: 'spread', n: 9, spread: 160, speed: 260, dmg: 0.7, cd: [5, 7] }, { use: 'laser', clip: 'sigB', windup: 0.8, dur: 1.2, sweep: 90, dmg: 0.42, cd: [7, 9] }], { scale: 0.8 });
raidBoss('siRaidBoss_vita', '慈悲之维塔', 'sirocoRaidDawn', 'light', [{ use: 'pool', clip: 'sigA', at: 'target', r: 90, windup: 1, linger: 4, zone: 'slow', dmg: 0.3, cd: [7, 9] }, { use: 'rain', clip: 'sigB', kind: 'bolt', n: 6, r: 44, spread: 200, windup: 0.9, dmg: 1.05, cd: [7, 9] }, { use: 'dash', clip: 'atk1', len: 380, speed: 760, windup: 0.7, dmg: 1.15, cd: [6, 8] }], [{ use: 'lanes', clip: 'sigA', kind: 'bolt', lanes: 5, hit: 3, windup: 0.85, dmg: 1.1, cd: [8, 10] }], { scale: 0.82 });
raidBoss('siRaidBoss_nex', '公义之奈克斯', 'sirocoRaidEclipse', 'dark', [{ use: 'aoe', clip: 'atk1', shape: 'line', at: 'target', hw: 30, windup: 0.8, dmg: 1.2, cd: [4, 6] }, { use: 'swipe', clip: 'sigA', n: 3, reach: 120, dmg: 1.15, cd: [3, 4.5] }, { use: 'pull', clip: 'sigB', mode: 'in', r: 300, force: 280, dur: 1, windup: 0.8, dmg: 0.4, cd: [8, 11] }], [{ use: 'rain', clip: 'sigA', kind: 'bolt', n: 5, r: 50, windup: 1, dmg: 1.15, cd: [7, 9] }], { scale: 0.82 });
raidBoss('siRaidBoss_nightmare', '惊悸梦魇', 'sirocoRaidNightmare', 'dark', [{ use: 'blink', clip: 'sigA', to: 'behind', dist: 100, cd: [5, 7] }, { use: 'aoe', clip: 'sigB', shape: 'cross', at: 'self', hw: 26, windup: 1, dmg: 1.2, cd: [7, 9] }, { use: 'rain', clip: 'rage', kind: 'bolt', n: 6, r: 50, spread: 200, windup: 0.9, dmg: 1.05, cd: [8, 10] }], [{ use: 'aoe', clip: 'sigA', shape: 'circle', at: 'self', r: 220, windup: 1.3, dmg: 1.35, cd: [10, 12] }], { scale: 0.8 });
raidBoss('siRaidBoss_phantom', '无形之希洛克', 'sirocoRaidPhantom', 'dark', [{ use: 'aoe', clip: 'sigA', shape: 'line', at: 'target', hw: 34, windup: 0.9, dmg: 1.2, cd: [5, 7] }, { use: 'seq', clip: 'atk1', cd: [8, 11], steps: [{ use: 'blink', to: 'behind', dist: 90 }, { use: 'swipe', n: 2, reach: 110, dmg: 1.2 }] }, { use: 'pool', clip: 'sigB', at: 'target', r: 80, windup: 0.9, linger: 3, zone: 'blind', dmg: 0.3, cd: [7, 9] }], [{ use: 'rain', clip: 'sigA', kind: 'bolt', n: 5, r: 50, spread: 160, windup: 0.9, dmg: 1.05, cd: [8, 10] }], { scale: 0.74 });
raidBoss('siRaidBoss_crone', '梦魇之沃德海格', 'sirocoRaidOracle', 'dark', [{ use: 'laser', clip: 'sigA', windup: 0.9, dur: 1, sweep: 0, dmg: 0.45, cd: [5, 7] }, { use: 'shot', clip: 'sigB', mode: 'homing', n: 3, speed: 240, turn: 2.2, dmg: 0.85, cd: [4, 6] }, { use: 'rain', clip: 'rage', kind: 'bolt', n: 5, r: 50, spread: 180, windup: 1, dmg: 1, cd: [8, 10] }], [{ use: 'cone', clip: 'sigA', ang: 60, len: 300, windup: 1, dur: 1.2, dmg: 0.4, col: '#8aff9a', cd: [7, 9] }], { scale: 0.8 });
raidBoss('siRaidBoss_siroco', '无形之希洛克', 'sirocoRaidFinal', 'dark', [{ use: 'swipe', clip: 'sigA', n: 4, reach: 128, width: 38, windup: 0.55, dmg: 1.32, cd: [2.4, 3.6] }, { use: 'shot', clip: 'sigB', mode: 'arc', n: 4, speed: 300, spread: 120, r: 72, dmg: 0.86, cd: [5, 7] }], [{ use: 'laser', clip: 'sigA', windup: 0.8, dur: 1.6, sweep: 110, dmg: 0.48, cd: [7, 9] }, { use: 'rain', clip: 'sigB', kind: 'bolt', n: 7, r: 50, spread: 220, windup: 0.9, dmg: 1.15, cd: [8, 10] }], { lvl: 64, scale: 0.76, size: [24, 18, 154], speed: 108 });
// ---- 阻截战补全的图（P1 全图）：幻影之界 / 归还之昼 / 幻影之城；讨伐战第 1 界：否定 / 压抑 / 忘却 / 真理之棺 ×3 / 阴影之棺。招式是占位，机制在 raid_mech（P2/P3） ----
raidBoss('siRaidBoss_kulaTanna', '崔拉 & 昙娜', ['sirocoRaidMimic', { hue: 150, sat: 0.9 }], 'dark', [{ use: 'seq', clip: 'atk1', cd: [6, 8], steps: [{ use: 'blink', to: 'behind', dist: 90 }, { use: 'swipe', n: 2, reach: 104, dmg: 1.1 }] }, { use: 'shot', clip: 'sigA', mode: 'spread', n: 4, spread: 50, speed: 360, dmg: 0.8, cd: [4, 6] }], [{ use: 'aoe', clip: 'sigB', shape: 'cross', at: 'self', hw: 26, windup: 1, dmg: 1.2, cd: [7, 9] }], { scale: 0.78 });
raidBoss('siRaidBoss_myungho', '万兽之皇明皓', ['jailer', { hue: 40, sat: 1.1, bright: 0.9 }], 'fire', [{ use: 'dash', len: 420, speed: 760, windup: 0.7, dmg: 1.2, cd: [5, 7] }, { use: 'leap', r: 120, dmg: 1.25, cd: [7, 9] }, { use: 'swipe', n: 3, reach: 110, width: 34, dmg: 1.1, cd: [3, 4.5] }], [{ use: 'aoe', shape: 'ring', at: 'self', r: 260, r0: 100, windup: 1, dmg: 1.2, cd: [8, 10] }], { scale: 1.05, size: [22, 16, 136] });
raidBoss('siRaidBoss_rodos', '破坏之洛多斯', ['gatekeeper', { hue: 150, sat: 0.8, bright: 0.8 }], 'dark', [{ use: 'swipe', n: 2, reach: 120, width: 36, windup: 0.7, dmg: 1.2, cd: [3, 4.5] }, { use: 'aoe', shape: 'line', at: 'target', hw: 30, windup: 0.9, dmg: 1.2, cd: [6, 8] }], [{ use: 'leap', r: 120, dmg: 1.3, cd: [7, 9] }], { scale: 0.8 });
raidBoss('siRaidBoss_nightmare2', '惊悸梦魇', ['sirocoRaidNightmare', { hue: 40 }], 'dark', [{ use: 'blink', clip: 'sigA', to: 'behind', dist: 100, cd: [5, 7] }, { use: 'aoe', clip: 'sigB', shape: 'cross', at: 'self', hw: 26, windup: 1, dmg: 1.2, cd: [7, 9] }], [{ use: 'rain', clip: 'sigA', kind: 'bolt', n: 6, r: 48, spread: 200, windup: 1, dmg: 1.1, cd: [8, 10] }]);
raidBoss('siRaidBoss_kain', '迷雾中的暗杀者凯恩', ['assassin', { hue: -40, sat: 0.9 }], 'dark', [{ use: 'seq', cd: [6, 8], steps: [{ use: 'blink', to: 'behind', dist: 70 }, { use: 'swipe', n: 2, reach: 90, windup: 0.3, dmg: 1.0 }] }, { use: 'dash', len: 400, speed: 780, windup: 0.7, dmg: 1.2, cd: [5, 7] }], [{ use: 'pool', at: 'target', r: 90, windup: 0.9, linger: 4, zone: 'blind', dmg: 0.3, cd: [8, 10] }], { scale: 0.92 });
raidBoss('siRaidBoss_luxi', '卢克西', ['sirocoRaidOracle', { hue: 120 }], 'dark', [{ use: 'shot', clip: 'sigB', mode: 'homing', n: 3, speed: 240, turn: 2.2, dmg: 0.85, cd: [4, 6] }, { use: 'laser', clip: 'sigA', windup: 0.9, dur: 1, sweep: 40, dmg: 0.45, cd: [6, 8] }], [{ use: 'rain', clip: 'sigA', kind: 'hex', n: 5, r: 50, spread: 180, windup: 1, dmg: 1.05, cd: [7, 9] }], { scale: 0.8 });
// 真理的意识之棺的三个形态（共享血量）：基里（无言）/ 莱斯特（无念）/ 拉维茜（无我）[QQ][NAMU-C1]
raidBoss('siRaidBoss_formGiri', '无言之希洛克-基里', ['siroco', { hue: 200, sat: 0.8 }], 'dark', [{ use: 'swipe', n: 3, reach: 120, width: 36, windup: 0.6, dmg: 1.2, cd: [3, 4.5] }, { use: 'aoe', shape: 'line', at: 'target', hw: 34, windup: 0.9, dmg: 1.2, cd: [5, 7] }], [{ use: 'rain', kind: 'bolt', n: 5, r: 50, spread: 180, windup: 1, dmg: 1.1, cd: [8, 10] }], { scale: 1.2 });
raidBoss('siRaidBoss_formLester', '无念之希洛克-莱斯特', ['siroco', { hue: 90, sat: 0.8 }], 'dark', [{ use: 'shot', mode: 'spread', n: 5, spread: 60, speed: 330, dmg: 0.85, cd: [4, 6] }, { use: 'pull', mode: 'in', r: 300, force: 280, dur: 1, windup: 0.8, dmg: 0.4, cd: [8, 11] }], [{ use: 'aoe', shape: 'ring', at: 'self', r: 280, r0: 110, windup: 1, dmg: 1.2, cd: [8, 10] }], { scale: 1.2 });
raidBoss('siRaidBoss_formLavicy', '无我之希洛克-拉维茜', ['siroco', { hue: -40, sat: 0.9 }], 'dark', [{ use: 'dash', len: 380, speed: 760, windup: 0.7, dmg: 1.2, cd: [5, 7] }, { use: 'aoe', shape: 'cross', at: 'self', hw: 28, windup: 1, dmg: 1.2, cd: [7, 9] }], [{ use: 'laser', windup: 0.9, dur: 1.2, sweep: 80, dmg: 0.45, cd: [7, 9] }], { scale: 1.2 });
// 跨图惩罚召唤的怪（raid_pen 在对方的图里刷）：高血量幻影（幻影之界）/ 玄武（归还之昼 → 黎明）/ 伪装者（归还之昼 → 幻影之界）[QQ][91-界]
const SIROCO_RAID_PEN_MOBS = {
  siRaidMob_phantomAdd: { name: '幻影', tier: 'brute', arch: 'aggressive', size: [15, 12, 100], weight: 3, elem: 'dark', art: ['siPhantom', { hue: -30, sat: 1.1, bright: 0.9 }], skills: [{ use: 'swipe', n: 2, reach: 86, dmg: 0.9, cd: [2, 3] }] },
  siRaidMob_genbu: { name: '玄武', tier: 'brute', arch: 'guard', size: [22, 18, 96], weight: 6, speed: 50, elem: 'water', art: ['jailer', { hue: 140, sat: 0.9, bright: 0.8 }], skills: [{ use: 'aoe', shape: 'circle', at: 'self', r: 130, windup: 1.1, dmg: 1.1, cd: [5, 7] }] },
  siRaidMob_disguiser: { name: '伪装者', arch: 'kiter', elem: 'dark', art: ['voidcaster', { hue: 60, sat: 0.9, bright: 0.85 }], skills: [{ use: 'shot', mode: 'straight', n: 1, speed: 420, dmg: 0.8, cd: [3, 4.5] }] },
  siRaidMob_kula: { name: '崔拉', tier: 'elite', arch: 'aggressive', size: [16, 13, 108], elem: 'dark', art: ['siPhantom', { hue: 150, sat: 1 }], skills: [{ use: 'dash', len: 320, speed: 700, windup: 0.7, dmg: 1, cd: [4, 6] }] },
  siRaidMob_tanna: { name: '昙娜', tier: 'elite', arch: 'kiter', size: [16, 13, 108], elem: 'dark', art: ['siPhantom', { hue: -150, sat: 1 }], skills: [{ use: 'shot', mode: 'spread', n: 3, spread: 40, speed: 340, dmg: 0.8, cd: [3, 5] }] },
};
for (const [id, M] of Object.entries(SIROCO_RAID_PEN_MOBS)) regionMonster(SIROCO_RAID_SPEC, id, M, false);
Object.assign(MON_ART, {
  siRaidBoss_gatekeeper: ['gatekeeper'], siRaidBoss_haniel: ['sirocoRaidMimic'],
  siRaidBoss_lena: ['sirocoRaidFrost'], siRaidBoss_gusty: ['sirocoRaidGorge'], siRaidBoss_grumi: ['sirocoRaidCinder'],
  siRaidBoss_vita: ['sirocoRaidDawn'], siRaidBoss_nex: ['sirocoRaidEclipse'], siRaidBoss_nightmare: ['sirocoRaidNightmare'],
  siRaidBoss_phantom: ['sirocoRaidPhantom'], siRaidBoss_crone: ['sirocoRaidOracle'], siRaidBoss_siroco: ['sirocoRaidFinal'],
  siRaidBoss_kulaTanna: ['sirocoRaidMimic'], siRaidBoss_myungho: ['jailer'], siRaidBoss_rodos: ['gatekeeper'], siRaidBoss_nightmare2: ['sirocoRaidNightmare'],
  siRaidBoss_kain: ['assassin'], siRaidBoss_luxi: ['sirocoRaidOracle'], siRaidBoss_formGiri: ['siroco'], siRaidBoss_formLester: ['siroco'], siRaidBoss_formLavicy: ['siroco'],
});
const SIROCO_RAID_COMMON = { raid: true, hidden: true, layout: 'raid', branches: 0, cols: 5, rows: 1, rooms: 5, bossAdds: 0, lvl: [62, 63], clearExp: 0, bgm: 'dungeon', bossBgm: 'boss' };
const SIROCO_RAID_MOBS = {
  cult: [['siRaidMob_grimFollower', 3], ['siRaidMob_grimWarrior', 2], ['siRaidMob_grimElder', 1]],
  gate: [['siRaidMob_grimFollower', 3], ['siRaidMob_grimWarrior', 2]],   // 「门」召唤的就是这两种 [NAMU-LAW]
  coffin: [['siRaidMob_grimFollower', 2], ['siRaidMob_grimWarrior', 2], ['siRaidMob_grimElder', 1.5], ['siRaidMob_sirocoShard', 1]],
  shard: [['siRaidMob_sirocoShard', 3], ['siRaidMob_grimElder', 1]],
};
// 官方固定房间结构（docs/RAID_SIROCO.md §地图）：line(n) = 一条直线 n 个房间，第一个是准备房（不刷怪），最后一个是领主房
const siLine = (n, o = {}) => ({ cols: n, rows: 1, rooms: Array.from({ length: n }, (_, i) => ({ at: [o.rtl ? n - 1 - i : i, 0], ...(i === 0 ? { prep: true } : {}), ...(i === n - 1 ? { type: 'boss' } : {}), ...((o.rooms || {})[i] || {}) })), start: 0, boss: n - 1 });
const SIROCO_RAID_LAYOUT = {
  law: siLine(5, { rooms: { 2: { type: 'elite', elite: 'siRaidMob_gate', name: '门' } } }),   // 准备 / 小怪 / 门 / 小怪 / 守门人 [91-破]
  dawn: siLine(5),   // 准备 + 3 小怪 + 哈妮尔 [233-黎]
  // 噩梦之夜：5×2 共 10 房，随机出生在四角（1 / 5 / 6 / 10，空房），领主随机在 2 / 3 / 4 / 7 / 8 / 9 之一 [91-夜]
  night: { cols: 5, rows: 2, links: 'grid', hideBoss: true, rooms: Array.from({ length: 10 }, (_, i) => ({ at: [i % 5, Math.floor(i / 5)], ...([0, 4, 5, 9].includes(i) ? { prep: true } : {}) })), start: [0, 4, 5, 9], boss: [1, 2, 3, 6, 7, 8] },
  memory: siLine(4), mirror: siLine(4),   // 准备 / 小怪 / 小怪 / 领主 [YW-忆][YW-镜]
  gateL: siLine(3), gateR: siLine(3, { rtl: true }),   // 准备 / 小怪 / 领主；奈克斯那张左右镜像、从右往左走 [YW-门]
  // 无欲之棺：约 8 房、领主每次进图随机（不在准备房）[QQ][SR-P2]【存疑：具体形状】
  sub: { cols: 4, rows: 2, links: 'grid', hideBoss: true, rooms: Array.from({ length: 8 }, (_, i) => ({ at: [i % 4, Math.floor(i / 4)], ...(i === 0 ? { prep: true } : {}) })), start: 0, boss: [1, 2, 3, 4, 5, 6, 7] },
  twisted: siLine(4), con: siLine(3),   // 【存疑：房间数】
  coffin: siLine(3, { rooms: { 1: { mobs: SIROCO_RAID_MOBS.shard } } }),
  // 幻影之界：准备 / 小怪 / 崔拉（精英）/ 小怪 / 昙娜（精英）/ 小怪 / 崔拉 & 昙娜 [91-界]
  phantom: siLine(7, { rooms: { 2: { type: 'elite', elite: 'siRaidMob_kula' }, 4: { type: 'elite', elite: 'siRaidMob_tanna' } } }),
  day: siLine(5), castle: siLine(2),   // 【存疑：房间数】
  deny: siLine(3), forget: siLine(2),
  // 压抑：4×4 迷雾，领主随机在外圈“┛”的 7 个房间之一 [NAMU-C1]【存疑：具体形状】
  suppress: { cols: 4, rows: 4, links: 'grid', hideBoss: true, rooms: Array.from({ length: 16 }, (_, i) => ({ at: [i % 4, Math.floor(i / 4)], ...(i === 0 ? { prep: true } : {}) })), start: 0, boss: [3, 7, 11, 15, 14, 13, 12] },
  truth: siLine(3, { rooms: { 1: { mobs: SIROCO_RAID_MOBS.shard } } }),
  shadow: { cols: 1, rows: 1, rooms: [{ at: [0, 0], type: 'boss' }], start: 0, boss: 0 },   // 阴影之棺：只有领主房
};
const defineSirocoRaid = (id, name, theme, mobs, elite, boss, extra = {}) => defineDungeon(id, { ...SIROCO_RAID_COMMON, ...extra, id, name, theme, mobs: SIROCO_RAID_MOBS[mobs] || mobs, elite, boss: { kind: boss, lvl: extra.bossLvl || 64 }, desc: `【希洛克攻坚】${name}。团本节点专用地图（官方固定房间结构），不消耗疲劳。` });
defineSirocoRaid('raid_si_law', '破坏之门', 'siroRaidGate', 'gate', 'siRaidMob_gate', 'siRaidBoss_gatekeeper', { fixed: SIROCO_RAID_LAYOUT.law, bossLvl: 62 });
defineSirocoRaid('raid_si_dawn', '梦幻之黎明', 'siroRaidMirror', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_haniel', { fixed: SIROCO_RAID_LAYOUT.dawn, bossLvl: 62 });
defineSirocoRaid('raid_si_night', '噩梦之夜', 'siroRaidCoffin', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_lena', { fixed: SIROCO_RAID_LAYOUT.night, bossLvl: 62 });
defineSirocoRaid('raid_si_memory', '记忆的碎片', 'siroRaidMirror', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_gusty', { fixed: SIROCO_RAID_LAYOUT.memory, bossLvl: 63 });
defineSirocoRaid('raid_si_mirror', '痛苦之镜', 'siroRaidMirror', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_grumi', { fixed: SIROCO_RAID_LAYOUT.mirror, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_l', '无形之门 1', 'siroRaidGate', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_vita', { fixed: SIROCO_RAID_LAYOUT.gateL, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_r', '无形之门 2', 'siroRaidGate', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_nex', { fixed: SIROCO_RAID_LAYOUT.gateR, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_duo', '无形之门', 'siroRaidGate', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_vita', { fixed: SIROCO_RAID_LAYOUT.gateL, bossLvl: 63 });
defineSirocoRaid('raid_si_sub', '无欲之棺', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_nightmare', { fixed: SIROCO_RAID_LAYOUT.sub, bossLvl: 63 });
defineSirocoRaid('raid_si_con', '意识之棺', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_phantom', { fixed: SIROCO_RAID_LAYOUT.con, bossLvl: 63 });
defineSirocoRaid('raid_si_mutant', '扭曲的无欲之棺', 'siroRaidMirror', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_crone', { fixed: SIROCO_RAID_LAYOUT.twisted, bossLvl: 63 });
defineSirocoRaid('raid_si_coffin', '真理的意识之棺', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_siroco', { fixed: SIROCO_RAID_LAYOUT.coffin, lvl: [63, 64], bossLvl: 64, bgm: 'abyss' });
defineSirocoRaid('raid_si_phantom', '幻影之界', 'siroRaidMirror', 'cult', 'siRaidMob_kula', 'siRaidBoss_kulaTanna', { fixed: SIROCO_RAID_LAYOUT.phantom, bossLvl: 62 });
defineSirocoRaid('raid_si_day', '归还之昼', 'siroRaidGate', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_myungho', { fixed: SIROCO_RAID_LAYOUT.day, bossLvl: 62 });
defineSirocoRaid('raid_si_castle', '幻影之城', 'siroRaidGate', 'cult', 'siRaidMob_grimElder', 'siRaidBoss_rodos', { fixed: SIROCO_RAID_LAYOUT.castle, bossLvl: 63 });
defineSirocoRaid('raid_si_deny', '无欲之棺：否定', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_nightmare2', { fixed: SIROCO_RAID_LAYOUT.deny, bossLvl: 63 });
defineSirocoRaid('raid_si_suppress', '无欲之棺：压抑', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_kain', { fixed: SIROCO_RAID_LAYOUT.suppress, bossLvl: 63 });
defineSirocoRaid('raid_si_forget', '无欲之棺：忘却', 'siroRaidMirror', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_luxi', { fixed: SIROCO_RAID_LAYOUT.forget, bossLvl: 63 });
defineSirocoRaid('raid_si_truth_g', '真理的意识之棺 · 基里', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_formGiri', { fixed: SIROCO_RAID_LAYOUT.truth, lvl: [63, 64], bossLvl: 64 });
defineSirocoRaid('raid_si_truth_l', '真理的意识之棺 · 莱斯特', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_formLester', { fixed: SIROCO_RAID_LAYOUT.truth, lvl: [63, 64], bossLvl: 64 });
defineSirocoRaid('raid_si_truth_v', '真理的意识之棺 · 拉维茜', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_formLavicy', { fixed: SIROCO_RAID_LAYOUT.truth, lvl: [63, 64], bossLvl: 64 });
defineSirocoRaid('raid_si_shadow', '阴影之棺', 'siroRaidCoffin', 'coffin', 'siRaidMob_grimElder', 'siRaidBoss_siroco', { fixed: SIROCO_RAID_LAYOUT.shadow, lvl: [64, 64], bossLvl: 64, bgm: 'abyss' });
RAID_DEFS.siroco.rewards = { cur: 'raid_petal', p1: [{ cur: [3, 4] }, { key: 'raid_immaterial', n: [1, 2] }], p2: [{ cur: [12, 16] }, { table: [[82, { key: 'raid_immaterial', n: [2, 4] }], [18, { pick: SIROCO_RAID_GEAR, n: 1, gear: true }]] }] };
