/* =====================================================================
   希洛克攻坚战 · RA4 节点地下城
   每个节点使用独立主题、专属小怪和专属领主；规则核心仍在 raid_core.js。
   ===================================================================== */
const SIROCO_RAID_SPEC = { id: 'sirocoRaid', lvl: 63, power: 1.12, bossPower: 1.2, atkPower: 1.08 };
regionTheme('siroRaidMirror', { grade: { tint: 'rgba(40,170,200,0.13)', fog: 'rgba(90,220,255,0.1)' }, ambient: 'motes', rgb: '110,220,255', pal: { sky: ['#061d2b', '#0b4a5c', '#16849a'], far: '#03121b', haze: '#58ddf0', floor: ['#092d3b', '#0d5361', '#061d2b'], line: 'rgba(120,240,255,.5)' } });
regionTheme('siroRaidCoffin', { grade: { tint: 'rgba(170,50,190,0.16)', fog: 'rgba(230,120,255,0.1)' }, ambient: 'wisps', rgb: '220,120,255', pal: { sky: ['#16051f', '#42135c', '#812b95'], far: '#0b0312', haze: '#e078ff', floor: ['#25102f', '#4b1d58', '#1b0925'], line: 'rgba(236,130,255,.48)' } });
regionTheme('siroRaidGate', { grade: { tint: 'rgba(220,155,40,0.13)', fog: 'rgba(255,210,90,0.08)' }, ambient: 'motes', rgb: '255,205,110', pal: { sky: ['#211306', '#5c3410', '#a56a1b'], far: '#120a03', haze: '#ffd36a', floor: ['#38220c', '#674116', '#241407'], line: 'rgba(255,220,130,.48)' } });
const SIROCO_RAID_MOB_DEFS = {
  siRaidMob_lawSentinel: { name: '法则刻印卫', tier: 'elite', arch: 'guard', size: [20, 15, 124], weight: 3, elem: 'light', art: ['jailer', { hue: 48, sat: 1.25, bright: 1.08 }], skills: [{ use: 'guard', dur: 1.8, reduce: 0.72, cd: [7, 10], counter: { use: 'aoe', shape: 'circle', at: 'self', r: 110, windup: 0.5, dmg: 1.15 } }, { use: 'swipe', clip: 'slam', reach: 104, width: 30, windup: 0.65, dmg: 1.25, cd: [2.2, 3.3] }] },
  siRaidMob_runeRunner: { name: '逆律追猎者', arch: 'aggressive', elem: 'dark', art: ['siPhantom', { hue: -35, sat: 1.4, bright: 0.78 }], skills: [{ use: 'dash', len: 300, speed: 670, windup: 0.65, dmg: 1.05, cd: [3.8, 5.2] }, { use: 'swipe', n: 2, reach: 78, dmg: 0.9, cd: [1.3, 2.1] }] },
  siRaidMob_wisdomMoth: { name: '知性裂翼', tier: 'flier', arch: 'flier', size: [15, 12, 74], elem: 'ice', art: ['gazer', { hue: 95, sat: 1.35, bright: 1.18 }], skills: [{ use: 'shot', mode: 'spread', n: 3, spread: 52, speed: 320, dmg: 0.76, status: 'slow', cd: [3.8, 5] }, { use: 'aoe', shape: 'ring', at: 'self', r: 115, r0: 48, windup: 1, dmg: 1.05, cd: [7, 9] }] },
  siRaidMob_memoryWeaver: { name: '记忆织梦师', tier: 'caster', arch: 'kiter', elem: 'light', art: ['voidcaster', { hue: 65, sat: 1.45, bright: 1.15 }], skills: [{ use: 'shot', mode: 'homing', n: 2, speed: 240, turn: 2.4, dmg: 0.85, cd: [3.2, 4.8] }, { use: 'buff', kind: 'shield', target: 'allies', r: 240, amt: 0.12, dur: 7, cd: [12, 17] }, { use: 'mark', delay: 0.9, r: 58, dmg: 1, cd: [6, 8] }] },
  siRaidMob_painHound: { name: '痛苦噬魂犬', arch: 'aggressive', elem: 'fire', art: ['hound', { hue: 45, sat: 1.7, bright: 0.82 }], skills: [{ use: 'dash', clip: 'chargeW', len: 360, speed: 730, windup: 0.7, dmg: 1.2, cd: [3.5, 5.5] }, { use: 'swipe', clip: 'bite', reach: 66, dmg: 1, cd: [1.2, 2.2] }] },
  siRaidMob_mirrorMimic: { name: '镜中拟态体', tier: 'swarm', arch: 'swarm', size: [12, 10, 58], scale: 0.82, elem: 'dark', art: ['siPhantom', { hue: 155, sat: 0.9, bright: 0.72 }], skills: [{ use: 'seq', cd: [5, 7], steps: [{ use: 'blink', to: 'behind', dist: 54 }, { use: 'swipe', n: 2, reach: 56, dmg: 0.72 }] }, { use: 'explode', r: 78, windup: 0.8, dmg: 1.25, cd: [5.5, 7.5] }] },
  siRaidMob_gateCrusher: { name: '无形碎门兽', tier: 'brute', arch: 'guard', size: [22, 16, 126], weight: 4, scale: 1.08, elem: 'dark', art: ['gatekeeper', { hue: 115, sat: 1.15, bright: 0.78 }], skills: [{ use: 'swipe', clip: 'slam', reach: 112, width: 34, windup: 0.75, dmg: 1.4, cd: [2.4, 3.5] }, { use: 'aoe', shape: 'cross', at: 'target', hw: 22, windup: 1.05, dmg: 1.25, cd: [6.5, 8.5] }] },
  siRaidMob_coffinWisp: { name: '棺中幽辉', tier: 'flier', arch: 'flier', elem: 'dark', art: ['gazer', { hue: 180, sat: 1.2, bright: 0.86 }], skills: [{ use: 'laser', windup: 0.9, dur: 0.9, sweep: 70, dmg: 0.48, cd: [5.5, 7.5] }, { use: 'shot', mode: 'homing', n: 2, speed: 260, turn: 2, dmg: 0.82, cd: [3.5, 5] }] },
  siRaidMob_thoughtEater: { name: '意识吞食者', tier: 'brute', arch: 'aggressive', size: [18, 14, 112], weight: 2.8, speed: 92, elem: 'dark', art: ['jailer', { hue: -95, sat: 0.8, bright: 0.86 }], skills: [{ use: 'pull', r: 260, dur: 0.8, cd: [7, 10] }, { use: 'swipe', clip: 'slam', reach: 96, width: 30, windup: 0.65, dmg: 1.35, cd: [2.3, 3.4] }] },
  siRaidMob_dreamShard: { name: '梦境碎片', tier: 'swarm', arch: 'swarm', size: [11, 10, 54], scale: 0.76, elem: 'light', art: ['voidcaster', { hue: 35, sat: 0.55, bright: 1.35 }], skills: [{ use: 'shot', mode: 'spread', n: 2, spread: 35, speed: 250, dmg: 0.65, cd: [2.6, 3.8] }, { use: 'explode', r: 70, windup: 0.7, dmg: 1.1, cd: [4.5, 6] }] },
  siRaidMob_nullPriest: { name: '虚无祷告者', tier: 'caster', arch: 'kiter', elem: 'dark', art: ['voidcaster', { hue: -75, sat: 1.2, bright: 0.7 }], skills: [{ use: 'aoe', shape: 'circle', at: 'target', r: 62, windup: 0.9, dmg: 1.05, status: 'slow', cd: [5, 7] }, { use: 'buff', kind: 'shield', target: 'allies', r: 240, amt: 0.1, dur: 6, cd: [11, 15] }] },
  siRaidMob_veilWalker: { name: '幻界行者', arch: 'aggressive', elem: 'dark', art: ['assassin', { hue: -125, sat: 1.1, bright: 0.75 }], skills: [{ use: 'seq', cd: [5.5, 7.5], steps: [{ use: 'blink', to: 'behind', dist: 80 }, { use: 'swipe', n: 3, reach: 80, dmg: 0.82 }] }, { use: 'dash', len: 330, speed: 700, windup: 0.7, dmg: 1.15, cd: [4.5, 6.5] }] },
  siRaidMob_soulAnchor: { name: '灵魂锚兽', tier: 'elite', arch: 'guard', elem: 'light', art: ['jailer', { hue: 175, sat: 0.9, bright: 1.08 }], skills: [{ use: 'guard', dur: 2, reduce: 0.78, cd: [8, 11], counter: { use: 'aoe', shape: 'circle', at: 'self', r: 100, windup: 0.45, dmg: 1.1 } }, { use: 'mark', delay: 0.8, r: 68, dmg: 1, cd: [6, 8] }] },
};
for (const [id, M] of Object.entries(SIROCO_RAID_MOB_DEFS)) regionMonster(SIROCO_RAID_SPEC, id, M, false);
const raidMech = (use, o = {}) => ({ use: 'mech', mech: { use, ...o }, cd: [14, 19] });
const raidBoss = (id, name, art, elem, first, second, extra = {}) => regionMonster(SIROCO_RAID_SPEC, id, { name, lvl: extra.lvl || 64, size: extra.size || [18, 15, 126], speed: extra.speed || 100, elem, art, hook: extra.hook, mechs: extra.mechs || [{ use: 'groggy', max: 108, dur: 6 }], phases: [{ at: 1, skills: first }, { at: 0.5, enter: extra.enter || { say: `${name}进入第二阶段！`, mechs: [{ use: 'safezone', windup: 2.6, n: 1, r: 72, frac: 0.4 }] }, skills: second }] }, true);
raidBoss('siRaidBoss_gatekeeper', '法则守门者', 'gatekeeper', 'light', [{ use: 'lanes', kind: 'bolt', lanes: 4, hit: 2, windup: 0.9, dmg: 1.15, cd: [8, 10] }, { use: 'guard', dur: 2.1, reduce: 0.75, cd: [9, 12] }, { use: 'swipe', n: 3, reach: 112, dmg: 1.25, cd: [2.2, 3.4] }], [{ use: 'aoe', shape: 'cross', at: 'target', hw: 24, windup: 0.9, dmg: 1.3, cd: [7, 9] }, { use: 'lanes', kind: 'bolt', lanes: 5, hit: 3, windup: 0.8, dmg: 1.15, cd: [9, 11] }], { mechs: [{ use: 'groggy', max: 100, dur: 6 }, { use: 'enrage', t: 210 }] });
raidBoss('siRaidBoss_haniel', '梦幻哈妮尔', 'assassin', 'dark', [{ use: 'seq', cd: [7, 9], steps: [{ use: 'blink', to: 'behind', dist: 88 }, { use: 'swipe', n: 3, reach: 86, dmg: 1.05 }] }, { use: 'mark', mode: 'burst', delay: 1.2, r: 92, dmg: 1.45, cd: [9, 12] }, raidMech('clones', { n: 2, dur: 8, punish: 'nova' })], [{ use: 'pool', at: 'target', r: 78, windup: 0.9, linger: 5, zone: 'blind', dmg: 0.3, cd: [7, 9] }, { use: 'seq', cd: [8, 11], steps: [{ use: 'blink', to: 'behind', dist: 112 }, { use: 'swipe', n: 4, reach: 92, dmg: 1.12 }] }], { mechs: [{ use: 'groggy', max: 96, dur: 5 }] });
raidBoss('siRaidBoss_lena', '狙击手莱娜', 'luxi', 'ice', [{ use: 'shot', mode: 'homing', n: 3, speed: 320, turn: 2.5, dmg: 0.95, cd: [4, 6] }, { use: 'dash', len: 380, speed: 720, windup: 0.8, dmg: 1.2, cd: [7, 9] }, { use: 'aoe', shape: 'line', at: 'target', hw: 28, windup: 1.1, dmg: 1.25, cd: [8, 11] }], [raidMech('safezone', { windup: 2.4, n: 2, r: 70, frac: 0.35 }), { use: 'laser', windup: 0.9, dur: 1.1, sweep: 80, dmg: 0.42, cd: [7, 9] }], { mechs: [{ use: 'groggy', max: 100, dur: 5 }] });
raidBoss('siRaidBoss_gusty', '贪食古斯提', 'gazer', 'dark', [{ use: 'pull', r: 300, dur: 0.85, cd: [8, 11] }, { use: 'pool', at: 'target', r: 92, windup: 0.9, linger: 5, zone: 'poison', dmg: 0.25, cd: [7, 9] }, { use: 'swipe', n: 2, reach: 118, dmg: 1.35, cd: [2.6, 3.8] }], [{ use: 'rain', kind: 'hex', n: 6, r: 48, spread: 190, windup: 0.9, dmg: 1.1, cd: [7, 9] }, { use: 'pull', r: 360, dur: 1, cd: [11, 14] }], { mechs: [{ use: 'groggy', max: 108, dur: 6 }, { use: 'enrage', t: 240 }] });
raidBoss('siRaidBoss_grumi', '漂流古鲁米', 'gazer', 'fire', [{ use: 'laser', windup: 0.8, dur: 1.1, sweep: 72, dmg: 0.4, cd: [6, 8] }, { use: 'shot', mode: 'spread', n: 5, spread: 48, speed: 300, dmg: 0.72, cd: [4, 6] }, { use: 'aoe', shape: 'ring', at: 'target', r: 128, r0: 48, windup: 1.1, dmg: 1.25, cd: [8, 11] }], [raidMech('safezone', { windup: 2.5, n: 2, r: 74, frac: 0.4 }), { use: 'laser', windup: 0.7, dur: 1.4, sweep: 105, dmg: 0.45, cd: [6, 8] }], { mechs: [{ use: 'groggy', max: 106, dur: 6 }] });
raidBoss('siRaidBoss_vita', '慈悲维塔', 'nex', 'light', [{ use: 'shot', mode: 'homing', n: 3, speed: 300, turn: 2.1, dmg: 0.92, cd: [4, 6] }, { use: 'aoe', shape: 'cross', at: 'target', hw: 25, windup: 1, dmg: 1.2, cd: [7, 9] }, { use: 'guard', dur: 1.8, reduce: 0.7, cd: [9, 12] }], [{ use: 'lanes', kind: 'bolt', lanes: 5, hit: 3, windup: 0.85, dmg: 1.1, cd: [8, 10] }], { mechs: [{ use: 'groggy', max: 112, dur: 6 }, { use: 'element', modes: ['light', 'dark'], every: 12, mul: 0.45 }] });
raidBoss('siRaidBoss_nex', '慈悲奈克斯', 'nex', 'dark', [{ use: 'swipe', n: 3, reach: 110, dmg: 1.2, cd: [2.3, 3.5] }, { use: 'shot', mode: 'homing', n: 2, speed: 270, turn: 2.4, dmg: 0.85, cd: [4, 5.5] }, { use: 'aoe', at: 'self', shape: 'circle', r: 132, windup: 1, dmg: 1.25, cd: [8, 10] }], [raidMech('shield', { hp: 0.05, dur: 14, punish: 'nova', onBreak: 'groggy' }), { use: 'rain', kind: 'bolt', n: 4, r: 52, windup: 1, dmg: 1.15, cd: [7, 9] }], { mechs: [{ use: 'groggy', max: 112, dur: 6 }, { use: 'shield', hp: 0.04, dur: 16, punish: 'heal', onBreak: 'groggy' }] });
raidBoss('siRaidBoss_nightmare', '希洛克的噩梦', 'siroco', 'dark', [{ use: 'seq', cd: [7, 9], steps: [{ use: 'blink', to: 'away', dist: 100 }, { use: 'shot', mode: 'spread', n: 5, spread: 42, speed: 280, dmg: 0.7 }] }, { use: 'pool', at: 'target', r: 96, windup: 0.9, linger: 6, zone: 'blind', dmg: 0.3, cd: [8, 10] }, raidMech('clones', { n: 3, dur: 9, punish: 'nova' })], [{ use: 'laser', windup: 0.9, dur: 1.3, sweep: 90, dmg: 0.44, cd: [7, 9] }], { hook: 'siroco' });
raidBoss('siRaidBoss_phantom', '希洛克的幻影', 'siroco', 'dark', [{ use: 'mark', mode: 'share', delay: 1.25, r: 110, dmg: 1.4, cd: [9, 12] }, { use: 'rain', kind: 'bolt', n: 5, r: 50, spread: 160, windup: 0.9, dmg: 1.05, cd: [8, 10] }, { use: 'seq', cd: [8, 11], steps: [{ use: 'blink', to: 'behind', dist: 90 }, { use: 'swipe', n: 4, reach: 92, dmg: 1.1 }] }], [raidMech('clones', { n: 4, dur: 10, punish: 'nova' }), { use: 'pool', at: 'target', r: 88, windup: 0.8, linger: 5, zone: 'slow', dmg: 0.25, cd: [6, 8] }], { hook: 'siroco', mechs: [{ use: 'groggy', max: 118, dur: 7 }] });
raidBoss('siRaidBoss_crone', '梦中老妪', 'voidCaster', 'light', [{ use: 'shot', mode: 'homing', n: 3, speed: 250, turn: 2.2, dmg: 0.9, cd: [4, 6] }, { use: 'buff', kind: 'shield', target: 'allies', r: 260, amt: 0.12, dur: 7, cd: [13, 17] }, { use: 'pool', at: 'target', r: 80, windup: 0.9, linger: 6, zone: 'poison', dmg: 0.25, cd: [7, 9] }], [{ use: 'lanes', kind: 'wave', lanes: 4, hit: 2, windup: 0.9, dmg: 1.2, cd: [8, 10] }, { use: 'mark', mode: 'move', delay: 1, dur: 3, frac: 0.04, cd: [10, 13] }]);
raidBoss('siRaidBoss_siroco', '无形之希洛克', 'siroco', 'dark', [{ use: 'swipe', n: 4, reach: 128, width: 38, windup: 0.55, dmg: 1.32, cd: [2.4, 3.6] }, { use: 'shot', mode: 'homing', n: 4, speed: 300, turn: 2.3, dmg: 0.86, cd: [5, 7] }, { use: 'mech', mech: { use: 'clones', n: 3, dur: 10, punish: 'nova' }, cd: [15, 19] }], [{ use: 'laser', windup: 0.8, dur: 1.6, sweep: 110, dmg: 0.48, cd: [7, 9] }, { use: 'rain', kind: 'bolt', n: 7, r: 50, spread: 220, windup: 0.9, dmg: 1.15, cd: [8, 10] }], { lvl: 64, size: [24, 18, 154], speed: 108, hook: 'siroco', mechs: [{ use: 'groggy', max: 125, dur: 8, mul: 1.6 }, { use: 'enrage', t: 300 }], enter: { say: '无形之棺闭合——背对凝视并击破记忆碎片！', mechs: [{ use: 'invuln', until: 'crystals', n: 4, name: '记忆碎片', hpFrac: 0.02 }] });
Object.assign(MON_ART, { siRaidMob_lawSentinel: ['sirocoRaidGuardian'], siRaidMob_mirrorMimic: ['sirocoRaidMimic'], siRaidBoss_phantom: ['sirocoRaidPhantom'], siRaidBoss_siroco: ['sirocoRaidFinal'] });
const SIROCO_RAID_COMMON = { raid: true, hidden: true, layout: 'raid', branches: 1, cols: 5, rows: 3, rooms: 5, bossAdds: 0, lvl: [62, 63], clearExp: 0, bgm: 'dungeon', bossBgm: 'boss' };
const SIROCO_RAID_MOBS = {
  law: [['siRaidMob_runeRunner', 2.5], ['siRaidMob_lawSentinel', 1.5], ['siRaidMob_gateCrusher', 1], ['siRaidMob_dreamShard', 1.5]],
  wit: [['siRaidMob_wisdomMoth', 2.5], ['siRaidMob_memoryWeaver', 1.5], ['siRaidMob_veilWalker', 1.5], ['siRaidMob_dreamShard', 1]],
  pain: [['siRaidMob_painHound', 2.5], ['siRaidMob_mirrorMimic', 2], ['siRaidMob_thoughtEater', 1], ['siRaidMob_nullPriest', 1]],
  coffin: [['siRaidMob_coffinWisp', 2], ['siRaidMob_memoryWeaver', 1.5], ['siRaidMob_mirrorMimic', 1.5], ['siRaidMob_thoughtEater', 1], ['siRaidMob_dreamShard', 1]],
};
const defineSirocoRaid = (id, name, theme, mobs, elite, boss, extra = {}) => defineDungeon(id, { ...SIROCO_RAID_COMMON, ...extra, id, name, theme, mobs: SIROCO_RAID_MOBS[mobs] || mobs, elite, boss: { kind: boss, lvl: extra.bossLvl || 64 }, desc: `【希洛克攻坚】${name}。团本节点专用地图，不消耗疲劳。` });
defineSirocoRaid('raid_si_law', '破坏之门', 'siroRaidGate', 'law', 'siRaidMob_lawSentinel', 'siRaidBoss_gatekeeper', { rooms: 5, branches: 0, bossLvl: 62 });
defineSirocoRaid('raid_si_dawn', '梦幻之黎明', 'siroRaidMirror', 'wit', 'siRaidMob_memoryWeaver', 'siRaidBoss_haniel', { rooms: 5, branches: 1, bossLvl: 62 });
defineSirocoRaid('raid_si_night', '噩梦之夜', 'siroRaidCoffin', 'wit', 'siRaidMob_wisdomMoth', 'siRaidBoss_lena', { rooms: 4, branches: 0, bossLvl: 62 });
defineSirocoRaid('raid_si_memory', '记忆的碎片', 'siroRaidMirror', 'pain', 'siRaidMob_thoughtEater', 'siRaidBoss_gusty', { rooms: 5, branches: 1, bossLvl: 63 });
defineSirocoRaid('raid_si_mirror', '痛苦之镜', 'siroRaidMirror', 'pain', 'siRaidMob_mirrorMimic', 'siRaidBoss_grumi', { rooms: 4, branches: 0, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_l', '无形之门·左', 'siroRaidGate', 'law', 'siRaidMob_gateCrusher', 'siRaidBoss_vita', { rooms: 5, branches: 1, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_r', '无形之门·右', 'siroRaidGate', 'law', 'siRaidMob_runeRunner', 'siRaidBoss_nex', { rooms: 5, branches: 1, bossLvl: 63 });
defineSirocoRaid('raid_si_gate_duo', '无形之门', 'siroRaidGate', 'law', 'siRaidMob_gateCrusher', 'siRaidBoss_vita', { rooms: 6, branches: 1, bossLvl: 63 });
defineSirocoRaid('raid_si_sub', '潜意识之厅', 'siroRaidCoffin', 'coffin', 'siRaidMob_coffinWisp', 'siRaidBoss_nightmare', { rooms: 5, branches: 0, bossLvl: 63 });
defineSirocoRaid('raid_si_con', '意识之厅', 'siroRaidCoffin', 'coffin', 'siRaidMob_thoughtEater', 'siRaidBoss_phantom', { rooms: 6, branches: 1, bossLvl: 63 });
defineSirocoRaid('raid_si_mutant', '变异的潜意识之厅', 'siroRaidMirror', 'pain', 'siRaidMob_nullPriest', 'siRaidBoss_crone', { rooms: 5, branches: 0, bossLvl: 63 });
defineSirocoRaid('raid_si_coffin', '真·意识之棺', 'siroRaidCoffin', 'coffin', 'siRaidMob_soulAnchor', 'siRaidBoss_siroco', { rooms: 7, branches: 1, lvl: [63, 64], bossLvl: 64, bgm: 'abyss' });
RAID_DEFS.siroco.rewards = { cur: 'raid_petal', p1: [{ cur: [3, 4] }, { key: 'raid_immaterial', n: [1, 2] }], p2: [{ cur: [12, 16] }, { table: [[82, { key: 'raid_immaterial', n: [2, 4] }], [18, { pick: SIROCO_RAID_GEAR, n: 1, gear: true }]] }] };
