"""装备 2.0 · 格斗家武器（B8 二期）：72 件具名史诗 + 17 件领主神器 / 粉装的图标（只做图标；拿在手里 = <类型>_r4 / _r3 + 物品上的 pal 配色）。
gear_icons.py 自动合并：python3 art/tools/gear_icons.py gen pink60_fighter_a；cut 同名（一张表 3×2 = 6 件，共 15 张）。物品定义在 src/content/items/epics60_w_fighter.js。
顺序：手套 → 拳套 → 爪 → 东方棍 → 臂铠（同类型尽量在同一张表，模型自己会拉开差别）；描述里的颜色和物品的 pal 对上。
"""
_KN = 'a martial-arts knuckle glove (fingerless-looking fighting glove on a clenched fist, wrist wrap, knuckle guard plate)'
_BX = 'a puffy rounded boxing glove with a laced wrist cuff'
_CL = 'a claw gauntlet (short glove cuff with three long straight parallel blades sticking forward past the knuckles)'
_TF = 'a tonfa (a straight fighting baton with a short perpendicular side handle near one end)'
_GA = 'a chunky armored arm gauntlet covering the forearm and the clenched fist'
_P = ', rose-pink artifact-grade gem and trim'

ITEMS = [
    # ---- 手套 knuckle ----
    ('ep_kn_dawn', f'{_KN}: plain cream cloth hand wraps wound tightly around a brown leather glove, a small sunrise emblem on the back'),
    ('ep_kn_blaze', f'{_KN}: crimson leather with a string of glowing red-orange prayer beads across the back of the hand, small flames'),
    ('ep_kn_puppet', f'{_KN}: dark purple velvet glove with tiny silver puppet strings hanging from the fingertips and a small wooden puppet charm'),
    ('ep_kn_windbell', f'{_KN}: white-and-sky-blue glove with a small silver wind bell hanging from the wrist and feather trim'),
    ('ep_kn_heaven', f'{_KN}: pale gold and white glove with a ring of glowing golden prayer beads wrapped around the wrist, halo glow'),
    ('ep_kn_moonshade', f'{_KN}: midnight-navy leather glove with a glowing silver crescent moon on the back of the hand'),
    ('ep_kn_diregie', f'{_KN}: dark moss-green glove leaking wisps of purple poison smoke from vents on the knuckles'),
    ('ep_kn_piper', f'{_KN}: elegant white conductor glove with gold cuff, violet musical-note charms floating around it'),
    ('ep_kn_gentmage', f'{_KN}: royal blue glove with gold filigree and a big glowing light-blue crystal set in the back of the hand'),
    ('ep_kn_tiger', f'{_KN}: black glove whose back is a snarling tiger head, eerie blue-violet ghost fire burning in its open mouth'),
    ('ep_kn_lotus', f'{_KN}: pale pink silk glove embroidered with a golden thousand-petal lotus that glows on the back of the hand'),
    ('ep_kn_skyroar', f'{_KN}: bright sky-blue glove with white hawk-wing guards on the knuckles, streaks of wind'),
    ('ep_kn_evilend', f'{_KN}: polished silver-white glove with a golden exorcism cross engraved on the knuckle plate, holy light'),
    ('ep_kn_bonesoul', f'{_KN}: majestic gold glove with violet energy cracks and a glowing violet nen-energy orb on the back, crackling light'),
    ('nm_kn_kaino', f'{_KN}: dark steel-grey glove with yellow lightning bolts sparking from the fingertips' + _P),
    ('nm_kn_spiz', f'{_KN}: sickly green-black dragon-scale glove with a red dragon eye and dripping green corpse poison' + _P),
    ('nm_kn_goliath', f'{_KN}: huge blackened giant-size glove with molten orange lava cracks glowing between the plates' + _P),
    ('nm_kn_mozhen', f'{_KN}: dark brown leather glove with sharp white hound fangs set along the knuckles' + _P),
    ('nm_kn_utara', f'{_KN}: brown beast-tamer glove with golden lion-mane fur cuff and a gold beast-king crest' + _P),
    # ---- 拳套 boxing ----
    ('ep_bx_redstar', f'{_BX}: classic red boxing glove with a big yellow star stitched on the back'),
    ('ep_bx_tauking', f'{_BX}: rough dark-brown hide boxing glove with a short bull horn sticking up from the cuff'),
    ('ep_bx_golem', f'{_BX}: boxing glove carved out of sandy grey stone with glowing amber cracks'),
    ('ep_bx_champion', f'{_BX}: shiny royal-blue champion boxing glove with gold trim and a small gold champion belt buckle on the cuff'),
    ('ep_bx_sinfist', f'{_BX}: dark purple-black boxing glove with a single crimson demonic eye open on the back'),
    ('ep_bx_spider', f'{_BX}: plum-purple boxing glove wrapped in shiny silver spider silk threads'),
    ('ep_bx_headless', f'{_BX}: black iron armored boxing glove, empty and ghostly, pale blue spectral mist leaking from the cuff'),
    ('ep_bx_piston', f'{_BX}: steel steampunk boxing glove with a big brass piston on the back and white steam puffing out'),
    ('ep_bx_gentguard', f'{_BX}: navy-blue boxing glove with gold royal crest and gold laces'),
    ('ep_bx_flash', f'{_BX}: sleek black boxing glove with white speed-line lightning streaks, extremely clean and fast-looking'),
    ('ep_bx_emperor', f'{_BX}: gleaming gold emperor boxing glove with white trim and a small crown on the cuff'),
    ('ep_bx_phantom', f'{_BX}: semi-transparent pale icy-white ghostly boxing glove glowing soft blue light'),
    ('ep_bx_dragonrage', f'{_BX}: fiery red boxing glove with a golden dragon coiled around it breathing flames'),
    ('ep_bx_warsoul', f'{_BX}: battle-worn crimson boxing glove with gold bands and a burning orange war-spirit aura'),
    ('nm_bx_ruug', f'{_BX}: frosty ice-blue boxing glove covered in icicles and snow' + _P),
    ('nm_bx_mobeni', f'{_BX}: boxing glove covered in overlapping dark teal iron fish scales' + _P),
    # ---- 爪 claw ----
    ('ep_cl_goblin', f'{_CL}: crude bone-white blades lashed to a green goblin-leather cuff with twine'),
    ('ep_cl_dragonkin', f'{_CL}: green dragon-scale cuff with three orange-tinted reverse-scale blades'),
    ('ep_cl_bone', f'{_CL}: blades made of long bleached finger bones, dark purple cuff with a small skull'),
    ('ep_cl_stigma', f'{_CL}: ivory cuff with gold holy script engraved on the three straight blades'),
    ('ep_cl_wyvern', f'{_CL}: steel-blue wyvern-scale cuff, three blades shaped like sharp wyvern talons but straight'),
    ('ep_cl_lava', f'{_CL}: charred black cuff and blades with glowing red-hot lava edges'),
    ('ep_cl_raven', f'{_CL}: black raven-feather cuff with dark purple glowing straight blades'),
    ('ep_cl_goldhook', f'{_CL}: brown thief leather cuff with three golden blades ending in small hooks, a coin charm'),
    ('ep_cl_chitin', f'{_CL}: olive-green insect chitin cuff with serrated chitin blades dripping green venom'),
    ('ep_cl_zixiao', f'{_CL}: royal purple cuff with three blades crackling with violet lightning'),
    ('ep_cl_venomdragon', f'{_CL}: dark green poison-dragon cuff with purple fangs as blades, toxic purple mist'),
    ('ep_cl_scorpion', f'{_CL}: blood-red scorpion-shell cuff, the three blades split from one crimson scorpion tail stinger'),
    ('ep_cl_wuxuan', f'{_CL}: dark slate cuff with ghostly cyan soul flames flowing along the three blades'),
    ('ep_cl_nightraid', f'{_CL}: matte midnight-blue imperial cuff with frosted icy blades'),
    ('ep_cl_slaughter', f'{_CL}: menacing black cuff with three long blood-red blades and a red king crown emblem'),
    ('nm_cl_lotus', f'{_CL}: pale bone-white cuff with ghostly light-blue soul wisps swirling around the blades' + _P),
    ('nm_cl_morgan', f'{_CL}: dark shadowy cuff with long cursed purple fingernail blades' + _P),
    ('nm_cl_ranzhan', f'{_CL}: jagged uneven orange-red blades, three-headed hound bite marks on the cuff' + _P),
    # ---- 东方棍 tonfa ----
    ('ep_tf_oak', f'{_TF}: carved light oak wood with green leaf rune carvings and a small sprout'),
    ('ep_tf_thunder', f'{_TF}: dark iron-wood with yellow lightning sparks crackling along the baton'),
    ('ep_tf_amber', f'{_TF}: warm amber-resin tonfa with a tiny ancient insect trapped inside, brown wooden grip'),
    ('ep_tf_vine', f'{_TF}: twisted green living vines forming the baton, small leaves sprouting'),
    ('ep_tf_seraph', f'{_TF}: pure white baton with gold caps and small white angel wings on the side handle'),
    ('ep_tf_silvermoon', f'{_TF}: dark indigo baton with a silver crescent-moon shaped side handle'),
    ('ep_tf_gravekeeper', f'{_TF}: weathered grey graveyard baton with a small bronze bell hanging from the side handle, pale green glow'),
    ('ep_tf_steam', f'{_TF}: steel steampunk police baton with a small brass boiler on the side handle venting steam'),
    ('ep_tf_gentwatch', f'{_TF}: soot-black iron baton with glowing orange ember cracks at the tip'),
    ('ep_tf_shadow', f'{_TF}: pitch-black baton trailing violet shadow afterimages'),
    ('ep_tf_wushen', f'{_TF}: vermilion red lacquered baton with gold bands, sacred temple style'),
    ('ep_tf_mammoth', f'{_TF}: made from a single curved-but-straightened ivory mammoth tusk with brown fur-wrapped grip, frost'),
    ('ep_tf_butterfly', f'{_TF}: dark wine-red baton with a glowing blood-red butterfly perched on the side handle'),
    ('ep_tf_hurricane', f'{_TF}: jade-teal baton with a swirling mini tornado of wind wrapped around it'),
    ('nm_tf_suleide', f'{_TF}: navy-blue riot-police baton with gold stripes and a small blue dragon coiled on it' + _P),
    ('nm_tf_utara', f'{_TF}: deep red baton with a burning orange flame core glowing through a window in the middle' + _P),
    ('nm_tf_satan', f'{_TF}: dark purple baton topped with a small vial of glittering fallen-angel dust' + _P),
    # ---- 臂铠 gauntlet ----
    ('ep_ga_tau', f'{_GA}: dented plain iron plates strapped with brown leather, a bull-head rivet'),
    ('ep_ga_lava', f'{_GA}: black volcanic-rock plates with bright orange molten cracks'),
    ('ep_ga_bonedragon', f'{_GA}: made of pale bone-dragon claw bones with glowing blue joints'),
    ('ep_ga_silverguard', f'{_GA}: polished holy silver plates with gold edges and a sun emblem'),
    ('ep_ga_titan', f'{_GA}: massive bronze titan plates with glowing orange rune lines'),
    ('ep_ga_boroding', f'{_GA}: forged dark iron with four flattened hammer-head knuckles, brass rivets'),
    ('ep_ga_darklord', f'{_GA}: jet-black spiked dark-lord plates with crimson glowing seams'),
    ('ep_ga_testsubject', f'{_GA}: steel-blue mechanical power arm with glowing cyan energy tubes'),
    ('ep_ga_gt', f'{_GA}: grey robot arm with red panels and a rocket thruster on the elbow'),
    ('ep_ga_dragon', f'{_GA}: crimson gauntlet with a red dragon coiling from shoulder to fist, gold claws'),
    ('ep_ga_rage', f'{_GA}: battered gunmetal gauntlet with angry red glowing cracks and steam venting'),
    ('ep_ga_hero', f'{_GA}: gleaming silver hero gauntlet with gold laurel engravings'),
    ('ep_ga_icesoul', f'{_GA}: made of translucent pale-blue ice crystal with white frost'),
    ('ep_ga_brute', f'{_GA}: oversized reddish-brown brute gauntlet with gold bands, huge knuckles'),
    ('ep_ga_wailstar', f'{_GA}: deep violet gauntlet with a glowing star embedded in the fist, lavender stardust'),
    ('nm_ga_sauta', f'{_GA}: brown iron arm with a big curved bull horn strapped along the forearm' + _P),
    ('nm_ga_lik', f'{_GA}: frozen ice-giant arm plates, pale blue with dark blue frost runes' + _P),
    ('nm_ga_podir', f'{_GA}: dark red gauntlet with a small round flaming shield attached at the elbow' + _P),
    ('nm_ga_chaos', f'{_GA}: dark violet gauntlet with a gem where red, blue, gold and purple energies swirl and clash' + _P),
]
_N = 'abcdefghijklmnopqrstuvwxyz'
SHEETS = {f'pink60_fighter_{_N[i // 6]}': ITEMS[i:i + 6] + [('gear_spare', 'a small round golden coin')] * (6 - len(ITEMS[i:i + 6])) for i in range(0, len(ITEMS), 6)}
